export const verbBatchPartA = [
  // Comprehensive, authentic English verbs with Bengali meanings, phonetics and contextual sentences
  { english: "accept", bangla: "গ্রহণ করা", phonetic: "/əkˈsɛpt/", sentence: "She accepted the proposal gladly.", translation: "সে আনন্দের সাথে প্রস্তাবটি গ্রহণ করেছিল।" },
  { english: "achieve", bangla: "অর্জন করা", phonetic: "/əˈtʃiːv/", sentence: "He worked hard to achieve success.", translation: "সাফল্য অর্জন করতে সে কঠোর পরিশ্রম করেছিল।" },
  { english: "acquire", bangla: "অর্জন করা / লাভ করা", phonetic: "/əˈkwaɪər/", sentence: "Students acquire knowledge through reading.", translation: "শিক্ষার্থীরা পড়ার মাধ্যমে জ্ঞান অর্জন করে।" },
  { english: "act", bangla: "কাজ করা / অভিনয় করা", phonetic: "/ækt/", sentence: "You must act quickly in an emergency.", translation: "জরুরি পরিস্থিতিতে তোমাকে দ্রুত কাজ করতে হবে।" },
  { english: "adapt", bangla: "খাপ খাওয়ানো", phonetic: "/əˈdæpt/", sentence: "Animals adapt to their environment.", translation: "প্রাণীরা তাদের পরিবেশের সাথে খাপ খাইয়ে নেয়।" },
  { english: "add", bangla: "যোগ করা", phonetic: "/æd/", sentence: "Please add some sugar to the tea.", translation: "দয়া করে চায়ে কিছু চিনি যোগ করুন।" },
  { english: "admire", bangla: "প্রশংসা করা", phonetic: "/ədˈmaɪər/", sentence: "We admire his honesty and courage.", translation: "আমরা তার সততা ও সাহসের প্রশংসা করি।" },
  { english: "admit", bangla: "স্বীকার করা / ভর্তি করা", phonetic: "/ədˈmɪt/", sentence: "He admitted his mistake politely.", translation: "সে ভদ্রভাবে তার ভুল স্বীকার করেছিল।" },
  { english: "adopt", bangla: "দত্তক নেওয়া / গ্রহণ করা", phonetic: "/əˈdɒpt/", sentence: "They decided to adopt a new strategy.", translation: "তারা একটি নতুন কৌশল গ্রহণ করার সিদ্ধান্ত নিয়েছিল।" },
  { english: "advise", bangla: "উপদেশ দেওয়া", phonetic: "/ədˈvaɪz/", sentence: "The doctor advised him to rest.", translation: "ডাক্তার তাকে বিশ্রাম নেওয়ার উপদেশ দিয়েছিলেন।" },
  { english: "affect", bangla: "প্রভাবিত করা", phonetic: "/əˈfɛkt/", sentence: "Cold weather affects his health.", translation: "ঠান্ডা আবহাওয়া তার স্বাস্থ্যকে প্রভাবিত করে।" },
  { english: "afford", bangla: "সামর্থ্য থাকা", phonetic: "/əˈfɔːrd/", sentence: "We can afford to buy a new laptop.", translation: "আমাদের একটি নতুন ল্যাপটপ কেনার সামর্থ্য আছে।" },
  { english: "agree", bangla: "একমত হওয়া", phonetic: "/əˈɡriː/", sentence: "I agree with your suggestion completely.", translation: "আমি তোমার প্রস্তাবের সাথে সম্পূর্ণ একমত।" },
  { english: "allow", bangla: "অনুমতি দেওয়া", phonetic: "/əˈlaʊ/", sentence: "Parents should allow children to play.", translation: "বাবা-মায়ের উচিত শিশুদের খেলতে অনুমতি দেওয়া।" },
  { english: "announce", bangla: "ঘোষণা করা", phonetic: "/əˈnaʊns/", sentence: "The headmaster announced the holiday.", translation: "প্রধান শিক্ষক ছুটির ঘোষণা করেছিলেন।" },
  { english: "apologize", bangla: "ক্ষমা চাওয়া", phonetic: "/əˈpɒlədʒaɪz/", sentence: "You should apologize for your rude behavior.", translation: "তোমার অভদ্র আচরণের জন্য ক্ষমা চাওয়া উচিত।" },
  { english: "appear", bangla: "উপস্থিত হওয়া / মনে হওয়া", phonetic: "/əˈpɪər/", sentence: "The moon appeared behind the clouds.", translation: "মেঘের আড়াল থেকে চাঁদ দেখা গেল।" },
  { english: "apply", bangla: "আবেদন করা / প্রয়োগ করা", phonetic: "/əˈplaɪ/", sentence: "He applied for a scholarship.", translation: "সে একটি বৃত্তির জন্য আবেদন করেছিল।" },
  { english: "appreciate", bangla: "প্রশংসা করা / কদর করা", phonetic: "/əˈpriːʃieɪt/", sentence: "I appreciate your kind assistance.", translation: "আমি তোমার সদয় সহযোগিতার কদর করি।" },
  { english: "approach", bangla: "নিকটবর্তী হওয়া", phonetic: "/əˈproʊtʃ/", sentence: "The train approached the station slowly.", translation: "ট্রেনটি ধীরে ধীরে স্টেশনের নিকটবর্তী হলো।" },
  { english: "arrange", bangla: "ব্যবস্থা করা / সাজানো", phonetic: "/əˈreɪndʒ/", sentence: "They arranged a beautiful farewell party.", translation: "তারা একটি সুন্দর বিদায় অনুষ্ঠানের ব্যবস্থা করেছিল।" },
  { english: "arrive", bangla: "পৌঁছানো", phonetic: "/əˈraɪv/", sentence: "The guests arrived on time.", translation: "অতিথিরা সময়মতো পৌঁছেছিলেন।" },
  { english: "ask", bangla: "জিজ্ঞাসা করা", phonetic: "/ɑːsk/", sentence: "Feel free to ask any question.", translation: "নির্দ্বিধায় যেকোনো প্রশ্ন জিজ্ঞাসা করুন।" },
  { english: "assist", bangla: "সাহায্য করা", phonetic: "/əˈsɪst/", sentence: "She assisted the elderly lady across the street.", translation: "সে বৃদ্ধা মহিলাকে রাস্তা পার হতে সাহায্য করেছিল।" },
  { english: "assume", bangla: "ধরে নেওয়া", phonetic: "/əˈsjuːm/", sentence: "Do not assume things without evidence.", translation: "প্রমাণ ছাড়া কোনো কিছু ধরে নেবেন না।" },
  { english: "attack", bangla: "আক্রমণ করা", phonetic: "/əˈtæk/", sentence: "The army attacked the enemy camp.", translation: "সেনাবাহিনী শত্রু শিবিরে আক্রমণ করেছিল।" },
  { english: "attempt", bangla: "চেষ্টা করা", phonetic: "/əˈtɛmpt/", sentence: "He attempted to solve the hard puzzle.", translation: "সে কঠিন ধাঁধাটি সমাধান করার চেষ্টা করেছিল।" },
  { english: "attend", bangla: "উপস্থিত থাকা", phonetic: "/əˈtɛnd/", sentence: "Students must attend class regularly.", translation: "শিক্ষার্থীদের অবশ্যই নিয়মিত ক্লাসে উপস্থিত থাকতে হবে।" },
  { english: "attract", bangla: "আকর্ষণ করা", phonetic: "/əˈtrækt/", sentence: "Bright flowers attract honeybees.", translation: "উজ্জ্বল ফুল মৌমাছিদের আকর্ষণ করে।" },
  { english: "avoid", bangla: "এড়িয়ে চলা", phonetic: "/əˈvɔɪd/", sentence: "Avoid eating junk food daily.", translation: "প্রতিদিন ফাস্টফুড খাওয়া এড়িয়ে চলুন।" },
  { english: "bake", bangla: "সেঁকা / বেক করা", phonetic: "/beɪk/", sentence: "Mother baked a delicious chocolate cake.", translation: "মা একটি সুস্বাদু চকলেট কেক বেক করেছিলেন।" },
  { english: "balance", bangla: "ভারসাম্য রাখা", phonetic: "/ˈbæləns/", sentence: "Try to balance work and personal life.", translation: "কাজ ও ব্যক্তিগত জীবনের ভারসাম্য রাখার চেষ্টা করুন।" },
  { english: "bark", bangla: "ঘেউ ঘেউ করা", phonetic: "/bɑːrk/", sentence: "The watchdog barked at the stranger.", translation: "পাহাড়াদার কুকুরটি অপরিচিত ব্যক্তির দিকে ঘেউ ঘেউ করেছিল।" },
  { english: "bathe", bangla: "স্নান করা", phonetic: "/beɪð/", sentence: "He bathes in the river every morning.", translation: "সে প্রতিদিন সকালে নদীতে স্নান করে।" },
  { english: "beat", bangla: "প্রহার করা / হারানো", phonetic: "/biːt/", sentence: "Our team beat the opponent easily.", translation: "আমাদের দল প্রতিপক্ষকে সহজেই হারিয়েছিল।" },
  { english: "become", bangla: "হওয়া", phonetic: "/bɪˈkʌm/", sentence: "She wants to become a doctor.", translation: "সে একজন ডাক্তার হতে চায়।" },
  { english: "beg", bangla: "ভিক্ষা চাওয়া / অনুনয় করা", phonetic: "/bɛɡ/", sentence: "He begged for mercy.", translation: "সে ক্ষমার জন্য অনুনয় করেছিল।" },
  { english: "begin", bangla: "শুরু করা", phonetic: "/bɪˈɡɪn/", sentence: "Let us begin our English lesson today.", translation: "চলুন আজ আমাদের ইংরেজি পাঠ শুরু করি।" },
  { english: "behave", bangla: "আচরণ করা", phonetic: "/bɪˈheɪv/", sentence: "Children should behave politely with elders.", translation: "শিশুদের গুরুজনদের সাথে ভদ্রভাবে আচরণ করা উচিত।" },
  { english: "believe", bangla: "বিশ্বাস করা", phonetic: "/bɪˈliːv/", sentence: "Always believe in yourself and work hard.", translation: "সবসময় নিজের উপর বিশ্বাস রাখুন এবং কঠোর পরিশ্রম করুন।" },
  { english: "belong", bangla: "অধীনে থাকা / উপযুক্ত হওয়া", phonetic: "/bɪˈlɒŋ/", sentence: "This pen belongs to my teacher.", translation: "এই কলমটি আমার শিক্ষকের।" },
  { english: "bend", bangla: "বাঁকা করা / নত হওয়া", phonetic: "/bɛnd/", sentence: "Bend your knees while lifting weights.", translation: "ভার তোলার সময় হাঁটু ভাঁজ করুন।" },
  { english: "bind", bangla: "বাঁধা / আবদ্ধ করা", phonetic: "/baɪnd/", sentence: "Love binds all members of the family.", translation: "ভালোবাসা পরিবারের সকল সদস্যকে আবদ্ধ করে।" },
  { english: "bite", bangla: "কামড়ানো", phonetic: "/baɪt/", sentence: "Be careful, the puppy might bite.", translation: "সাবধান থাকুন, কুকুরছানাটি কামড়াতে পারে।" },
  { english: "blame", bangla: "দোষারোপ করা", phonetic: "/bleɪm/", sentence: "Do not blame others for your mistake.", translation: "নিজের ভুলের জন্য অন্যদের দোষারোপ করবেন না।" },
  { english: "bleed", bangla: "রক্তপাত হওয়া", phonetic: "/bliːd/", sentence: "His finger started to bleed after the cut.", translation: "কেটে যাওয়ার পর তার আঙুল থেকে রক্তপাত হতে লাগল।" },
  { english: "bless", bangla: "আশীর্বাদ করা", phonetic: "/blɛs/", sentence: "May the Almighty bless you with good health.", translation: "সর্বশক্তিমান আপনাকে সুস্বাস্থ্য দান করুন।" },
  { english: "blow", bangla: "বাতাস বওয়া / ফুঁ দেওয়া", phonetic: "/bloʊ/", sentence: "The gentle morning breeze blows softly.", translation: "ভোরের মৃদুমন্দ বাতাস ধীরে ধীরে বয়ে যায়।" },
  { english: "boil", bangla: "ফোটানো", phonetic: "/bɔɪl/", sentence: "Always drink boiled water for safety.", translation: "নিরাপত্তার জন্য সর্বদা ফোটানো পানি পান করুন।" },
  { english: "borrow", bangla: "ধার নেওয়া", phonetic: "/ˈbɒroʊ/", sentence: "He borrowed a history book from the library.", translation: "সে লাইব্রেরি থেকে একটি ইতিহাসের বই ধার নিয়েছিল।" },
  { english: "breathe", bangla: "শ্বাস নেওয়া", phonetic: "/briːð/", sentence: "Take a deep breath of fresh air.", translation: "টাটকা বাতাসে গভীর শ্বাস নিন।" },
  { english: "bring", bangla: "আনা", phonetic: "/brɪŋ/", sentence: "Please bring your notebook tomorrow.", translation: "দয়া করে আগামীকাল তোমার খাতা নিয়ে এসো।" },
  { english: "build", bangla: "নির্মাণ করা", phonetic: "/bɪld/", sentence: "Engineers are building a grand bridge.", translation: "প্রকৌশলীরা একটি বিশাল সেতু নির্মাণ করছেন।" },
  { english: "burn", bangla: "পোড়ানো / জ্বলা", phonetic: "/bɜːrn/", sentence: "Dry wood burns quickly.", translation: "শুকনো কাঠ দ্রুত জ্বলে।" },
  { english: "buy", bangla: "কেনা", phonetic: "/baɪ/", sentence: "I want to buy some English storybooks.", translation: "আমি কিছু ইংরেজি গল্পের বই কিনতে চাই।" },
  { english: "call", bangla: "ডাকা / ফোন করা", phonetic: "/kɔːl/", sentence: "Call me whenever you need help.", translation: "যখনই সাহায্যের প্রয়োজন হয় আমাকে ডাকবেন।" },
  { english: "carry", bangla: "বহন করা", phonetic: "/ˈkæri/", sentence: "The porter carried the heavy luggage.", translation: "কুলি ভারী মালপত্র বহন করেছিল।" },
  { english: "catch", bangla: "ধরা", phonetic: "/kætʃ/", sentence: "The fielder caught the cricket ball.", translation: "ফিল্ডার ক্রিকেট বলটি ধরে ফেলেছিল।" },
  { english: "celebrate", bangla: "উদযাপন করা", phonetic: "/ˈsɛlɪbreɪt/", sentence: "We celebrated our victory happily.", translation: "আমরা আনন্দের সাথে আমাদের বিজয় উদযাপন করেছি।" },
  { english: "change", bangla: "পরিবর্তন করা", phonetic: "/tʃeɪndʒ/", sentence: "Technology changes human life continuously.", translation: "প্রযুক্তি মানুষের জীবনকে নিরবচ্ছিন্নভাবে পরিবর্তন করে।" },
  { english: "chase", bangla: "পিছু নেওয়া / তাড়া করা", phonetic: "/tʃeɪs/", sentence: "The cat chased the mouse across the hall.", translation: "বিড়ালটি ঘরের মধ্যে ইঁদুরটিকে তাড়া করেছিল।" },
  { english: "cheat", bangla: "প্রতারণা করা", phonetic: "/tʃiːt/", sentence: "Never cheat in examinations.", translation: "পরীক্ষায় কখনো প্রতারণা (নকল) করবেন না।" },
  { english: "check", bangla: "পরীক্ষা করা / যাচাই করা", phonetic: "/tʃɛk/", sentence: "Check your answers before submitting the script.", translation: "খাতা জমা দেওয়ার আগে তোমার উত্তরগুলো যাচাই করো।" },
  { english: "choose", bangla: "পছন্দ করা / বেছে নেওয়া", phonetic: "/tʃuːz/", sentence: "Choose the correct answer from four options.", translation: "চারটি বিকল্প থেকে সঠিক উত্তরটি বেছে নিন।" },
  { english: "clap", bangla: "হাততালি দেওয়া", phonetic: "/klæp/", sentence: "Audience clapped loudly after the performance.", translation: "পরিবেশনার পর দর্শকরা জোরে হাততালি দিয়েছিল।" },
  { english: "climb", bangla: "আরোহণ করা / ওঠা", phonetic: "/klaɪm/", sentence: "He climbed the tall coconut tree skillfully.", translation: "সে দক্ষতার সাথে উঁচু নারকেল গাছে উঠেছিল।" },
  { english: "collect", bangla: "সংগ্রহ করা", phonetic: "/kəˈlɛkt/", sentence: "She likes to collect rare stamps.", translation: "সে বিরল ডাকটিকিট সংগ্রহ করতে পছন্দ করে।" },
  { english: "combine", bangla: "একত্রিত করা", phonetic: "/kəmˈbaɪn/", sentence: "Combine study with sports for good health.", translation: "সুস্বাস্থ্যের জন্য পড়াশোনার সাথে খেলাধুলা একত্রিত করুন।" },
  { english: "come", bangla: "আসা", phonetic: "/kʌm/", sentence: "Come to school punctually every day.", translation: "প্রতিদিন সময়মতো বিদ্যালয়ে আসুন।" },
  { english: "cook", bangla: "রান্না করা", phonetic: "/kʊk/", sentence: "Mother cooks delicious food for our family.", translation: "মা আমাদের পরিবারের জন্য সুস্বাদু খাবার রান্না করেন।" },
  { english: "cough", bangla: "কাশি দেওয়া", phonetic: "/kɒf/", sentence: "Cover your mouth when you cough.", translation: "কাশি দেওয়ার সময় মুখ ঢেকে রাখুন।" },
  { english: "dance", bangla: "নাচা", phonetic: "/dɑːns/", sentence: "Children danced cheerfully at the cultural program.", translation: "সাংস্কৃতিক অনুষ্ঠানে শিশুরা আনন্দের সাথে নেচেছিল।" },
  { english: "die", bangla: "মারা যাওয়া", phonetic: "/daɪ/", sentence: "Heroes die for their nation but live forever in memory.", translation: "বীররা দেশের জন্য জীবন দেন কিন্তু স্মৃতিতে চিরকাল বেঁচে থাকেন।" },
  { english: "dig", bangla: "খনন করা", phonetic: "/dɪɡ/", sentence: "Farmers dig soil to plant seeds.", translation: "কৃষকরা বীজ রোপণের জন্য মাটি খনন করেন।" },
  { english: "dislike", bangla: "অপছন্দ করা", phonetic: "/dɪsˈlaɪk/", sentence: "She dislikes telling lies.", translation: "সে মিথ্যা বলা অপছন্দ করে।" },
  { english: "do", bangla: "করা", phonetic: "/duː/", sentence: "Do your daily duties with full sincerity.", translation: "পূর্ণ আন্তরিকতার সাথে তোমার দৈনন্দিন দায়িত্ব পালন করো।" },
  { english: "doubt", bangla: "সন্দেহ করা", phonetic: "/daʊt/", sentence: "I do not doubt his honest intentions.", translation: "আমি তার সৎ উদ্দেশ্য নিয়ে সন্দেহ করি না।" },
  { english: "draw", bangla: "আঁকা / টানা", phonetic: "/drɔː/", sentence: "Children love to draw colorful scenery.", translation: "শিশুরা রঙিন প্রাকৃতিক দৃশ্য আঁকতে ভালোবাসে।" },
  { english: "eat", bangla: "খাওয়া", phonetic: "/iːt/", sentence: "Eat fresh fruits and vegetables to stay strong.", translation: "সুস্থ ও সবল থাকতে তাজা ফল ও শাকসবজি খান।" }
];
