export const verbsListFtoZ = [
  // E
  ["eliminate", "দূর করা", "/ɪˈlɪmɪneɪt/", "Education eliminates social ignorance.", "শিক্ষা সামাজিক অজ্ঞতা দূর করে।"],
  ["emphasize", "জোর দেওয়া", "/ˈɛmfəsaɪz/", "Teachers emphasize clear pronunciation.", "শিক্ষকরা স্পষ্ট উচ্চারণের ওপর জোর দেন।"],
  ["employ", "নিয়োগ করা / কাজে লাগানো", "/ɪmˈplɔɪ/", "Use your leisure hours constructively.", "তোমার অবসর সময় গঠনমূলকভাবে কাজে লাগাও।"],
  ["enable", "সক্ষম করা", "/ɪˈneɪbl/", "Grammar rules enable students to write correctly.", "ব্যাকরণের নিয়ম শিক্ষার্থীদের সঠিকভাবে লিখতে সক্ষম করে।"],
  ["encourage", "উৎসাহিত করা", "/ɪnˈkʌrɪdʒ/", "Mentors encourage students to speak fluently.", "শিক্ষকরা শিক্ষার্থীদের সাবলীলভাবে কথা বলতে উৎসাহিত করেন।"],
  ["endorse", "সমর্থন করা", "/ɪnˈdɔːrs/", "The principal endorsed the project proposal.", "অধ্যক্ষ প্রকল্পের প্রস্তাবটি সমর্থন করেছিলেন।"],
  ["endure", "সহ্য করা / টিকে থাকা", "/ɪnˈdjʊər/", "Patience helps people endure difficulties.", "ধৈর্য মানুষকে কঠিন সময় সহ্য করতে সাহায্য করে।"],
  ["engage", "যুক্ত হওয়া", "/ɪnˈɡeɪdʒ/", "Engage in meaningful English discussions.", "অর্থবহ ইংরেজি আলোচনায় যুক্ত হোন।"],
  ["enhance", "উন্নত করা / বৃদ্ধি করা", "/ɪnˈhɑːns/", "Reading widely enhances your vocabulary.", "বেশি বেশি পড়া তোমার শব্দভাণ্ডার বৃদ্ধি করে।"],
  ["enjoy", "উপভোগ করা", "/ɪnˈdʒɔɪ/", "Students enjoy learning with interactive quizzes.", "শিক্ষার্থীরা মিথস্ক্রিয়ামূলক কুইজের মাধ্যমে শেখা উপভোগ করে।"],
  ["enrich", "সমৃদ্ধ করা", "/ɪnˈrɪtʃ/", "Good books enrich the human mind.", "ভালো বই মানুষের মনকে সমৃদ্ধ করে।"],
  ["ensure", "নিশ্চিত করা", "/ɪnˈʃʊər/", "Practice daily to ensure fluent speaking.", "সাবলীল কথন নিশ্চিত করতে প্রতিদিন অনুশীলন করুন।"],
  ["enter", "প্রবেশ করা", "/ˈɛntər/", "Knock gently before you enter the hall.", "হলঘরে প্রবেশের আগে আলতো করে দরজায় টোকা দিন।"],
  ["entertain", "বিনোদন দেওয়া", "/ˌɛntərˈteɪn/", "Folk stories entertain children in villages.", "লোককাহিনি গ্রামের শিশুদের বিনোদন দেয়।"],
  ["equip", "সজ্জিত করা", "/ɪˈkwɪp/", "Schools equip youth with modern knowledge.", "বিদ্যালয়গুলো তরুণদের আধুনিক জ্ঞানে সজ্জিত করে।"],
  ["erase", "মুছে ফেলা", "/ɪˈreɪs/", "You can erase pencil mistakes easily.", "তুমি সহজেই পেন্সিলের ভুলগুলো মুছে ফেলতে পারো।"],
  ["escape", "পলায়ন করা / রেহাই পাওয়া", "/ɪˈskeɪp/", "The rabbit escaped into the green bushes.", "খরগোশটি সবুজ ঝোপের মধ্যে পালিয়ে গেল।"],
  ["establish", "প্রতিষ্ঠা করা", "/ɪˈstæblɪʃ/", "The community established a charitable dispensary.", "সমাজ একটি দাতব্য চিকিৎসালয় প্রতিষ্ঠা করেছে।"],
  ["estimate", "অনুমান করা", "/ˈɛstɪmeɪt/", "Engineers estimate the construction timeline.", "প্রকৌশলীরা নির্মাণের সময়সীমা অনুমান করেন।"],
  ["evaluate", "মূল্যায়ন করা", "/ɪˈvæljueɪt/", "Quizzes evaluate your language progress.", "কুইজ তোমার ভাষা শিক্ষার অগ্রগতি মূল্যায়ন করে।"],
  ["evolve", "বিবর্তিত হওয়া / বিকাশ লাভ করা", "/ɪˈvɒlv/", "Languages evolve with cultural exchanges.", "সাংস্কৃতিক বিনিময়ের মাধ্যমে ভাষা বিকশিত হয়।"],
  ["examine", "পরীক্ষা করা", "/ɪɡˈzæmɪn/", "Inspectors examine school sanitation.", "পরিদর্শকরা বিদ্যালয়ের স্যানিটেশন পরীক্ষা করেন।"],
  ["excel", "উৎকর্ষ সাধন করা", "/ɪkˈsɛl/", "Dedicated learners excel in exams.", "নিষ্ঠাবান শিক্ষার্থীরা পরীক্ষায় চমৎকার ফলাফল অর্জন করে।"],
  ["exchange", "বিনিময় করা", "/ɪksˈtʃeɪndʒ/", "Pen pals exchange friendly letters.", "কলমের বন্ধুরা বন্ধুত্বপূর্ণ চিঠি বিনিময় করে।"],
  ["excite", "উত্তেজিত / রোমাঞ্চিত করা", "/ɪkˈsaɪt/", "Science experiments excite young minds.", "বিজ্ঞান পরীক্ষা তরুণ মনকে রোমাঞ্চিত করে।"],
  ["exclude", "বাদ দেওয়া", "/ɪkˈskluːd/", "Do not exclude any willing learner.", "কোনো আগ্রহী শিক্ষার্থীকে বাদ দেবেন না।"],
  ["execute", "সম্পাদন করা", "/ˈɛksɪkjuːt/", "Athletes execute their strategy perfectly.", "ক্রীড়াবিদরা নিখুঁতভাবে তাদের কৌশল বাস্তবায়ন করেন।"],
  ["exercise", "ব্যায়াম করা", "/ˈɛksərsaɪz/", "Exercise every dawn for physical stamina.", "শারীরিক সক্ষমতার জন্য প্রতিদিন ভোরে ব্যায়াম করুন।"],
  ["exert", "প্রয়োগ করা", "/ɪɡˈzɜːrt/", "Exert your utmost effort to succeed.", "সফল হতে তোমার সর্বোচ্চ প্রচেষ্টা প্রয়োগ করো।"],
  ["exhibit", "প্রদর্শন করা", "/ɪɡˈzɪbɪt/", "Museums exhibit archaeological discoveries.", "জাদুঘর প্রত্নতাত্ত্বিক নিদর্শন প্রদর্শন করে।"],
  ["expand", "প্রসারিত করা", "/ɪkˈspænd/", "Reading expands intellectual horizons.", "অধ্যয়ন বুদ্ধিবৃত্তিক দিগন্তকে প্রসারিত করে।"],
  ["expect", "প্রত্যাশা করা", "/ɪkˈspɛkt/", "Teachers expect disciplined dedication.", "শিক্ষকরা সুশৃঙ্খল নিষ্ঠা প্রত্যাশা করেন।"],
  ["experience", "অভিজ্ঞতা লাভ করা", "/ɪkˈspɪəriəns/", "Travelers experience new natural landscapes.", "ভ্রমণকারীরা নতুন প্রাকৃতিক ভূদৃশ্যের অভিজ্ঞতা লাভ করেন।"],
  ["experiment", "পরীক্ষা-নিরীক্ষা করা", "/ɪkˈspɛrɪmənt/", "Researchers experiment in chemistry laboratories.", "রসায়ন গবেষণাগারে গবেষকরা পরীক্ষা-নিরীক্ষা করেন।"],
  ["explain", "ব্যাখ্যা করা", "/ɪkˈspleɪn/", "Please explain the meaning of this idiom.", "দয়া করে এই বাগধারাটির অর্থ ব্যাখ্যা করুন।"],
  ["explore", "অন্বেষণ করা", "/ɪkˈsplɔːr/", "Scientists explore the mysteries of deep oceans.", "বিজ্ঞানীরা গভীর সমুদ্রের রহস্য অন্বেষণ করেন।"],
  ["express", "প্রকাশ করা", "/ɪkˈsprɛs/", "Express your thoughts respectfully.", "শ্রদ্ধাপূর্ণ ভঙ্গিতে তোমার চিন্তা প্রকাশ করো।"],
  ["extend", "প্রসারিত করা", "/ɪkˈstɛnd/", "The government extended the library hours.", "সরকার পাঠাগারের সময়সীমা বৃদ্ধি করেছে।"],

  // F
  ["fail", "ব্যর্থ হওয়া", "/feɪl/", "Failure teaches invaluable life lessons.", "ব্যর্থতা অমূল্য জীবনের শিক্ষা প্রদান করে।"],
  ["faint", "অজ্ঞান হওয়া", "/feɪnt/", "The tired runner fainted in extreme heat.", "ক্লান্ত দৌড়বিদ তীব্র গরমে অজ্ঞান হয়ে পড়েছিলেন।"],
  ["fall", "পতন ঘটা / পড়া", "/fɔːl/", "Ripe guavas fall from the orchard trees.", "বাগানের গাছ থেকে পাকা পেয়ারা পড়ে।"],
  ["fasten", "আবদ্ধ করা / বাঁধা", "/ˈfɑːsn/", "Fasten your seatbelt before the vehicle moves.", "যানবাহন চলার আগে তোমার সিটবেল্ট বাঁধো।"],
  ["fear", "ভয় পাওয়া", "/fɪər/", "Do not fear mistakes; learn from them.", "ভুল করতে ভয় পাবেন না; ভুল থেকে শিখুন।"],
  ["feed", "খাওয়ানো", "/fiːd/", "Villagers feed grain to morning birds.", "গ্রামবাসীরা সকালের পাখিদের শস্যদানা খাওয়ান।"],
  ["feel", "অনুভব করা", "/fiːl/", "We feel proud of our glorious mother tongue.", "আমরা আমাদের গৌরবময় মাতৃভাষার জন্য গর্ব অনুভব করি।"],
  ["fetch", "গিয়ে নিয়ে আসা", "/fɛtʃ/", "The boy went to fetch drinking water.", "ছেলেটি খাবার পানি নিয়ে আসতে গিয়েছিল।"],
  ["fight", "যুদ্ধ করা / লড়াই করা", "/faɪt/", "Freedom fighters fought valiantly for independence.", "মুক্তিযোদ্ধারা স্বাধীনতার জন্য সাহসিকতার সাথে লড়াই করেছিলেন।"],
  ["fill", "পূর্ণ করা", "/fɪl/", "Fill the jug with refreshing lemon water.", "জগটি সতেজ লেবুর পানি দিয়ে পূর্ণ করুন।"],
  ["filter", "পরিশ্রুত করা", "/ˈfɪltər/", "Modern purifiers filter water for purity.", "আধুনিক ফিল্টার বিশুদ্ধতার জন্য পানি পরিশোধন করে।"],
  ["find", "খুঁজে পাওয়া", "/faɪnd/", "Look closely to find the hidden lesson.", "লুকানো শিক্ষাটি খুঁজে পেতে নিবিড়ভাবে লক্ষ্য করো।"],
  ["finish", "শেষ করা", "/ˈfɪnɪʃ/", "Finish your assignment before twilight.", "সন্ধ্যার আগেই তোমার দায়িত্ব শেষ করো।"],
  ["fire", "আগুন লাগানো / গুলি করা", "/ˈfaɪər/", "The soldier fired a signal flare.", "সৈনিক একটি সতর্কতামূলক সিগন্যাল পাঠিয়েছিলেন।"],
  ["fit", "মানানসই হওয়া", "/fɪt/", "These cotton shirts fit comfortably in summer.", "এই সুতি শার্টগুলো গ্রীষ্মে আরামদায়কভাবে মানিয়ে যায়।"],
  ["fix", "মেরামত করা / ঠিক করা", "/fɪks/", "Technicians fix electric circuits safely.", "কারিগরি কর্মীরা নিরাপদে বৈদ্যুতিক বর্তনী ঠিক করেন।"],
  ["flash", "চকচক করা", "/flæʃ/", "Lightning flashed brightly across the sky.", "আকাশজুড়ে উজ্জ্বলভাবে বিদ্যুৎ চমকে উঠল।"],
  ["flee", "পালিয়ে যাওয়া", "/fliː/", "The thief fled when alarms rang.", "অ্যালার্ম বাজতেই চোর পালিয়ে গেল।"],
  ["fling", "ছুঁড়ে ফেলা", "/flɪŋ/", "Children flung flowers in the air.", "শিশুরা বাতাসে ফুল ছুঁড়ে দিয়েছিল।"],
  ["float", "ভেসে থাকা", "/floʊt/", "Dry wooden boats float on the river.", "শুকনো কাঠের নৌকা নদীর জলে ভেসে থাকে।"],
  ["flow", "প্রবাহিত হওয়া", "/floʊ/", "Fresh water flows down from the green hills.", "সবুজ পাহাড় থেকে সতেজ পানি প্রবাহিত হয়।"],
  ["fly", "ওড়া", "/flaɪ/", "White migratory birds fly across wetlands.", "সাদা পরিযায়ী পাখিরা জলাভূমির ওপর দিয়ে ওড়ে।"],
  ["focus", "দৃষ্টি নিবদ্ধ করা", "/ˈfoʊkəs/", "Focus your attention during class.", "ক্লাসের সময় তোমার মনোযোগ নিবদ্ধ রাখো।"],
  ["fold", "ভাঁজ করা", "/foʊld/", "Fold the clean linen neatly.", "পরিচ্ছন্ন চাদর সুন্দর করে ভাঁজ করো।"],
  ["follow", "অনুসরণ করা", "/ˈfɒloʊ/", "Follow the traffic rules for safety.", "নিরাপত্তার জন্য ট্রাফিক নিয়ম মেনে চলুন।"],
  ["forbid", "নিষেধ করা", "/fərˈbɪd/", "School rules forbid dishonest conduct.", "বিদ্যালয়ের নিয়ম অসদুপায় অবলম্বন নিষেধ করে।"],
  ["forecast", "পূর্বাভাস দেওয়া", "/ˈfɔːrkæst/", "Meteorologists forecast a sunny day.", "আবহাওয়াবিদরা একটি রৌদ্রোজ্জ্বল দিনের পূর্বাভাস দিয়েছেন।"],
  ["foresee", "আগে থেকেই দেখতে পাওয়া", "/fɔːrˈsiː/", "A wise planner foresees future challenges.", "একজন বিচক্ষণ পরিকল্পনাকারী ভবিষ্যতের চ্যালেঞ্জ আগে থেকেই দেখতে পান।"],
  ["forget", "ভুলে যাওয়া", "/fərˈɡɛt/", "Never forget the sacrifices of freedom fighters.", "মুক্তিযোদ্ধাদের আত্মত্যাগ কখনোই ভুলে যাবেন না।"],
  ["forgive", "ক্ষমা করা", "/fərˈɡɪv/", "To forgive mistakes is a divine virtue.", "ভুল ক্ষমা করা একটি মহৎ স্বর্গীয় গুণ।"],
  ["form", "গঠন করা", "/fɔːrm/", "Students formed an English conversation club.", "শিক্ষার্থীরা একটি ইংরেজি কথন ক্লাব গঠন করেছিল।"],
  ["formulate", "প্রণয়ন করা", "/ˈfɔːrmjuleɪt/", "Teachers formulated a balanced curriculum.", "শিক্ষকরা একটি সুষম পাঠ্যক্রম প্রণয়ন করেছিলেন।"],
  ["foster", "লালন করা / উৎসাহিত করা", "/ˈfɒstər/", "Sports foster team spirit among students.", "খেলাধুলা শিক্ষার্থীদের মাঝে দলীয় মনোভাব উৎসাহিত করে।"],
  ["freeze", "জমে বরফ হওয়া", "/friːz/", "Water freezes at zero degrees Celsius.", "শূন্য ডিগ্রি সেলসিয়াসে পানি জমে বরফ হয়।"],
  ["frighten", "ভয় দেখানো", "/ˈfraɪtn/", "Loud explosions frighten innocent birds.", "বিকট বিস্ফোরণ নিরীহ পাখিদের ভয় দেখায়।"],
  ["fulfill", "বাস্তবায়ন করা / পূরণ করা", "/fʊlˈfɪl/", "Hard work fulfills lofty dreams.", "কঠোর পরিশ্রম উচ্চাশা ও স্বপ্ন পূরণ করে।"],

  // G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, Y, Z
  ["gamble", "ঝুঁকি নেওয়া / জুয়া খেলা", "/ˈɡæmbl/", "Never gamble away your valuable time.", "তোমার মূল্যবান সময় কখনোই ঝুঁকির মুখে ফেলে নষ্ট করো না।"],
  ["generate", "উৎপাদন করা", "/ˈdʒɛnəreɪt/", "Solar plants generate clean energy.", "সৌর কেন্দ্রগুলো পরিচ্ছন্ন বিদ্যুৎ উৎপাদন করে।"],
  ["glide", "মসৃণভাবে ভেসে চলা", "/ɡlaɪd/", "The eagle glides high above the clouds.", "ঈগল মেঘের ওপর দিয়ে মসৃণভাবে ভেসে চলে।"],
  ["glorify", "মহিমান্বিত করা", "/ˈɡlɔːrɪfaɪ/", "Patriots glorify their motherland.", "দেশপ্রেমিকরা তাদের মাতৃভূমিকে মহিমান্বিত করেন।"],
  ["glow", "আলো বিকিরণ করা", "/ɡloʊ/", "Fireflies glow in the rural village nights.", "গ্রামের রাতে জোনাকি পোকারা আলো ছড়ায়।"],
  ["govern", "শাসন করা", "/ˈɡʌvərn/", "Elected leaders govern the nation with justice.", "নির্বাচিত নেতারা ন্যায়ের সাথে দেশ শাসন করেন।"],
  ["graduate", "স্নাতক সম্পন্ন করা", "/ˈɡrædʒueɪt/", "She graduated from university with distinction.", "তিনি কৃতিত্বের সাথে বিশ্ববিদ্যালয় থেকে স্নাতক সম্পন্ন করেছেন।"],
  ["grant", "মঞ্জুর করা", "/ɡrɑːnt/", "The principal granted his fee concession.", "অধ্যক্ষ তার বেতন মওকুফের আবেদন মঞ্জুর করেছিলেন।"],
  ["greet", "অভিবাদন জানানো", "/ɡriːt/", "Always greet your teachers with respect.", "সর্বদা শ্রদ্ধার সাথে শিক্ষকদের অভিবাদন জানান।"],
  ["grieve", "শোক প্রকাশ করা", "/ɡriːv/", "The country grieved the national loss.", "জাতি জাতীয় শোক প্রকাশ করেছিল।"],
  ["groan", "কাতরানো", "/ɡroʊn/", "The sick patient groaned softly.", "অসুস্থ রোগী মৃদু কাতরাচ্ছিল।"],
  ["guard", "পাহারা দেওয়া", "/ɡɑːrd/", "Sentries guard the national gate.", "প্রহরীরা জাতীয় ফটক পাহারা দেন।"],
  ["guide", "পথ প্রদর্শন করা", "/ɡaɪd/", "Mentors guide students toward success.", "শিক্ষকরা শিক্ষার্থীদের সাফল্যের পথে পরিচালিত করেন।"],
  ["halt", "থামানো", "/hɔːlt/", "The express train halted at the bridge.", "এক্সপ্রেস ট্রেনটি সেতুর কাছে থেমেছিল।"],
  ["hammer", "হাতুড়ি মারা", "/ˈhæmər/", "Carpenters hammer nails into the plank.", "কাঠমিস্ত্রিরা তক্তার ওপর পেরেক মারেন।"],
  ["handle", "সামলানো", "/ˈhændl/", "Handle delicate glassware with care.", "নাজুক কাচের জিনিস যত্নের সাথে সামলান।"],
  ["happen", "ঘটা", "/ˈhæpən/", "Miracles happen when people cooperate.", "মানুষ যখন সহযোগিতা করে তখন অলৌকিক সাফল্য ঘটে।"],
  ["harass", "হয়রানি করা", "/həˈræs/", "The law penalizes anyone who harasses citizens.", "নাগরিকদের হয়রানি করলে আইন শাস্তি দেয়।"],
  ["harvest", "ফসল তোলা", "/ˈhɑːrvɪst/", "Farmers harvest golden grain in winter.", "শীতকালে কৃষকরা সোনালি শস্য ঘরে তোলেন।"],
  ["hasten", "ত্বরান্বিত করা", "/ˈheɪsn/", "Hasten your steps to catch the morning train.", "সকালের ট্রেন ধরতে তোমার পদক্ষেপ দ্রুত করো।"],
  ["hate", "ঘৃণা করা", "/heɪt/", "Hate falsehood and uphold truth.", "মিথ্যাকে ঘৃণা করুন এবং সত্যকে তুলে ধরুন।"],
  ["heal", "নিরাময় হওয়া", "/hiːl/", "Proper care helps wounds heal rapidly.", "সঠিক যত্ন ক্ষতকে দ্রুত নিরাময় হতে সাহায্য করে।"],
  ["hesitate", "দ্বিধা করা", "/ˈhɛzɪteɪt/", "Do not hesitate to seek help.", "সাহায্য চাইতে কোনো দ্বিধা করবেন না।"],
  ["hinder", "বাধা সৃষ্টি করা", "/ˈhɪndər/", "Illiteracy hinders the progress of a nation.", "নিরক্ষরতা জাতির অগ্রগতিতে বাধা সৃষ্টি করে।"],
  ["hire", "ভাড়া করা", "/ˈhaɪər/", "They hired a tourist coach for the excursion.", "তারা শিক্ষাসফরের জন্য একটি পর্যটন বাস ভাড়া করেছিল।"],
  ["hit", "আঘাত করা", "/hɪt/", "The batsman hit the ball for a six.", "ব্যাটসম্যান বলটিতে ছক্কা মেরেছিলেন।"],
  ["hold", "ধরে রাখা", "/hoʊld/", "Hold the hand of little children in crowds.", "ভিড়ের মধ্যে ছোট শিশুদের হাত ধরে রাখুন।"],
  ["honor", "সম্মান করা", "/ˈɒnər/", "We honor the martyrs of our language movement.", "আমরা আমাদের ভাষা আন্দোলনের শহীদদের সম্মান করি।"],
  ["hug", "আলিঙ্গন করা", "/hʌɡ/", "Mother hugged her child warmly.", "মা তার সন্তানকে উষ্ণ আলিঙ্গনে জড়িয়ে নিলেন।"],
  ["hunt", "শিকার করা", "/hʌnt/", "Preserve wild animals and do not hunt them.", "বন্যপ্রাণী সংরক্ষণ করুন এবং তাদের শিকার করবেন না।"],
  ["hurry", "তাড়াহুড়ো করা", "/ˈhʌri/", "Hurry up so that we arrive before the bell.", "তাড়াতাড়ি করো যাতে আমরা ঘণ্টা পড়ার আগেই পৌঁছাতে পারি।"],
  ["identify", "শনাক্ত করা", "/aɪˈdɛntɪfaɪ/", "Identify the grammatical function of each word.", "প্রতিটি শব্দের ব্যাকরণগত ভূমিকা শনাক্ত করো।"],
  ["ignore", "উপেক্ষা করা", "/ɪɡˈnɔːr/", "Wise people ignore meaningless gossip.", "জ্ঞানীরা অর্থহীন পরচর্চা উপেক্ষা করেন।"],
  ["illuminate", "আলোকিত করা", "/ɪˈluːmɪneɪt/", "Lamps illuminated the study room.", "বাতি পড়ার ঘরটি আলোকিত করেছিল।"],
  ["illustrate", "চিত্রের মাধ্যমে বোঝানো", "/ˈɪləstreɪt/", "Diagrams illustrate science theories clearly.", "চিত্রসমূহ বিজ্ঞানের তত্ত্বগুলোকে পরিষ্কারভাবে বোঝায়।"],
  ["imagine", "কল্পনা করা", "/ɪˈmædʒɪn/", "Imagine a world without poverty and ignorance.", "দারিদ্র্য ও অজ্ঞতাহীন এক পৃথিবীর কল্পনা করো।"],
  ["imitate", "অনুকরণ করা", "/ˈɪmɪteɪt/", "Learners imitate standard English pronunciation.", "শিক্ষার্থীরা প্রমিত ইংরেজি উচ্চারণ অনুকরণ করে।"],
  ["implement", "বাস্তবায়ন করা", "/ˈɪmplɪmɛnt/", "The school implemented a clean campus policy.", "বিদ্যালয় একটি পরিচ্ছন্ন প্রাঙ্গণ নীতি বাস্তবায়ন করেছে।"],
  ["imply", "ইঙ্গিত করা", "/ɪmˈplaɪ/", "His statement implies constructive intent.", "তার বক্তব্য গঠনমূলক উদ্দেশ্যের ইঙ্গিত দেয়।"],
  ["impose", "আরোপ করা", "/ɪmˈpoʊz/", "Authorities impose speed limits on highways.", "কর্তৃপক্ষ মহাসড়কে গতির সীমা আরোপ করে।"],
  ["impress", "মুগ্ধ করা", "/ɪmˈprɛs/", "Her clear speech impressed the examiners.", "তার স্পষ্ট বক্তব্য পরীক্ষকদের মুগ্ধ করেছিল।"],
  ["indicate", "নির্দেশ করা", "/ˈɪndɪkeɪt/", "Clouds indicate that fresh rain is coming.", "মেঘ নির্দেশ করে যে মিষ্টি বৃষ্টি আসছে।"],
  ["inform", "অবহিত করা", "/ɪnˈfɔːrm/", "Please inform the office about your address change.", "ঠিকানা পরিবর্তনের বিষয়টি অনুগ্রহ করে অফিসে জানান।"],
  ["inherit", "উত্তরাধিকার সূত্রে পাওয়া", "/ɪnˈhɛrɪt/", "Children inherit cultural traditions from parents.", "সন্তানেরা পিতা-মাতার কাছ থেকে সাংস্কৃতিক ঐতিহ্য উত্তরাধিকার সূত্রে পায়।"],
  ["initiate", "উদ্বোধন করা / সূচনা করা", "/ɪˈnɪʃieɪt/", "The headmaster initiated the literacy drive.", "প্রধান শিক্ষক সাক্ষরতা অভিযানের সূচনা করেছিলেন।"],
  ["injure", "আহত করা", "/ˈɪndʒər/", "Avoid reckless driving that might injure others.", "বেপরোয়া গাড়ি চালানো পরিহার করুন যা অন্যদের আহত করতে পারে।"],
  ["insert", "সন্নিবেশ করা", "/ɪnˈsɜːrt/", "Insert the memory card into the slot.", "স্লটে মেমরি কার্ডটি সন্নিবেশ করুন।"],
  ["insist", "জোর দেওয়া", "/ɪnˈsɪst/", "Teachers insist on legible handwriting.", "শিক্ষকরা স্পষ্ট হস্তাক্ষরের ওপর জোর দেন।"],
  ["inspect", "পরিদর্শন করা", "/ɪnˈspɛkt/", "Officials inspect the irrigation canals.", "কর্মকর্তারা সেচ খালগুলো পরিদর্শন করেন।"],
  ["inspire", "অনুপ্রাণিত করা", "/ɪnˈspaɪər/", "Great biographies inspire noble ambitions.", "মহান জীবনীগুলো মহৎ উচ্চাকাঙ্ক্ষাকে অনুপ্রাণিত করে।"],
  ["install", "স্থাপন করা", "/ɪnˈstɔːl/", "Workers installed safe drinking water pumps.", "শ্রমিকরা নিরাপদ খাবার পানির পাম্প স্থাপন করেছেন।"],
  ["instruct", "নির্দেশনা দেওয়া", "/ɪnˈstrʌkt/", "Mentors instruct students with patience.", "শিক্ষকরা ধৈর্যের সাথে শিক্ষার্থীদের নির্দেশনা দেন।"],
  ["insult", "অপমান করা", "/ɪnˈsʌlt/", "Never insult or belittle anyone.", "কাউকে কখনো অপমান বা ছোট করবেন না।"],
  ["intend", "মনস্থ করা", "/ɪnˈtɛnd/", "We intend to organize an English quiz.", "আমরা একটি ইংরেজি কুইজ আয়োজনের মনস্থ করেছি।"],
  ["intensify", "তীব্র করা", "/ɪnˈtɛnsɪfaɪ/", "Rescue teams intensified their relief operations.", "উদ্ধারকারী দল তাদের ত্রাণ কার্যক্রম জোরদার করেছে।"],
  ["interact", "মতবিনিময় করা", "/ˌɪntərˈækt/", "Students interact during collaborative study.", "যৌথ অধ্যয়নের সময় শিক্ষার্থীরা পারস্পরিক মতবিনিময় করে।"],
  ["interrupt", "বাধা দেওয়া", "/ˌɪntəˈrʌpt/", "Do not interrupt while someone is speaking.", "কেউ কথা বলার সময় বাধা দেবেন না।"],
  ["introduce", "পরিচয় করিয়ে দেওয়া", "/ˌɪntrəˈdjuːs/", "Allow me to introduce our guest speaker.", "আমাদের অতিথি বক্তার সাথে আপনাদের পরিচয় করিয়ে দিতে দিন।"],
  ["invent", "উদ্ভাবন করা", "/ɪnˈvɛnt/", "Innovators invent green technologies.", "উদ্ভাবকরা পরিবেশবান্ধব প্রযুক্তি উদ্ভাবন করেন।"],
  ["invest", "বিনিয়োগ করা", "/ɪnˈvɛst/", "Invest your time in acquiring wisdom.", "জ্ঞান অর্জনে তোমার সময় বিনিয়োগ করো।"],
  ["invite", "আমন্ত্রণ জানানো", "/ɪnˈvaɪt/", "We invited the poet to our cultural festival.", "আমরা আমাদের সাংস্কৃতিক উৎসবে কবিকে আমন্ত্রণ জানিয়েছিলাম।"],
  ["irrigate", "সেচ দেওয়া", "/ˈɪrɪɡeɪt/", "Farmers irrigate dry fields with canal water.", "কৃষকরা খালের পানি দিয়ে শুকনো মাঠে সেচ দেন।"],
  ["isolate", "বিচ্ছিন্ন রাখা", "/ˈaɪsəleɪt/", "Isolate infectious patients for quick recovery.", "দ্রুত আরোগ্যের জন্য সংক্রামক রোগীদের আলাদা রাখুন।"],
  ["jog", "ধীরে দৌড়ানো", "/dʒɒɡ/", "Elderly citizens jog in the morning park.", "বয়স্ক নাগরিকরা সকালে পার্কে জগিং করেন।"],
  ["judge", "বিচার করা", "/dʒʌdʒ/", "Courts judge disputes with impartiality.", "আদালত নিরপেক্ষতার সাথে বিরোধ বিচার করে।"],
  ["juggle", "একত্রে বহু কাজ সামলানো", "/ˈdʒʌɡl/", "She juggles studies and household chores well.", "সে পড়াশোনা ও ঘরের কাজ সুন্দরভাবে সামলায়।"],
  ["jump", "লাফ দেওয়া", "/dʒʌmp/", "Athletes jump across the hurdles gracefully.", "ক্রীড়াবিদরা বাধার ওপর দিয়ে সুন্দরভাবে লাফিয়ে ওঠেন।"],
  ["justify", "ন্যায্যতা প্রতিপাদন করা", "/ˈdʒʌstɪfaɪ/", "Good intentions cannot justify dishonest means.", "সৎ উদ্দেশ্য অসৎ উপায়ের ন্যায্যতা প্রতিপাদন করতে পারে না।"],
  ["kneel", "হাঁটু গেড়ে বসা", "/niːl/", "The gardener knelt to weed the flower bed.", "মালী ফুলের বাগান পরিষ্কার করতে হাঁটু গেড়ে বসেছিলেন।"],
  ["knit", "বোনা", "/nɪt/", "Grandmother knits warm woolen mufflers.", "দাদি উলের গরম মাফলার বোনেন।"],
  ["knock", "টোকা দেওয়া", "/nɒk/", "Always knock gently before opening a door.", "দরজা খোলার আগে সর্বদা আলতো টোকা দিন।"],
  ["launch", "উদ্বোধন করা", "/lɔːntʃ/", "The school launched an environmental club.", "বিদ্যালয় একটি পরিবেশ ক্লাব উদ্বোধন করেছে।"],
  ["lead", "নেতৃত্ব দেওয়া", "/liːd/", "True statesmen lead by moral example.", "প্রকৃত রাষ্ট্রনায়করা নৈতিক দৃষ্টান্তের মাধ্যমে নেতৃত্ব দেন।"],
  ["leak", "চুইয়ে পড়া", "/liːk/", "Fix the faucet before fresh water leaks away.", "বিশুদ্ধ পানি চুইয়ে অপচয় হওয়ার আগেই কলটি মেরামত করুন।"],
  ["lean", "হেলান দেওয়া", "/liːn/", "Do not lean over the deck railing.", "লঞ্চের রেলিংয়ে অতিরিক্ত ঝুঁকে হেলান দেবেন না।"],
  ["leap", "লাফানো", "/liːp/", "The deer leaped across the forest creek.", "হরিণটি বনের খালের ওপর দিয়ে লাফিয়ে গেল।"],
  ["lecture", "বক্তৃতা দেওয়া", "/ˈlɛktʃər/", "The professor lectured on English phonetics.", "অধ্যাপক ইংরেজি ধ্বনিতত্ত্বের ওপর বক্তৃতা দিয়েছিলেন।"],
  ["lend", "ধার দেওয়া", "/lɛnd/", "A true friend lends a helping hand.", "প্রকৃত বন্ধু সহযোগিতার হাত বাড়িয়ে দেয়।"],
  ["lessen", "হ্রাস করা", "/ˈlɛsn/", "Rest lessens exhaustion after hard study.", "কঠোর পড়াশোনার পর বিশ্রাম ক্লান্তি হ্রাস করে।"],
  ["liberate", "মুক্ত করা", "/ˈlɪbəreɪt/", "Freedom fighters liberated Bangladesh in 1971.", "১৯৭১ সালে মুক্তিযোদ্ধারা বাংলাদেশকে মুক্ত করেছিলেন।"],
  ["lift", "উত্তোলন করা", "/lɪft/", "He lifted the heavy parcel with ease.", "সে অনায়াসেই ভারী পার্সেলটি তুলেছিল।"],
  ["lighten", "হালকা করা", "/ˈlaɪtn/", "Kind words lighten the sorrow of troubled hearts.", "সদয় কথা ব্যথিত হৃদয়ের দুঃখ হালকা করে।"],
  ["limit", "সীমিত করা", "/ˈlɪmɪt/", "Limit your sugar consumption for better health.", "সুস্বাস্থ্যের জন্য চিনি খাওয়ার পরিমাণ সীমিত করুন।"],
  ["link", "সংযুক্ত করা", "/lɪŋk/", "Highways link every district to the capital.", "মহাসড়ক প্রতিটি জেলাকে রাজধানীর সাথে সংযুক্ত করে।"],
  ["listen", "মনোযোগ দিয়ে শোনা", "/ˈlɪsn/", "Listen attentively to the teacher's lesson.", "শিক্ষকের পাঠ মনোযোগ সহকারে শুনুন।"],
  ["locate", "অবস্থান নির্ণয় করা", "/loʊˈkeɪt/", "Use the map to locate historical landmarks.", "ঐতিহাসিক নিদর্শনগুলোর অবস্থান নির্ণয়ে মানচিত্র ব্যবহার করুন।"],
  ["lock", "তালা দেওয়া", "/lɒk/", "Lock the laboratory doors after practical class.", "ব্যবহারিক ক্লাসের পর গবেষণাগারের দরজায় তালা দিন।"],
  ["loosen", "আলগা করা", "/ˈluːsn/", "Loosen the tight shoelaces before resting.", "বিশ্রামের আগে শক্ত জুতার ফিতা আলগা করুন।"],
  ["magnify", "বড় করে দেখানো", "/ˈmæɡnɪfaɪ/", "Magnifying lenses reveal microscopic details.", "বিবর্ধক কাচ আণুবীক্ষণিক বিবরণ প্রকাশ করে।"],
  ["maintain", "রক্ষণাবেক্ষণ করা", "/meɪnˈteɪn/", "Maintain discipline in the school corridors.", "বিদ্যালয়ের বারান্দায় শৃঙ্খলা বজায় রাখুন।"],
  ["manage", "ব্যবস্থাপনা করা", "/ˈmænɪdʒ/", "Manage your study timetable efficiently.", "তোমার পড়ার সময়সূচি দক্ষতার সাথে ব্যবস্থাপনা করো।"],
  ["manufacture", "উৎপাদন করা", "/ˌmænjuˈfæktʃər/", "Local mills manufacture fine jute goods.", "স্থানীয় কারখানাগুলো চমৎকার পাটের পণ্য উৎপাদন করে।"],
  ["march", "কুচকাওয়াজ করা", "/mɑːrtʃ/", "Scouts marched smartly during the parade.", "প্যারেডের সময় স্কাউটরা স্মার্টভাবে কুচকাওয়াজ করেছিল।"],
  ["mark", "চিহ্নিত করা", "/mɑːrk/", "Mark key vocabulary words in your notebook.", "তোমার খাতায় মূল শব্দগুলো চিহ্নিত করো।"],
  ["marry", "বিবাহ করা", "/ˈmæri/", "The couple married with parental blessings.", "দম্পতি পিতা-মাতার আশীর্বাদে বিবাহবন্ধনে আবদ্ধ হয়েছিল।"],
  ["master", "আয়ত্ত করা", "/ˈmæstər/", "Daily practice helps you master English.", "প্রতিদিনের অনুশীলন তোমাকে ইংরেজি আয়ত্ত করতে সাহায্য করে।"],
  ["match", "মেলানো", "/mætʃ/", "Match each adjective with its opposite.", "প্রতিটি বিশেষণকে তার বিপরীত শব্দের সাথে মেলাও।"],
  ["mature", "পরিপক্ব হওয়া", "/məˈtʃʊər/", "Students mature through diverse experiences.", "নানা অভিজ্ঞতার মাধ্যমে শিক্ষার্থীরা পরিপক্ব হয়।"],
  ["measure", "পরিমাপ করা", "/ˈmɛʒər/", "Measure the length with a metric ruler.", "একটি মেট্রিক স্কেল দিয়ে দৈর্ঘ্য পরিমাপ করুন।"],
  ["meditate", "ধ্যান করা", "/ˈmɛdɪteɪt/", "Meditate quietly to gain mental peace.", "মানসিক শান্তি লাভের জন্য শান্তভাবে ধ্যান করুন।"],
  ["meet", "সাক্ষাৎ করা", "/miːt/", "Teachers meet parents to share progress.", "অগ্রগতি জানাতে শিক্ষকরা অভিভাবকদের সাথে দেখা করেন।"],
  ["melt", "গলে যাওয়া", "/mɛlt/", "Ice melts into water at room temperature.", "ঘরের তাপমাত্রায় বরফ গলে পানিতে পরিণত হয়।"],
  ["memorize", "মুখস্থ করা", "/ˈmɛməraɪz/", "Memorize useful vocabulary with sentences.", "বাক্যের সাথে প্রয়োজনীয় শব্দভাণ্ডার মুখস্থ করো।"],
  ["mend", "মেরামত করা", "/mɛnd/", "Cobblers mend old shoes skillfully.", "মুচিরা পুরানো জুতো নিপুণভাবে মেরামত করেন।"],
  ["mention", "উল্লেখ করা", "/ˈmɛnʃn/", "The author mentioned his primary teachers.", "লেখক তার প্রাথমিক বিদ্যালয়ের শিক্ষকদের কথা উল্লেখ করেছিলেন।"],
  ["merge", "একত্রিত হওয়া", "/mɜːrdʒ/", "Two streams merge into a mighty river.", "দুটি জলধারা মিলিত হয়ে একটি বিশাল নদীতে পরিণত হয়।"],
  ["migrate", "স্থানান্তরিত হওয়া", "/maɪˈɡreɪt/", "Siberian birds migrate to our wetlands in winter.", "শীতকালে সাইবেরিয়ার পাখিরা আমাদের জলাভূমিতে পরিযান করে।"],
  ["mimic", "অনুকরণ করা", "/ˈmɪmɪk/", "Parrots mimic human speech accurately.", "তোতাপাখি মানুষের কথা সঠিকভাবে অনুকরণ করে।"],
  ["mingle", "মিশে যাওয়া", "/ˈmɪŋɡl/", "Children mingled happily at the school fair.", "বিদ্যালয়ের মেলায় শিশুরা আনন্দের সাথে মেলামেশা করেছিল।"],
  ["mislead", "ভুল পথে চালিত করা", "/mɪsˈliːd/", "False rumors mislead gullible minds.", "ভুয়া গুজব সরল মনকে ভুল পথে পরিচালিত করে।"],
  ["mix", "মেশানো", "/mɪks/", "Mix fresh honey with warm water.", "কুসুম গরম পানিতে খাঁটি মধু মেশান।"],
  ["modify", "সংশোধন / পরিমার্জন করা", "/ˈmɒdɪfaɪ/", "Modify sentences to improve clarity.", "স্পষ্টতা বাড়াতে বাক্যগুলো পরিমার্জন করুন।"],
  ["motivate", "অনুপ্রাণিত করা", "/ˈmoʊtɪveɪt/", "Encouraging praise motivates students to excel.", "উৎসাহজনক প্রশংসা শিক্ষার্থীদের ভালো করতে অনুপ্রাণিত করে।"],
  ["mourn", "শোক প্রকাশ করা", "/mɔːrn/", "The nation mourns the loss of national heroes.", "জাতি তার জাতীয় বীরদের স্মরণে শোক প্রকাশ করে।"],
  ["multiply", "গুণ করা / বৃদ্ধি পাওয়া", "/ˈmʌltɪplaɪ/", "Kindness multiplies happiness in society.", "দয়া সমাজে সুখকে বহুগুণ বাড়িয়ে দেয়।"],
  ["navigate", "পথ চলা / পরিচালনা করা", "/ˈnævɪɡeɪt/", "Sailors navigate using maps and stars.", "নাবিকরা মানচিত্র ও তারকার সাহায্যে দিক নির্ণয় করে চলেন।"],
  ["negotiate", "আলোচনা করা", "/nɪˈɡoʊʃieɪt/", "Diplomats negotiate peacefully.", "কূটনীতিকরা শান্তিপূর্ণভাবে আলোচনা করেন।"],
  ["nourish", "পুষ্ট করা", "/ˈnʌrɪʃ/", "Fresh milk and fruits nourish the body.", "তাজা দুধ ও ফলমূল শরীরকে পুষ্ট করে।"],
  ["nurture", "যত্নে গড়ে তোলা", "/ˈnɜːrtʃər/", "Teachers nurture talent in classrooms.", "শিক্ষকরা শ্রেণিকক্ষে প্রতিভাকে যত্নে গড়ে তোলেন।"],
  ["notify", "বিজ্ঞপ্তি দিয়ে জানানো", "/ˈnoʊtɪfaɪ/", "The board notified students about exam dates.", "বোর্ড শিক্ষার্থীদের পরীক্ষার তারিখ সম্পর্কে অবহিত করেছে।"],
  ["observe", "পর্যবেক্ষণ করা", "/əbˈzɜːrv/", "Astronomers observe distant stars.", "জ্যোতির্বিজ্ঞানীরা দূরের তারকারাজি পর্যবেক্ষণ করেন।"],
  ["obtain", "অর্জন করা", "/əbˈteɪn/", "He obtained first position in the exam.", "সে পরীক্ষায় প্রথম স্থান অর্জন করেছিল।"],
  ["occupy", "স্থান দখল করা", "/ˈɒkjupaɪ/", "Books occupy shelves neatly.", "বইগুলো সুন্দরভাবে তাকের স্থান দখল করে আছে।"],
  ["occur", "ঘটা", "/əˈkɜːr/", "Eclipses occur in predictable astronomical cycles.", "গ্রহণ নির্দিষ্ট মহাজাগতিক চক্রে ঘটে থাকে।"],
  ["operate", "চালনা করা / শল্যচিকিৎসা করা", "/ˈɒpəreɪt/", "Surgeons operate with skilled precision.", "শল্যচিকিৎসকরা দক্ষতার সাথে অস্ত্রোপচার করেন।"],
  ["oppose", "বিরোধিতা করা", "/əˈpoʊz/", "Honest citizens oppose corruption.", "সৎ নাগরিকরা দুর্নীতির বিরোধিতা করেন।"],
  ["organize", "আয়োজন করা", "/ˈɔːrɡənaɪz/", "Students organized an English debate.", "শিক্ষার্থীরা একটি ইংরেজি বিতর্কের আয়োজন করেছিল।"],
  ["originate", "উৎপন্ন হওয়া", "/əˈrɪdʒɪneɪt/", "The river originates in the high hills.", "নদীটি উঁচু পাহাড় থেকে উৎপন্ন হয়েছে।"],
  ["outline", "রূপরেখা আঁকা", "/ˈaʊtlaɪn/", "Outline your composition before writing.", "লেখার আগে তোমার রচনার রূপরেখা তৈরি করো।"],
  ["overcome", "জয় করা", "/ˌoʊvərˈkʌm/", "Perseverance helps you overcome hurdles.", "অধ্যবসায় তোমাকে বাধা জয় করতে সাহায্য করে।"],
  ["participate", "অংশগ্রহণ করা", "/pɑːrˈtɪsɪpeɪt/", "All students should participate in sports.", "সকল শিক্ষার্থীর খেলাধুলায় অংশ নেওয়া উচিত।"],
  ["perceive", "উপলব্ধি করা", "/pərˈsiːv/", "He perceived the truth behind the smile.", "সে হাসির পেছনের সত্যটি উপলব্ধি করেছিল।"],
  ["perform", "পরিবেশন করা", "/pərˈfɔːrm/", "The choir performed patriotic songs.", "গায়কদল দেশাত্মবোধক গান পরিবেশন করেছিল।"],
  ["permit", "অনুমতি দেওয়া", "/pərˈmɪt/", "School rules do not permit mobile phones.", "বিদ্যালয়ের নিয়মে মোবাইল ফোন ব্যবহারের অনুমতি নেই।"],
  ["persevere", "অধ্যবসায়ী হওয়া", "/ˌpɜːrsɪˈvɪər/", "Persevere until you master grammar.", "ব্যাকরণ আয়ত্ত না হওয়া পর্যন্ত লেগে থাকুন।"],
  ["persuade", "রাজি করানো", "/pərˈsweɪd/", "She persuaded her friends to plant trees.", "সে তার বন্ধুদের বৃক্ষরোপণে রাজি করিয়েছিল।"],
  ["plant", "রোপণ করা", "/plænt/", "Plant saplings along school walkways.", "বিদ্যালয়ের হাঁটার পথের পাশে চারাগাছ রোপণ করো।"],
  ["postpone", "স্থগিত রাখা", "/poʊstˈpoʊn/", "The game was postponed due to heavy rain.", "ভারী বৃষ্টির কারণে খেলাটি স্থগিত রাখা হয়েছিল।"],
  ["praise", "প্রশংসা করা", "/preɪz/", "Teachers praise students who study sincerely.", "শিক্ষকরা আন্তরিকভাবে পড়াশোনা করা শিক্ষার্থীদের প্রশংসা করেন।"],
  ["pray", "প্রার্থনা করা", "/preɪ/", "Citizens pray for peace and prosperity.", "নাগরিকরা শান্তি ও সমৃদ্ধির জন্য প্রার্থনা করেন।"],
  ["predict", "ভবিষ্যদ্বাণী করা", "/prɪˈdɪkt/", "Meteorologists predict sunny weather.", "আবহাওয়াবিদরা রৌদ্রোজ্জ্বল আবহাওয়ার পূর্বাভাস দিয়েছেন।"],
  ["prefer", "অধিক পছন্দ করা", "/prɪˈfɜːr/", "I prefer green vegetables and fruits.", "আমি সবুজ শাকসবজি এবং ফল বেশি পছন্দ করি।"],
  ["prepare", "প্রস্তুতি নেওয়া", "/prɪˈpɛər/", "Prepare your lessons every evening.", "প্রতি সন্ধ্যায় তোমার পাঠ প্রস্তুত করো।"],
  ["preserve", "সংরক্ষণ করা", "/prɪˈzɜːrv/", "Preserve cultural heritage for the future.", "ভবিষ্যতের জন্য সাংস্কৃতিক ঐতিহ্য সংরক্ষণ করুন।"],
  ["prevent", "প্রতিরোধ করা", "/prɪˈvɛnt/", "Hygiene prevents diseases.", "স্বাস্থ্যবিধি রোগব্যাধি প্রতিরোধ করে।"],
  ["produce", "উৎপাদন করা", "/prəˈdjuːs/", "Fertile fields produce bountiful crops.", "উর্বর মাঠ প্রচুর ফসল উৎপাদন করে।"],
  ["protect", "রক্ষা করা", "/prəˈtɛkt/", "Trees protect riverbanks from erosion.", "গাছপালা নদীর পাড় ভাঙন থেকে রক্ষা করে।"],
  ["provide", "সরবরাহ করা", "/prəˈvaɪd/", "Libraries provide free knowledge.", "গ্রন্থাগার বিনামূল্যে জ্ঞান সরবরাহ করে।"],
  ["publish", "প্রকাশ করা", "/ˈpʌblɪʃ/", "The board published the annual results.", "শিক্ষা বোর্ড বার্ষিক ফলাফল প্রকাশ করেছে।"],
  ["pursue", "অনুসরণ করা / অন্বেষণ করা", "/pərˈsjuː/", "Pursue knowledge with relentless enthusiasm.", "অবিরাম উৎসাহের সাথে জ্ঞান অন্বেষণ করুন।"],
  ["qualify", "যোগ্যতা অর্জন করা", "/ˈkwɒlɪfaɪ/", "He qualified for the national scholarship.", "সে জাতীয় বৃত্তির যোগ্যতা অর্জন করেছিল।"],
  ["quench", "নিবারণ করা", "/kwɛntʃ/", "Cold water quenches summer thirst.", "শীতল পানি গ্রীষ্মের তৃষ্ণা নিবারণ করে।"],
  ["question", "জিজ্ঞাসা করা", "/ˈkwɛstʃən/", "Always question what you do not understand.", "যা বোঝো না সে বিষয়ে সর্বদা প্রশ্ন করো।"],
  ["quit", "ত্যাগ করা", "/kwɪt/", "Never quit learning English.", "ইংরেজি শেখা কখনো ছেড়ে দেবেন না।"],
  ["radiate", "বিকিরণ করা", "/ˈreɪdieɪt/", "The lamp radiates a soft warm light.", "বাতিটি মৃদু উষ্ণ আলো বিকিরণ করে।"],
  ["reach", "পৌঁছানো", "/riːtʃ/", "We reached the village at sundown.", "আমরা সূর্যাস্তের সময় গ্রামে পৌঁছেছিলাম।"],
  ["react", "প্রতিক্রিয়া দেখানো", "/riˈækt/", "Think before you react angrily.", "রাগান্বিত প্রতিক্রিয়া দেখানোর আগে ভাবুন।"],
  ["realize", "উপলব্ধি করা", "/ˈriːəlaɪz/", "He realized the true value of education.", "সে শিক্ষার প্রকৃত মূল্য উপলব্ধি করেছিল।"],
  ["rebuild", "পুনর্নির্মাণ করা", "/ˌriːˈbɪld/", "Communities rebuilt damaged schools.", "সমাজ ক্ষতিগ্রস্ত বিদ্যালয়গুলো পুনর্নির্মাণ করেছিল।"],
  ["recall", "স্মরণ করা", "/rɪˈkɔːl/", "Grandparents recall their childhood tales.", "দাদা-দাদিরা তাদের শৈশবের গল্প স্মরণ করেন।"],
  ["receive", "গ্রহণ করা", "/rɪˈsiːv/", "She received an award for academic merit.", "মেধার জন্য সে একটি পুরস্কার গ্রহণ করেছিল।"],
  ["recognize", "স্বীকৃতি দেওয়া", "/ˈrɛkəɡnaɪz/", "The committee recognized his honesty.", "কমিটি তার সততাকে স্বীকৃতি দিয়েছিল।"],
  ["recommend", "সুপারিশ করা", "/ˌrɛkəˈmɛnd/", "I recommend this vocabulary book.", "আমি এই শব্দভাণ্ডারের বইটি সুপারিশ করছি।"],
  ["reconcile", "মীমাংসা করা", "/ˈrɛkənsaɪl/", "Friends reconciled after an argument.", "তর্কের পর বন্ধুরা আবার মিলেমিশে গেল।"],
  ["recover", "আরোগ্য লাভ করা", "/rɪˈkʌvər/", "He recovered his strength after rest.", "বিশ্রামের পর সে তার শক্তি পুনরুদ্ধার করল।"],
  ["rectify", "সংশোধন করা", "/ˈrɛktɪfaɪ/", "Rectify spelling errors immediately.", "বানানের ভুলগুলো তাৎক্ষণিকভাবে সংশোধন করুন।"],
  ["reduce", "কমানো", "/rɪˈdjuːs/", "Save paper to reduce deforestation.", "বন উজাড় কমাতে কাগজের অপচয় কমান।"],
  ["reflect", "প্রতিফলিত করা", "/rɪˈflɛkt/", "Calm waters reflect the evening stars.", "শান্ত পানি সন্ধ্যার তারকারাজিকে প্রতিফলিত করে।"],
  ["reform", "সংস্কার করা", "/rɪˈfɔːrm/", "Education reforms modernize teaching methods.", "শিক্ষা সংস্কার শিক্ষাদান পদ্ধতিকে আধুনিক করে।"],
  ["refresh", "সতেজ করা", "/rɪˈfrɛʃ/", "A cool drink refreshes tired students.", "শীতল পানীয় ক্লান্ত শিক্ষার্থীদের সতেজ করে।"],
  ["refuse", "প্রত্যাখ্যান করা", "/rɪˈfjuːz/", "Refuse to engage in dishonest deeds.", "অসৎ কাজে যুক্ত হতে অস্বীকৃতি জানান।"],
  ["reinforce", "সুদৃঢ় করা", "/ˌriːɪnˈfɔːrs/", "Grammar drills reinforce language skills.", "ব্যাকরণ অনুশীলন ভাষার দক্ষতাকে সুদৃঢ় করে।"],
  ["rejoice", "আনন্দ প্রকাশ করা", "/rɪˈdʒɔɪs/", "The whole class rejoiced at the news.", "সংবাদটি শুনে পুরো ক্লাস আনন্দে মেতে উঠেছিল।"],
  ["relieve", "উপশম করা", "/rɪˈliːv/", "Kind words relieve emotional distress.", "সদয় কথা মানসিক কষ্ট উপশম করে।"],
  ["remember", "মনে রাখা", "/rɪˈmɛmbər/", "Remember your civic responsibilities.", "তোমার নাগরিক দায়িত্বসমূহ মনে রেখো।"],
  ["remind", "মনে করিয়ে দেওয়া", "/rɪˈmaɪnd/", "Remind me to return the library book.", "লাইব্রেরির বইটি ফেরত দেওয়ার কথা মনে করিয়ে দিও।"],
  ["renew", "নবায়ন করা", "/rɪˈnjuː/", "Renew your membership at the library.", "পাঠাগারে তোমার সদস্যপদ নবায়ন করো।"],
  ["repair", "মেরামত করা", "/rɪˈpɛər/", "The mechanic repaired the bicycle chain.", "মেকানিক সাইকেলের চেইনটি মেরামত করেছিলেন।"],
  ["repeat", "পুনরাবৃত্তি করা", "/rɪˈpiːt/", "Repeat new words aloud three times.", "নতুন শব্দগুলো তিনবার উচ্চস্বরে পুনরাবৃত্তি করো।"],
  ["replace", "প্রতিস্থাপন করা", "/rɪˈpleɪs/", "Replace negative thoughts with hope.", "নেতিবাচক ভাবনাকে আশা দিয়ে প্রতিস্থাপন করো।"],
  ["reply", "উত্তর দেওয়া", "/rɪˈplaɪ/", "Reply promptly to important letters.", "জরুরি চিঠির দ্রুত উত্তর দিন।"],
  ["represent", "প্রতিনিধিত্ব করা", "/ˌrɛprɪˈzɛnt/", "Athletes represent their schools proudly.", "ক্রীড়াবিদরা গর্বের সাথে তাদের বিদ্যালয়ের প্রতিনিধিত্ব করেন।"],
  ["rescue", "উদ্ধার করা", "/ˈrɛskjuː/", "Firefighters rescued people from danger.", "অগ্নিনির্বাপক কর্মীরা বিপদ থেকে মানুষকে উদ্ধার করেছিলেন।"],
  ["research", "গবেষণা করা", "/rɪˈsɜːrtʃ/", "Scientists research renewable energy solutions.", "বিজ্ঞানীরা নবায়নযোগ্য শক্তির সমাধান নিয়ে গবেষণা করেন।"],
  ["resolve", "সমাধান করা", "/rɪˈzɒlv/", "Resolve misunderstandings through calm talk.", "শান্ত আলোচনার মাধ্যমে ভুল বোঝাবুঝি সমাধান করুন।"],
  ["respect", "শ্রদ্ধা করা", "/rɪˈspɛkt/", "Respect teachers and elders sincerely.", "শিক্ষক ও গুরুজনদের আন্তরিকভাবে শ্রদ্ধা করুন।"],
  ["restore", "পুনরুদ্ধার করা", "/rɪˈstɔːr/", "Community groups restore public ponds.", "সামাজিক দলগুলো সরকারি পুকুরগুলো পুনরুদ্ধার করে।"],
  ["reveal", "উন্মোচন করা", "/rɪˈviːl/", "Honest investigation reveals the truth.", "সৎ তদন্ত সত্যকে উন্মোচন করে।"],
  ["revere", "শ্রদ্ধা নিবেদন করা", "/rɪˈvɪər/", "We revere national freedom fighters.", "আমরা জাতীয় মুক্তিযোদ্ধাদের প্রতি শ্রদ্ধা নিবেদন করি।"],
  ["revise", "রিভিশন দেওয়া", "/rɪˈvaɪz/", "Revise your vocabulary notes weekly.", "প্রতি সপ্তাহে তোমার শব্দভাণ্ডারের নোট রিভিশন দাও।"],
  ["reward", "পুরস্কৃত করা", "/rɪˈwɔːrd/", "The school rewarded diligent students.", "বিদ্যালয় পরিশ্রমী শিক্ষার্থীদের পুরস্কৃত করেছিল।"],
  ["roam", "ঘুরে বেড়ানো", "/roʊm/", "Cattle roam across green pastures.", "সবুজ চারণভূমিতে গবাদি পশু ঘুরে বেড়ায়।"],
  ["rotate", "আবর্তন করা", "/roʊˈteɪt/", "The earth rotates around its own axis.", "পৃথিবী নিজের অক্ষের ওপর আবর্তন করে।"]
];
