export const verbsListPart3 = [
  // S
  ["salute", "সালাম জানানো / অভিবাদন দেওয়া", "/səˈluːt/", "Scouts salute the national flag proudly.", "স্কাউটরা গর্বের সাথে জাতীয় পতাকাকে সালাম জানায়।"],
  ["satisfy", "সন্তুষ্ট করা", "/ˈsætɪsfaɪ/", "Good education satisfies intellectual curiosity.", "উত্তম শিক্ষা বুদ্ধিবৃত্তিক কৌতূহলকে সন্তুষ্ট করে।"],
  ["save", "সংরক্ষণ করা / বাঁচানো", "/seɪv/", "Save fresh water and avoid wastage.", "বিশুদ্ধ পানি সংরক্ষণ করুন এবং অপচয় পরিহার করুন।"],
  ["say", "বলা", "/seɪ/", "Always say courteous words to others.", "অন্যদের সাথে সর্বদা মার্জিত কথা বলুন।"],
  ["scan", "স্ক্যান করা / গভীরভাবে চোখ বুলানো", "/skæn/", "Scan the chapter for important dates.", "গুরুত্বপূর্ণ তারিখের জন্য অধ্যায়টিতে চোখ বুলিয়ে নিন।"],
  ["scare", "ভয় দেখানো", "/skɛər/", "Sudden thunder scared the stray cat.", "হঠাৎ বজ্রপাত বেওয়ারিশ বিড়ালটিকে ভয় দেখিয়েছিল।"],
  ["scatter", "ছড়িয়ে দেওয়া", "/ˈskætər/", "Farmers scatter seeds across moist earth.", "কৃষকরা ভেজা মাটিতে বীজ ছড়িয়ে দেন।"],
  ["schedule", "সময়সূচি নির্ধারণ করা", "/ˈʃɛdjuːl/", "Schedule your study sessions consistently.", "ধারাবাহিকভাবে তোমার পড়ার সময়সূচি নির্ধারণ করো।"],
  ["scold", "বকা দেওয়া", "/skoʊld/", "Teachers rarely scold well-behaved learners.", "ভদ্র শিক্ষার্থীদের শিক্ষকরা খুব কমই বকা দেন।"],
  ["scratch", "আঁচড়ানো", "/skrætʃ/", "Do not scratch the polished wooden bench.", "পালিশ করা কাঠের বেঞ্চে আঁচড় কাটবেন না।"],
  ["scream", "চিৎকার করা", "/skriːm/", "Do not scream in quiet library rooms.", "শান্ত পাঠাগারে চিৎকার করবেন না।"],
  ["screen", "যাচাই করে নির্বাচন করা", "/skriːn/", "Officers screen applicants based on merit.", "কর্মকর্তারা মেধার ভিত্তিতে আবেদনকারীদের যাচাই করেন।"],
  ["seal", "সিলমোহর দেওয়া", "/siːl/", "Seal the letter envelope securely.", "চিঠির খামটি নিরাপদে সিলমোহর করুন।"],
  ["search", "অনুসন্ধান করা", "/sɜːrtʃ/", "Search for knowledge like hidden treasure.", "গুপ্তধনের মতো জ্ঞানের অনুসন্ধান করো।"],
  ["secure", "নিরাপদ করা / অর্জন করা", "/sɪˈkjʊər/", "Secure your bicycle with a strong lock.", "তোমার সাইকেলটি একটি মজবুত তালা দিয়ে সুরক্ষিত করো।"],
  ["see", "দেখা", "/siː/", "We see green paddy fields all around.", "আমরা চারপাশে সবুজ ধানের ক্ষেত দেখতে পাই।"],
  ["seek", "খোঁজা / অন্বেষণ করা", "/siːk/", "Seek truth and shun deceptive ways.", "সত্যের অন্বেষণ করো এবং প্রতারণামূলক পথ বর্জন করো।"],
  ["select", "নির্বাচন করা", "/sɪˈlɛkt/", "Select the best answer from the options.", "বিকল্পগুলো থেকে সেরা উত্তরটি নির্বাচন করো।"],
  ["sell", "বিক্রি করা", "/sɛl/", "Farmers sell organic vegetables in bazaars.", "কৃষকরা বাজারে জৈব শাকসবজি বিক্রি করেন।"],
  ["send", "পাঠানো", "/sɛnd/", "Send informative emails to your classmates.", "তোমার সহপাঠীদের তথ্যবহুল ইমেল পাঠাও।"],
  ["separate", "পৃথক করা", "/ˈsɛpəreɪt/", "Separate paper waste from plastic bottles.", "প্লাস্টিকের বোতল থেকে কাগজের বর্জ্য পৃথক করুন।"],
  ["serve", "সেবা করা", "/sɜːrv/", "Serve society through honesty and compassion.", "সততা ও সহানুভূতির মাধ্যমে সমাজের সেবা করুন।"],
  ["settle", "নিষ্পত্তি করা / বসতি স্থাপন করা", "/ˈsɛtl/", "They settled the matter amicably.", "তারা বিষয়টি বন্ধুত্বপূর্ণভাবে নিষ্পত্তি করেছিল।"],
  ["shake", "নাড়ানো / হাত মেলানো", "/ʃeɪk/", "Shake hands politely when meeting guests.", "অতিথিদের সাথে সাক্ষাতের সময় ভদ্রভাবে হাত মেলান।"],
  ["shape", "আকার দেওয়া / গড়ে তোলা", "/ʃeɪp/", "Quality education shapes human character.", "গুণগত শিক্ষা মানুষের চরিত্র গঠন করে।"],
  ["share", "ভাগাভাগি করা", "/ʃɛər/", "Share your English notes with study partners.", "পড়ার সাথীদের সাথে তোমার ইংরেজি নোট শেয়ার করো।"],
  ["sharpen", "ধারালো করা", "/ˈʃɑːrpən/", "Sharpen your pencil before drawing maps.", "মানচিত্র আঁকার আগে তোমার পেন্সিল ধারালো করো।"],
  ["shine", "উজ্জ্বল হওয়া / আলো দেওয়া", "/ʃaɪn/", "Stars shine brightly in moonless nights.", "চাঁদহীন রাতে তারকারা উজ্জ্বলভাবে আলো দেয়।"],
  ["shock", "হতবাক করা", "/ʃɒk/", "The sudden news shocked everyone.", "হঠাৎ সংবাদটি সবাইকে হতবাক করেছিল।"],
  ["shoot", "গুলি করা / অঙ্কুরোদগম হওয়া", "/ʃuːt/", "Green sprouts shoot up from the soil.", "মাটি থেকে সবুজ কচি চারা গজিয়ে ওঠে।"],
  ["shorten", "সংক্ষিপ্ত করা", "/ˈʃɔːrtn/", "Shorten lengthy essays for concise reading.", "সংক্ষিপ্ত পাঠের জন্য দীর্ঘ রচনা ছোট করো।"],
  ["shout", "চিৎকার করে বলা", "/ʃaʊt/", "Never shout at domestic animals.", "গৃহপালিত পশুপাখির দিকে কখনোই চিৎকার করবেন না।"],
  ["show", "প্রদর্শন করা", "/ʃoʊ/", "Show kindness to all living beings.", "সকল জীবের প্রতি দয়া প্রদর্শন করুন।"],
  ["shrink", "সংকুচিত হওয়া", "/ʃrɪŋk/", "Woolen clothes shrink in very hot water.", "অতিরিক্ত গরম পানিতে উলের কাপড় সংকুচিত হয়।"],
  ["shut", "বন্ধ করা", "/ʃʌt/", "Shut the classroom door gently.", "শ্রেণিকক্ষের দরজা আলতো করে বন্ধ করো।"],
  ["sign", "স্বাক্ষর করা", "/saɪn/", "Sign your name clearly on the sheet.", "কাগজে পরিষ্কারভাবে তোমার নাম স্বাক্ষর করো।"],
  ["signal", "সংকেত দেওয়া", "/ˈsɪɡnəl/", "The whistle signaled the start of race.", "বাঁশিটি দৌড় শুরুর সংকেত দিয়েছিল।"],
  ["simplify", "সহজবোধ্য করা", "/ˈsɪmplɪfaɪ/", "Teachers simplify complicated mathematics.", "শিক্ষকরা জটিল গণিতকে সহজবোধ্য করে তোলেন।"],
  ["sing", "গান গাওয়া", "/sɪŋ/", "Children sing folk songs melodiously.", "শিশুরা সুর করে লোকগান গায়।"],
  ["sink", "ডুবে যাওয়া", "/sɪŋk/", "Heavy stones sink quickly in water.", "ভারী পাথর পানিতে দ্রুত ডুবে যায়।"],
  ["sit", "বসা", "/sɪt/", "Sit straight for a healthy posture.", "স্বাস্থ্যকর ভঙ্গির জন্য সোজা হয়ে বসুন।"],
  ["skip", "লাফিয়ে চলা / এড়িয়ে যাওয়া", "/skɪp/", "Never skip your morning breakfast.", "সকালের নাশতা কখনোই বাদ দেবেন না।"],
  ["slam", "শব্দ করে বন্ধ করা", "/slæm/", "Do not slam the wooden door.", "কাঠের দরজাটি শব্দ করে ধাক্কা দিয়ে বন্ধ করবেন না।"],
  ["sleep", "ঘুমানো", "/sliːp/", "Sleep eight hours nightly for vitality.", "কর্মশক্তির জন্য রাতে আট ঘণ্টা ঘুমান।"],
  ["slide", "পিছলে যাওয়া", "/slaɪd/", "The boat slid smoothly into the river.", "নৌকাটি মসৃণভাবে নদীতে নেমে গেল।"],
  ["slip", "পা পিছলে যাওয়া", "/slɪp/", "Walk cautiously so you do not slip.", "সাবধানে হাঁটুন যাতে পা পিছলে না যায়।"],
  ["smell", "গন্ধ নেওয়া", "/smɛl/", "Night jasmine smells sweet at dusk.", "সন্ধ্যায় বেলি ফুলের মিষ্টি সুবাস পাওয়া যায়।"],
  ["smile", "হাসা", "/smaɪl/", "Smile warmly to brighten someone's day.", "কারও দিন উজ্জ্বল করতে উষ্ণ হাসি দিন।"],
  ["smoke", "ধোঁয়া ওড়ানো / ধূমপান করা", "/smoʊk/", "Never smoke as it destroys health.", "ধূমপান করবেন না কারণ এটি স্বাস্থ্য ধ্বংস করে।"],
  ["smooth", "মসৃণ করা", "/smuːð/", "Carpenters smooth rough wooden surfaces.", "কাঠমিস্ত্রিরা খসখসে কাঠের উপরিভাগ মসৃণ করেন।"],
  ["snap", "মট করে ভেঙে যাওয়া", "/snæp/", "Dry branches snap underfoot in the woods.", "বনে পায়ের নিচে শুকনো ডাল মট করে ভেঙে যায়।"],
  ["snatch", "ছিনিয়ে নেওয়া", "/snætʃ/", "Monkeys snatched ripe bananas from stalls.", "বানররা দোকান থেকে পাকা কলা ছিনিয়ে নিয়েছিল।"],
  ["sneeze", "হাঁচি দেওয়া", "/sniːz/", "Cover your nose when you sneeze.", "হাঁচি দেওয়ার সময় নাক ঢেকে রাখুন।"],
  ["snore", "নাক ডাকা", "/snɔːr/", "Deep sleep may cause someone to snore.", "গভীর ঘুমে কেউ নাক ডাকতে পারে।"],
  ["soak", "ভিজিয়ে রাখা", "/soʊk/", "Soak seeds overnight before planting.", "রোপণের আগে বীজ সারারাত ভিজিয়ে রাখুন।"],
  ["solve", "সমাধান করা", "/sɒlv/", "Solve the crossword puzzle patiently.", "ধৈর্য ধরে শব্দছক ধাঁধাটি সমাধান করো।"],
  ["soothe", "শান্ত করা / উপশম করা", "/suːð/", "Her gentle words soothed the anxious child.", "তার মিষ্টি কথা উদ্বিগ্ন শিশুকে শান্ত করেছিল।"],
  ["sort", "বাছাই করা", "/sɔːrt/", "Sort the vocabulary cards alphabetically.", "শব্দভাণ্ডারের কার্ডগুলো বর্ণানুক্রমে সাজাও।"],
  ["spark", "স্ফুলিঙ্গ ছড়ানো / জাগিয়ে তোলা", "/spɑːrk/", "Good questions spark lively debates.", "উত্তম প্রশ্ন প্রাণবন্ত বিতর্কের জন্ম দেয়।"],
  ["speak", "কথা বলা", "/spiːk/", "Practice speaking English every day.", "প্রতিদিন ইংরেজিতে কথা বলার অনুশীলন করো।"],
  ["specialize", "বিশেষজ্ঞ হওয়া", "/ˈspɛʃəlaɪz/", "Doctors specialize in pediatric health.", "চিকিৎসকরা শিশু স্বাস্থ্যে বিশেষ দক্ষতা অর্জন করেন।"],
  ["specify", "নির্দিষ্টভাবে উল্লেখ করা", "/ˈspɛsɪfaɪ/", "Specify the exact date on your paper.", "তোমার কাগজে সুনির্দিষ্ট তারিখ উল্লেখ করো।"],
  ["speed", "দ্রুত চলা", "/spiːd/", "The train sped past green countryside.", "ট্রেনটি সবুজ পল্লিপ্রকৃতির পাশ দিয়ে দ্রুত ছুটে গেল।"],
  ["spell", "বানান করা", "/spɛl/", "Spell the new adjectives with precision.", "নতুন বিশেষণগুলো নিখুঁত বানানে লেখো।"],
  ["spend", "ব্যয় করা", "/spɛnd/", "Spend your time acquiring wisdom.", "জ্ঞান অর্জনে তোমার সময় ব্যয় করো।"],
  ["spill", "ছড়িয়ে পড়া / ফেলে দেওয়া", "/spɪl/", "Be careful not to spill milk on books.", "বইয়ের ওপর যেন দুধ না পড়ে সে বিষয়ে সতর্ক থাকুন।"],
  ["spin", "ঘোরা / সুতা কাটা", "/spɪn/", "Weavers spin fine cotton yarn.", "তাঁতিরা সূক্ষ্ম সুতি সুতা কাটেন।"],
  ["spoil", "নষ্ট করা", "/spɔɪl/", "Excess heat spoils fresh milk.", "অতিরিক্ত তাপে টাটকা দুধ নষ্ট হয়ে যায়।"],
  ["spread", "ছড়িয়ে দেওয়া", "/sprɛd/", "Spread goodness and cheerful smiles.", "মঙ্গল ও আনন্দের হাসি ছড়িয়ে দিন।"],
  ["spring", "লাফিয়ে ওঠা / গজিয়ে ওঠা", "/sprɪŋ/", "Wildflowers spring up across green lawns.", "সবুজ ঘাসের বুকে বুনো ফুল ফুটে ওঠে।"],
  ["sprinkle", "ছিটানো", "/ˈsprɪŋkl/", "Sprinkle fresh water on green plants.", "সবুজ গাছপালায় তাজা পানি ছিটিয়ে দিন।"],
  ["sprout", "অঙ্কুরিত হওয়া", "/spraʊt/", "Moist seeds sprout within two days.", "ভেজা বীজ দুই দিনের মধ্যে অঙ্কুরিত হয়।"],
  ["squeeze", "নিংড়ানো", "/skwiːz/", "Squeeze fresh lemon into the tea.", "চায়ে তাজা লেবু নিংড়ে নিন।"],
  ["stabilize", "স্থিতিশীল করা", "/ˈsteɪbəlaɪz/", "Medicines stabilize body temperature.", "ওষুধ শরীরের তাপমাত্রা স্থিতিশীল করে।"],
  ["stain", "দাগ লাগানো", "/steɪn/", "Ink can stain your white shirt.", "কালি তোমার সাদা শার্টে দাগ ফেলতে পারে।"],
  ["stamp", "পদচিহ্ন দেওয়া / স্ট্যাম্প মারা", "/stæmp/", "The clerk stamped the admission letter.", "কেরানি ভর্তির চিঠিতে স্ট্যাম্প মেরেছিলেন।"],
  ["stand", "দাঁড়ানো", "/stænd/", "Stand up when greeting your teacher.", "শিক্ষককে অভিবাদন জানানোর সময় উঠে দাঁড়াও।"],
  ["stare", "একদৃষ্টিতে তাকানো", "/stɛər/", "Do not stare rudely at passersby.", "পথচারীদের দিকে অভদ্রভাবে একদৃষ্টিতে তাকিয়ে থাকবেন না।"],
  ["start", "শুরু করা", "/stɑːrt/", "Start your day with productive reading.", "ফলপ্রসূ অধ্যয়নের মাধ্যমে তোমার দিন শুরু করো।"],
  ["state", "বিবৃত করা / বলা", "/steɪt/", "State the facts clearly in the report.", "প্রতিবেদনে ঘটনাগুলো স্পষ্টভাবে বিবৃত করো।"],
  ["stay", "অবস্থান করা", "/steɪ/", "Stay focused on your educational goals.", "তোমার শিক্ষামূলক লক্ষ্যে অবিচল থাকো।"],
  ["steal", "চুরি করা", "/stiːl/", "Honest individuals never steal anything.", "সৎ ব্যক্তিরা কখনোই কোনো কিছু চুরি করেন না।"],
  ["steam", "ভাপে রান্না করা", "/stiːm/", "Steam fresh vegetables for pure nutrition.", "খাঁটি পুষ্টির জন্য তাজা শাকসবজি ভাপে সিদ্ধ করুন।"],
  ["steer", "দিক চালনা করা", "/stɪər/", "The helmsman steers the boat safely.", "মাঝি সাবধানে নৌকাটি পরিচালনা করেন।"],
  ["step", "পা ফেলা", "/stɛp/", "Step forward with confidence and hope.", "আত্মবিশ্বাস ও আশা নিয়ে সামনে পা বাড়াও।"],
  ["stick", "আটকে থাকা / লাগিয়ে দেওয়া", "/stɪk/", "Stick the postage stamp on the envelope.", "খামের ওপর ডাকটিকিটটি আঠা দিয়ে লাগিয়ে দাও।"],
  ["stimulate", "উদ্দীপ্ত করা", "/ˈstɪmjuleɪt/", "Challenging puzzles stimulate mental wit.", "কঠিন ধাঁধা মানসিক বুদ্ধিমত্তাকে উদ্দীপ্ত করে।"],
  ["stir", "নাড়াচাড়া করা", "/stɜːr/", "Stir the sugar into the warm milk.", "গরম দুধে চিনি দিয়ে ভালোভাবে নাড়ুন।"],
  ["stop", "থামা / বন্ধ করা", "/stɒp/", "Stop when traffic lights turn red.", "ট্রাফিক বাতি লাল হলে থেমে যান।"],
  ["store", "সংরক্ষণ করা", "/stɔːr/", "Store dry grain in ventilated rooms.", "বায়ু চলাচলযুক্ত ঘরে শুকনো শস্য সংরক্ষণ করুন।"],
  ["straighten", "সোজা করা", "/ˈstreɪtn/", "Straighten the picture frame on the wall.", "দেওয়ালের ছবির ফ্রেমটি সোজা করো।"],
  ["strengthen", "শক্তিশালী করা", "/ˈstrɛŋθən/", "Daily practice strengthens memory.", "প্রতিদিনের অনুশীলন স্মৃতিশক্তিকে শক্তিশালী করে।"],
  ["stretch", "প্রসারিত করা", "/strɛtʃ/", "Stretch your arms and legs after sitting long.", "দীর্ঘক্ষণ বসে থাকার পর হাত-পা টানটান করুন।"],
  ["stride", "লম্বা পদক্ষেপে হাঁটা", "/straɪd/", "He strode into the hall with confidence.", "সে আত্মবিশ্বাসের সাথে লম্বা পদক্ষেপে হলঘরে ঢুকল।"],
  ["strike", "আঘাত করা / ধর্মঘট করা", "/straɪk/", "The grandfather clock struck midnight.", "পুরানো দেয়ালঘড়িতে মধ্যরাতের ঘণ্টা বাজল।"],
  ["strive", "আপ্রাণ চেষ্টা করা", "/straɪv/", "Strive for excellence in every task.", "প্রতিটি কাজে উৎকর্ষের জন্য আপ্রাণ চেষ্টা করো।"],
  ["struggle", "সংগ্রাম করা", "/ˈstrʌɡl/", "Freedom fighters struggled for our freedom.", "মুক্তিযোদ্ধারা আমাদের স্বাধীনতার জন্য সংগ্রাম করেছিলেন।"],
  ["study", "অধ্যয়ন করা", "/ˈstʌdi/", "Study grammar rules with dedication.", "নিষ্ঠার সাথে ব্যাকরণের নিয়ম অধ্যয়ন করো।"],
  ["stumble", "হোঁচট খাওয়া", "/ˈstʌmbl/", "Watch your step so you do not stumble.", "হোঁচট না খাওয়ার জন্য সাবধানে পা ফেলো।"],
  ["submit", "জমা দেওয়া", "/səbˈmɪt/", "Submit your assignment on Friday.", "শুক্রবার তোমার অ্যাসাইনমেন্ট জমা দাও।"],
  ["substitute", "প্রতিস্থাপন করা", "/ˈsʌbstɪtjuːt/", "Substitute fresh fruits for junk snacks.", "ফাস্টফুডের বদলে তাজা ফল গ্রহণ করুন।"],
  ["succeed", "সফল হওয়া", "/səkˈsiːd/", "Hardworking students succeed in life.", "পরিশ্রমী শিক্ষার্থীরা জীবনে সফল হয়।"],
  ["suffer", "ভোগা / সহ্য করা", "/ˈsʌfər/", "Patients suffer when hospitals lack medicine.", "ওষুধের অভাবে রোগীরা কষ্ট ভোগ করে।"],
  ["suggest", "পরামর্শ দেওয়া", "/səˈdʒɛst/", "Mentors suggest good books to read.", "শিক্ষকরা পড়ার জন্য ভালো বইয়ের পরামর্শ দেন।"],
  ["suit", "মানানসই হওয়া", "/suːt/", "This polite tone suits a student.", "এই ভদ্র সুর একজন শিক্ষার্থীর জন্য মানানসই।"],
  ["summarize", "সারসংক্ষেপ করা", "/ˈsʌməraɪz/", "Summarize the story in five sentences.", "পাঁচটি বাক্যে গল্পটির সারসংক্ষেপ করো।"],
  ["supervise", "তত্ত্বাবধান করা", "/ˈsuːpərvaɪz/", "Senior teachers supervise the examinations.", "জ্যেষ্ঠ শিক্ষকরা পরীক্ষাগুলো তত্ত্বাবধান করেন।"],
  ["supply", "সরবরাহ করা", "/səˈplaɪ/", "Rivers supply clean water to villages.", "নদীগুলো গ্রামে বিশুদ্ধ পানি সরবরাহ করে।"],
  ["support", "সমর্থন করা / সাহায্য করা", "/səˈpɔːrt/", "Support your friends in times of need.", "প্রয়োজনের সময় তোমার বন্ধুদের সাহায্য করো।"],
  ["suppose", "মনে করা / ধরে নেওয়া", "/səˈpoʊz/", "Suppose you win first prize in debate.", "ধরে নাও তুমি বিতর্কে প্রথম পুরস্কার পেয়েছ।"],
  ["surpass", "অতিক্রম করা / ছাড়িয়ে যাওয়া", "/sərˈpɑːs/", "His score surpassed all expectations.", "তার স্কোর সকল প্রত্যাশাকে ছাড়িয়ে গিয়েছিল।"],
  ["surprise", "বিস্মিত করা", "/sərˈpraɪz/", "The birthday party surprised the child.", "জন্মদিনের অনুষ্ঠানটি শিশুটিকে বিস্মিত করেছিল।"],
  ["surrender", "আত্মসমর্পণ করা", "/səˈrɛndər/", "Enemies surrendered on December 16, 1971.", "১৯৭১ সালের ১৬ই ডিসেম্বর শত্রুরা আত্মসমর্পণ করেছিল।"],
  ["surround", "ঘিরে রাখা", "/səˈraʊnd/", "Green trees surround the rural school.", "সবুজ গাছপালা গ্রামীণ বিদ্যালয়টিকে ঘিরে রেখেছে।"],
  ["survive", "টিকে থাকা / বেঁচে থাকা", "/sərˈvaɪv/", "Indigenous plants survive dry spells.", "দেশীয় গাছপালা শুষ্ক মৌসুমেও টিকে থাকে।"],
  ["suspect", "সন্দেহ করা", "/səˈspɛkt/", "Officers suspect illegal poaching in woods.", "কর্মকর্তারা বনে অবৈধ শিকারের সন্দেহ করেন।"],
  ["suspend", "স্থগিত করা / ঝুলানো", "/səˈspɛnd/", "Officials suspended the ferry during storms.", "ঝড়ের সময় কর্মকর্তারা ফেরি চলাচল স্থগিত করেছিলেন।"],
  ["sustain", "বজায় রাখা / টিকিয়ে রাখা", "/səˈsteɪn/", "Balanced food sustains good physical vigor.", "সুষম খাবার শারীরিক কর্মক্ষমতা বজায় রাখে।"],
  ["swallow", "গিলে ফেলা", "/ˈswɒloʊ/", "Swallow the medicinal pill with fresh water.", "বিশুদ্ধ পানির সাথে ওষুধের বড়িটি গিলে ফেলুন।"],
  ["sweep", "ঝাড়ু দেওয়া", "/swiːp/", "Students swept the school ground together.", "শিক্ষার্থীরা একসাথে বিদ্যালয় প্রাঙ্গণ ঝাড়ু দিয়েছিল।"],
  ["swim", "সাঁতার কাটা", "/swɪm/", "Children swim happily in the village pond.", "গ্রামের পুকুরে শিশুরা আনন্দের সাথে সাঁতার কাটে।"],
  ["swing", "দোল খাওয়া", "/swɪŋ/", "Children swung on the garden ropes.", "শিশুরা বাগানের দোলনায় দোল খেয়েছিল।"]
];
