export const verbsListPart4 = [
  // T
  ["talk", "কথা বলা", "/tɔːk/", "Talk respectfully with your teachers and parents.", "তোমার শিক্ষক এবং পিতা-মাতার সাথে শ্রদ্ধার সাথে কথা বলো।"],
  ["taste", "স্বাদ গ্রহণ করা", "/teɪst/", "Taste the fresh mango from the garden.", "বাগান থেকে পাড়া তাজা আমের স্বাদ গ্রহণ করো।"],
  ["teach", "শেখানো / পড়ানো", "/tiːtʃ/", "Good teachers teach with immense patience.", "ভালো শিক্ষকরা অপরিসীম ধৈর্যের সাথে শিক্ষা দেন।"],
  ["tear", "ছিঁড়ে ফেলা", "/tɛər/", "Do not tear pages from your exercise books.", "তোমার খাতা থেকে পৃষ্ঠা ছিঁড়বে না।"],
  ["tell", "বলা", "/tɛl/", "Always tell the absolute truth.", "সর্বদা সম্পূর্ণ সত্য কথা বলুন।"],
  ["tend", "পরিচর্যা করা / ঝোঁক থাকা", "/tɛnd/", "The gardener tends the blooming rose bushes.", "মালী প্রস্ফুটিত গোলাপ ঝোপের পরিচর্যা করেন।"],
  ["terminate", "সমাপ্ত করা", "/ˈtɜːrmɪneɪt/", "The conductor terminated the train journey.", "পরিচালক ট্রেন যাত্রা সমাপ্ত ঘোষণা করেছিলেন।"],
  ["test", "পরীক্ষা করা", "/tɛst/", "Weekly quizzes test your vocabulary mastery.", "সাপ্তাহিক কুইজ তোমার শব্দভাণ্ডারের দক্ষতা পরীক্ষা করে।"],
  ["thank", "ধন্যবাদ জানানো", "/θæŋk/", "Thank those who assist you selflessly.", "যারা নিঃস্বার্থভাবে তোমাকে সাহায্য করে তাদের ধন্যবাদ জানাও।"],
  ["thaw", "গলে যাওয়া", "/θɔː/", "Ice thaws quickly in warm sunshine.", "উষ্ণ রোদে বরফ দ্রুত গলে যায়।"],
  ["think", "চিন্তা করা", "/θɪŋk/", "Think deeply before arriving at decisions.", "কোনো সিদ্ধান্তে পৌঁছানোর আগে গভীরভাবে চিন্তা করুন।"],
  ["threaten", "হুমকি দেওয়া", "/ˈθrɛtn/", "Pollution threatens river aquatic life.", "দূষণ নদীর জলজ জীবনকে হুমকির মুখে ফেলে।"],
  ["thrive", "উন্নতি লাভ করা / সতেজ থাকা", "/θraɪv/", "Crops thrive after seasonal monsoon rains.", "মৌসুমি বর্ষার পর ফসল সতেজ হয়ে ওঠে।"],
  ["throw", "নিক্ষেপ করা", "/θroʊ/", "Do not throw trash on public pavements.", "পৌর ফুটপাতে ময়লা-আবর্জনা ফেলবেন না।"],
  ["tie", "বাঁধা", "/taɪ/", "Tie the boat securely to the wooden post.", "নৌকাটি কাঠের খুঁটির সাথে শক্ত করে বাঁধো।"],
  ["tighten", "শক্ত করা", "/ˈtaɪtn/", "Tighten loose bolts on the school desk.", "বিদ্যালয়ের বেঞ্চের আলগা নাট-বোল্ট শক্ত করো।"],
  ["tolerate", "সহ্য করা", "/ˈtɒləreɪt/", "Good citizens tolerate diverse viewpoints.", "সুনাগরিকরা বিভিন্ন দৃষ্টিভঙ্গিকে সহ্য ও সম্মান করেন।"],
  ["touch", "স্পর্শ করা", "/tʌtʃ/", "Do not touch live electric wires.", "সক্রিয় বৈদ্যুতিক তারে হাত দেবেন না।"],
  ["trace", "অনুসন্ধান করা / রূপরেখা আঁকা", "/treɪs/", "Historians trace the roots of language.", "ঐতিহাসিকরা ভাষার শিকড় অনুসন্ধান করেন।"],
  ["track", "অনুসরণ করা / পর্যবেক্ষণ করা", "/træk/", "Use an app to track your daily progress.", "তোমার প্রতিদিনের অগ্রগতি পর্যবেক্ষণ করতে অ্যাপ ব্যবহার করো।"],
  ["trade", "ব্যবসা বাণিজ্য করা", "/treɪd/", "Merchants trade spices at river ports.", "নদীবন্দরে ব্যবসায়ীরা মসলার বাণিজ্য করেন।"],
  ["train", "প্রশিক্ষণ দেওয়া", "/treɪn/", "Schools train students for future careers.", "বিদ্যালয়গুলো ভবিষ্যৎ কর্মজীবনের জন্য শিক্ষার্থীদের প্রস্তুত করে।"],
  ["transfer", "স্থানান্তর করা", "/trænsˈfɜːr/", "He transferred his files to the safe drive.", "সে তার ফাইলগুলো সুরক্ষিত ড্রাইভে স্থানান্তর করেছে।"],
  ["transform", "রূপান্তরিত করা", "/trænsˈfɔːrm/", "Quality education transforms human societies.", "গুণগত শিক্ষা মানব সমাজকে রূপান্তরিত করে।"],
  ["translate", "অনুবাদ করা", "/trænsˈleɪt/", "Translate the English idioms into Bengali.", "ইংরেজি বাগধারাগুলোকে বাংলায় অনুবাদ করুন।"],
  ["transmit", "প্রেরণ করা", "/trænsˈmɪt/", "Radio towers transmit news broadcasts.", "রেডিও টাওয়ারগুলো সংবাদ সম্প্রচার করে।"],
  ["transport", "পরিবহন করা", "/trænsˈpɔːrt/", "Cargo boats transport grain along rivers.", "পণ্যবাহী নৌকা নদীতে শস্য পরিবহন করে।"],
  ["travel", "ভ্রমণ করা", "/ˈtrævl/", "Travel across beautiful rivers of Bangladesh.", "বাংলাদেশের সুন্দর নদীগুলো ধরে ভ্রমণ করুন।"],
  ["treat", "চিকিৎসা করা / ব্যবহার করা", "/triːt/", "Doctors treat patients with sympathetic care.", "চিকিৎসকরা সহমর্মিতার সাথে রোগীদের চিকিৎসা করেন।"],
  ["tremble", "কাঁপানো / কাঁপা", "/ˈtrɛmbl/", "Dry leaves tremble in the autumn breeze.", "শরতের বাতাসে শুকনো পাতা কেঁপে ওঠে।"],
  ["trigger", "শুরু করা / ঘটানো", "/ˈtrɪɡər/", "Kindness triggers joy in human hearts.", "দয়ালু আচরণ মানুষের হৃদয়ে আনন্দ জাগিয়ে তোলে।"],
  ["trim", "ছেঁটে সাজানো", "/trɪm/", "Gardeners trim green hedges symmetrically.", "মালীর দল সুন্দরভাবে সবুজ ঝোপঝাড় ছেঁটে দেন।"],
  ["trust", "বিশ্বাস করা", "/trʌst/", "Trust friends who stand by you in grief.", "যে বন্ধুরা বিপদে পাশে থাকে তাদের বিশ্বাস করুন।"],
  ["turn", "ঘোরা / ফেরানো", "/tɜːrn/", "Turn the page to study the next adjective.", "পরের বিশেষণটি পড়ার জন্য পৃষ্ঠাটি উল্টাও।"],

  // U, V, W, Y, Z
  ["uncover", "উন্মোচন করা", "/ʌnˈkʌvər/", "Historians uncover ancient inscriptions.", "ঐতিহাসিকরা প্রাচীন শিলালিপি উন্মোচন করেন।"],
  ["undergo", "মধ্য দিয়ে যাওয়া / সহ্য করা", "/ˌʌndərˈɡoʊ/", "Trainees undergo rigorous physical training.", "প্রশিক্ষণার্থীরা কঠোর শারীরিক প্রশিক্ষণের মধ্য দিয়ে যান।"],
  ["understand", "বোঝা", "/ˌʌndərˈstænd/", "Strive to understand grammar conceptually.", "ধারণাগতভাবে ব্যাকরণ বোঝার চেষ্টা করো।"],
  ["undertake", "দায়িত্ব গ্রহণ করা", "/ˌʌndərˈteɪk/", "The club undertook a tree planting campaign.", "ক্লাবটি একটি বৃক্ষরোপণ অভিযানের দায়িত্ব গ্রহণ করেছিল।"],
  ["undo", "পূর্বাবস্থায় ফেরানো", "/ʌnˈduː/", "Careful review helps undo thoughtless errors.", "মনোযোগপূর্ণ পর্যালোচনা অসতর্ক ভুলগুলো সংশোধন করতে সাহায্য করে।"],
  ["unfold", "উন্মোচিত হওয়া", "/ʌnˈfoʊld/", "Morning petals unfold under golden sunbeams.", "সোনালি রোদ পেয়ে সকালের পাপড়িগুলো উন্মোচিত হয়।"],
  ["unify", "একত্রিত করা", "/ˈjuːnɪfaɪ/", "Common aspirations unify diverse communities.", "অভিন্ন আকাঙ্ক্ষা বিভিন্ন জনগোষ্ঠীকে ঐক্যবদ্ধ করে।"],
  ["unite", "ঐক্যবদ্ধ হওয়া", "/juˈnaɪt/", "Citizens unite to build an enlightened country.", "একটি আলোকিত দেশ গড়তে নাগরিকরা ঐক্যবদ্ধ হন।"],
  ["unlock", "খোলা", "/ʌnˈlɒk/", "Books unlock the door to endless wisdom.", "বই অনন্ত জ্ঞানের দুয়ার খুলে দেয়।"],
  ["unpack", "খুলে বের করা", "/ʌnˈpæk/", "Unpack your notebooks on the study desk.", "পড়ার টেবিলে তোমার খাতাগুলো বের করো।"],
  ["update", "হালনাগাদ করা", "/ʌpˈdeɪt/", "Update your vocabulary journal daily.", "প্রতিদিন তোমার শব্দভাণ্ডারের নোটবুক হালনাগাদ করো।"],
  ["upgrade", "উন্নীত করা", "/ʌpˈɡreɪd/", "The school upgraded its science laboratory.", "বিদ্যালয়টি তাদের বিজ্ঞান গবেষণাগারকে আধুনিক করেছে।"],
  ["uphold", "উর্ধ্বে তুলে ধরা", "/ʌpˈhoʊld/", "Always uphold justice and truth.", "সর্বদা ন্যায় ও সত্যকে সমুন্নত রাখুন।"],
  ["urge", "তাকাদা দেওয়া / আহ্বান করা", "/ɜːrdʒ/", "Teachers urge students to read good books.", "শিক্ষকরা শিক্ষার্থীদের ভালো বই পড়তে আহ্বান জানান।"],
  ["utilize", "সদ্ব্যবহার করা", "/ˈjuːtəlaɪz/", "Utilize digital quizzes to practice adjectives.", "বিশেষণ অনুশীলনে ডিজিটাল কুইজের সদ্ব্যবহার করুন।"],
  ["vacate", "খালি করা", "/vəˈkeɪt/", "Please vacate the examination hall quietly.", "শান্তভাবে পরীক্ষার হল খালি করুন।"],
  ["validate", "বৈধ করা / যাচাই করা", "/ˈvælɪdeɪt/", "Experiments validate scientific hypotheses.", "পরীক্ষা-নিরীক্ষা বৈজ্ঞানিক অনুকল্প যাচাই করে।"],
  ["value", "মূল্য দেওয়া / কদর করা", "/ˈvæljuː/", "Value your time and spend it wisely.", "তোমার সময়কে মূল্য দাও এবং তা বিচক্ষণতার সাথে ব্যয় করো।"],
  ["vanish", "অদৃশ্য হওয়া", "/ˈvænɪʃ/", "The morning fog vanished as sun rose.", "সূর্য ওঠার সাথে সাথে সকালের কুয়াশা উধাও হয়ে গেল।"],
  ["vary", "পরিবর্তিত হওয়া / ভিন্ন হওয়া", "/ˈvɛəri/", "Folk customs vary across different regions.", "বিভিন্ন অঞ্চলে লোকজ রীতিনীতি ভিন্ন ভিন্ন হয়।"],
  ["venture", "সাহসিক অভিযান করা", "/ˈvɛntʃər/", "Explorers ventured into uncharted rivers.", "অভিযাত্রীরা অজানা নদীতে সাহসিক অভিযান করেছিলেন।"],
  ["verify", "যাচাই করা", "/ˈvɛrɪfaɪ/", "Verify each answer before finishing the quiz.", "কুইজ শেষ করার আগে প্রতিটি উত্তর যাচাই করুন।"],
  ["view", "দর্শন করা / দেখা", "/vjuː/", "We viewed the sunset from the hill summit.", "আমরা পাহাড়ের চূড়া থেকে সূর্যাস্ত প্রত্যক্ষ করেছিলাম।"],
  ["visit", "পরিদর্শন করা", "/ˈvɪzɪt/", "Students visit the historic Lalbagh Fort.", "শিক্ষার্থীরা ঐতিহাসিক লালবাগ কেল্লা পরিদর্শন করে।"],
  ["voice", "কণ্ঠ দেওয়া / প্রকাশ করা", "/vɔɪs/", "Citizens voice opinions through civic forums.", "নাগরিকরা নাগরিক ফোরামে নিজেদের মতামত প্রকাশ করেন।"],
  ["volunteer", "স্বেচ্ছায় সেবা দেওয়া", "/ˌvɒlənˈtɪər/", "Youth volunteer during community health drives.", "সামাজিক স্বাস্থ্য কর্মসূচিতে তরুণরা স্বেচ্ছাসেবা দেয়।"],
  ["vote", "ভোট দেওয়া", "/voʊt/", "Citizens vote to choose upright leaders.", "সৎ নেতা নির্বাচনে নাগরিকরা ভোট দেন।"],
  ["vow", "প্রতিজ্ঞা করা", "/vaʊ/", "Patriots vow to defend the motherland.", "দেশপ্রেমিকরা মাতৃভূমি রক্ষার প্রতিজ্ঞা করেন।"],
  ["wait", "অপেক্ষা করা", "/weɪt/", "Wait patiently for your turn in line.", "লাইনে নিজের পালার জন্য ধৈর্য ধরে অপেক্ষা করুন।"],
  ["wake", "জাগ্রত হওয়া", "/weɪk/", "Wake up early to study English words.", "ইংরেজি শব্দ পড়তে ভোরে ঘুম থেকে উঠুন।"],
  ["walk", "হাঁটা", "/wɔːk/", "Walking briskly promotes cardiovascular fitness.", "দ্রুত হাঁটা হৃদযন্ত্রের সুস্থতা বজায় রাখে।"],
  ["wander", "ঘুরে বেড়ানো", "/ˈwɒndər/", "Travelers wander along picturesque tea gardens.", "ভ্রমণকারীরা মনোরম চা বাগানে ঘুরে বেড়ান।"],
  ["want", "চাওয়া", "/wɒnt/", "We want everyone to achieve good literacy.", "আমরা চাই প্রত্যেকেই ভালো সাক্ষরতা অর্জন করুক।"],
  ["warm", "উষ্ণ করা", "/wɔːrm/", "Morning sunshine warms the cold earth.", "সকালের মিষ্টি রোদ শীতল পৃথিবীকে উষ্ণ করে তোলে।"],
  ["warn", "সতর্ক করা", "/wɔːrn/", "Lifeguards warn tourists against strong waves.", "লাইফগার্ডরা পর্যটকদের উত্তাল ঢেউ সম্পর্কে সতর্ক করেন।"],
  ["wash", "ধৌত করা", "/wɒʃ/", "Wash fresh fruits before eating.", "খাওয়ার আগে তাজা ফল ধৌত করুন।"],
  ["waste", "অপচয় করা", "/weɪst/", "Never waste clean drinking water.", "বিশুদ্ধ খাবার পানি কখনোই অপচয় করবেন না।"],
  ["watch", "পর্যবেক্ষণ করা / দেখা", "/wɒtʃ/", "Watch English documentaries to sharpen listening.", "শোনার দক্ষতা বাড়াতে ইংরেজি তথ্যচিত্র দেখুন।"],
  ["water", "পানি দেওয়া", "/ˈwɔːtər/", "Water flower plants every dawn.", "প্রতি ভোরে ফুলের গাছে পানি দিন।"],
  ["wave", "হাত নাড়ানো / তরঙ্গায়িত হওয়া", "/weɪv/", "The green flag waved gracefully in the breeze.", "বাতাসে সবুজ পতাকাটি সুন্দরভাবে দুলছিল।"],
  ["wear", "পরিধান করা", "/wɛər/", "Wear clean clothes to school.", "বিদ্যালয়ে পরিষ্কার পরিচ্ছন্ন পোশাক পরিধান করুন।"],
  ["weave", "বোনা", "/wiːv/", "Weavers weave magnificent Jamdani sarees.", "তাঁতিরা চমৎকার জামদানি শাড়ি বোনেন।"],
  ["weep", "কান্না করা", "/wiːp/", "Joyful tears made the champion weep.", "আনন্দের অশ্রুতে চ্যাম্পিয়ন কেঁদে ফেলেছিলেন।"],
  ["weigh", "ওজন পরিমাপ করা", "/weɪ/", "Weigh vegetables on accurate digital scales.", "সঠিক ডিজিটাল স্কেলে শাকসবজির ওজন নিন।"],
  ["welcome", "স্বাগত জানানো", "/ˈwɛlkəm/", "Welcome guests with courteous hospitality.", "মার্জিত আতিথেয়তার সাথে অতিথিদের স্বাগত জানান।"],
  ["whisper", "ফিসফিস করে বলা", "/ˈwɪspər/", "Whisper softly inside the library room.", "পাঠাগারের ভেতরে মৃদু স্বরে ফিসফিস করে কথা বলুন।"],
  ["whistle", "বাঁশি বাজানো", "/ˈwɪsl/", "The referee whistled to resume the game.", "রেফারি খেলা পুনরায় শুরুর বাঁশি বাজিয়েছিলেন।"],
  ["win", "জয়লাভ করা", "/wɪn/", "Perseverance helps you win every contest.", "অধ্যবসায় তোমাকে প্রতিটি প্রতিযোগিতায় জিততে সাহায্য করে।"],
  ["wind", "পাকানো / ঘুরানো", "/waɪnd/", "Wind the mechanical clock gently.", "আলতো করে মেকানিক্যাল ঘড়িতে দম দিন।"],
  ["wipe", "মুছে পরিষ্কার করা", "/waɪp/", "Wipe the writing blackboard after class.", "ক্লাসের পর ব্ল্যাকবোর্ডটি মুছে পরিষ্কার করো।"],
  ["wish", "ইচ্ছা পোষণ করা", "/wɪʃ/", "I wish you prosperous academic success.", "আমি তোমার উজ্জ্বল শিক্ষাজীবনের সাফল্য কামনা করি।"],
  ["withdraw", "তুলে নেওয়া / প্রত্যাহার করা", "/wɪðˈdrɔː/", "He withdrew money from the ATM bank.", "তিনি এটিএম ব্যাংক থেকে টাকা তুলেছিলেন।"],
  ["withstand", "প্রতিরোধ করা / টিকে থাকা", "/wɪðˈstænd/", "Mangrove trees withstand severe coastal cyclones.", "ম্যানগ্রোভ গাছ উপকূলীয় তীব্র ঘূর্ণিঝড় প্রতিরোধ করে।"],
  ["witness", "প্রত্যক্ষ করা / সাক্ষী হওয়া", "/ˈwɪtnɪs/", "The stadium witnessed a historic match.", "স্টেডিয়ামটি একটি ঐতিহাসিক ম্যাচের সাক্ষী ছিল।"],
  ["work", "কাজ করা / শ্রম দেওয়া", "/wɜːrk/", "Work diligently to fulfill your dreams.", "তোমার স্বপ্ন পূরণে নিষ্ঠার সাথে কাজ করো।"],
  ["worship", "উপাসনা করা", "/ˈwɜːrʃɪp/", "People worship the Creator in peace.", "মানুষ শান্তির সাথে সৃষ্টিকর্তার উপাসনা করে।"],
  ["wrap", "মোড়ানো", "/ræp/", "Wrap the gift book in colorful recycled paper.", "উপহারের বইটি রঙিন পুনর্ব্যবহৃত কাগজে মুড়িয়ে নিন।"],
  ["write", "লেখা", "/raɪt/", "Write new vocabulary in your exercise book.", "তোমার খাতায় নতুন শব্দভাণ্ডার লিখে রাখো।"],
  ["yawn", "হাই তোলা", "/jɔːn/", "Sleepy students yawned in the afternoon.", "ক্লান্ত শিক্ষার্থীরা বিকেলে হাই তুলছিল।"],
  ["yield", "ফলন দেওয়া / নতি স্বীকার করা", "/jiːld/", "Fertile fields yield bumper rice crops.", "উর্বর জমি প্রচুর ধানের বাম্পার ফলন দেয়।"],
  ["zoom", "দ্রুত চলা / জুম করা", "/zuːm/", "Zoom in to see clear map labels.", "মানচিত্রের স্পষ্ট লেখা দেখতে জুম করুন।"]
];
