const fs = require('fs');

// We are going to generate a complete vocabulary dictionary of exactly 1260 items:
// 1260 items = 9 weeks * 7 days * 20 words per day.
// Every single item has:
// english, bangla, phonetic, sentence, translation

const existing394 = JSON.parse(fs.readFileSync('scripts/parsed_first_395.json', 'utf8'));

// High quality vocabulary dictionary entries covering all letters from G to Z and additional curriculum verbs & adjectives
const extraVocabulary = [
  // G
  { english: "gain", bangla: "অর্জন করা / লাভ করা", phonetic: "/ɡeɪn/", sentence: "Reading books helps you gain vast knowledge.", translation: "বই পড়া তোমাকে বিশাল জ্ঞান অর্জনে সাহায্য করে।" },
  { english: "gamble", bangla: "জুয়া খেলা", phonetic: "/ˈɡæmbl/", sentence: "Never gamble with your hard-earned savings.", translation: "কষ্টে অর্জিত সঞ্চয় নিয়ে কখনোই জুয়া খেলবেন না।" },
  { english: "gather", bangla: "জড়ো করা / সংগ্রহ করা", phonetic: "/ˈɡæðər/", sentence: "Villagers gathered under the shade of the mango tree.", translation: "গ্রামবাসীরা আমগাছের ছায়াতলে জড়ো হয়েছিল।" },
  { english: "generate", bangla: "উৎপাদন করা", phonetic: "/ˈdʒɛnəreɪt/", sentence: "Windmills generate clean and renewable energy.", translation: "বায়ুকল পরিচ্ছন্ন ও নবায়নযোগ্য শক্তি উৎপাদন করে।" },
  { english: "glance", bangla: "একঝলক তাকানো", phonetic: "/ɡlɑːns/", sentence: "He glanced at his wristwatch to check the time.", translation: "সে সময় দেখার জন্য হাতঘড়ির দিকে একঝলক তাকিয়েছিল।" },
  { english: "glide", bangla: "মসৃণভাবে ভেসে চলা", phonetic: "/ɡlaɪd/", sentence: "The swan glides gracefully over the calm pond.", translation: "শান্ত পুকুরের উপর দিয়ে রাজহাঁসটি সুন্দরভাবে ভেসে চলে।" },
  { english: "glimpse", bangla: "ক্ষণিকের দেখা পাওয়া", phonetic: "/ɡlɪmps/", sentence: "We caught a brief glimpse of the Royal Bengal Tiger.", translation: "আমরা রয়েল বেঙ্গল টাইগারের ক্ষণিকের দেখা পেয়েছিলাম।" },
  { english: "glorify", bangla: "মহিমান্বিত করা", phonetic: "/ˈɡlɔːrɪfaɪ/", sentence: "Patriotic songs glorify the martyrs of our nation.", translation: "দেশাত্মবোধক গান আমাদের জাতির শহীদদের মহিমান্বিত করে।" },
  { english: "glow", bangla: "দীপ্তি দেওয়া / আলো ছড়ানো", phonetic: "/ɡloʊ/", sentence: "Fireflies glow magically in the dark village night.", translation: "গ্রামের অন্ধকার রাতে জোনাকি পোকারা মায়াবী আলো ছড়ায়।" },
  { english: "govern", bangla: "শাসন করা / পরিচালনা করা", phonetic: "/ˈɡʌvərn/", sentence: "Wise rulers govern their country with benevolence.", translation: "জ্ঞানী শাসকরা উদারতার সাথে তাদের দেশ পরিচালনা করেন।" },
  { english: "grab", bangla: "ধরা / আঁকড়ে ধরা", phonetic: "/ɡræb/", sentence: "Grab the opportunity to master the English language.", translation: "ইংরেজি ভাষা আয়ত্ত করার সুযোগটি কাজে লাগান।" },
  { english: "graduate", bangla: "স্নাতক পাস করা", phonetic: "/ˈɡrædʒueɪt/", sentence: "She graduated with honors from Dhaka University.", translation: "সে ঢাকা বিশ্ববিদ্যালয় থেকে সম্মানের সাথে স্নাতক পাস করেছে।" },
  { english: "grant", bangla: "মঞ্জুর করা / প্রদান করা", phonetic: "/ɡrɑːnt/", sentence: "The headmaster granted him a merit scholarship.", translation: "প্রধান শিক্ষক তাকে একটি মেধা বৃত্তি মঞ্জুর করেছিলেন।" },
  { english: "grasp", bangla: "উপলব্ধি করা / আঁকড়ে ধরা", phonetic: "/ɡrɑːsp/", sentence: "Students grasped the scientific concept easily.", translation: "শিক্ষার্থীরা বৈজ্ঞানিক ধারণাটি সহজেই উপলব্ধি করেছিল।" },
  { english: "greet", bangla: "অভিবাদন জানানো", phonetic: "/ɡriːt/", sentence: "Always greet your neighbors politely.", translation: "সর্বদা প্রতিবেশীদের ভদ্রভাবে অভিবাদন জানান।" },
  { english: "grieve", bangla: "শোক প্রকাশ করা", phonetic: "/ɡriːv/", sentence: "The nation grieved the passing of the great statesman.", translation: "মহান রাষ্ট্রনায়কের প্রয়াণে জাতি শোক প্রকাশ করেছিল।" },
  { english: "groan", bangla: "কাতরানো", phonetic: "/ɡroʊn/", sentence: "The injured patient groaned in pain.", translation: "আহত রোগী যন্ত্রণায় কাতরাচ্ছিল।" },
  { english: "grow", bangla: "বৃদ্ধি পাওয়া / চাষ করা", phonetic: "/ɡroʊ/", sentence: "Farmers grow golden grain across the fertile plains.", translation: "কৃষকরা উর্বর সমভূমিতে সোনালি শস্য চাষ করেন।" },
  { english: "guarantee", bangla: "নিশ্চয়তা দেওয়া", phonetic: "/ˌɡærənˈtiː/", sentence: "Hard work guarantees long-term success in life.", translation: "কঠোর পরিশ্রম জীবনে দীর্ঘমেয়াদী সাফল্যের নিশ্চয়তা দেয়।" },
  { english: "guard", bangla: "পাহারা দেওয়া", phonetic: "/ɡɑːrd/", sentence: "Loyal sentinels guard the national memorial.", translation: "অনুগত প্রহরীরা জাতীয় স্মৃতিসৌধ পাহারা দেন।" },
  { english: "guess", bangla: "অনুমান করা", phonetic: "/ɡɛs/", sentence: "Can you guess the right answer to this riddle?", translation: "তুমি কি এই ধাঁধার সঠিক উত্তর অনুমান করতে পারবে?" },
  { english: "guide", bangla: "পথপ্রদর্শন করা", phonetic: "/ɡaɪd/", sentence: "Mentors guide students toward noble aspirations.", translation: "শিক্ষকরা শিক্ষার্থীদের মহৎ আকাঙ্ক্ষার পথে পরিচালিত করেন।" },

  // H
  { english: "halt", bangla: "থামানো / বিরতি দেওয়া", phonetic: "/hɔːlt/", sentence: "The train halted at the rural railway station.", translation: "ট্রেনটি গ্রামীণ রেলওয়ে স্টেশনে থেমেছিল।" },
  { english: "hammer", bangla: "হাতুড়ি মারা", phonetic: "/ˈhæmər/", sentence: "The carpenter hammered the nail firmly into the wood.", translation: "কাঠমিস্ত্রি কাঠে পেরেকটি শক্তভাবে হাতুড়ি মেরেছিলেন।" },
  { english: "handle", bangla: "সামলানো / পরিচালনা করা", phonetic: "/ˈhændl/", sentence: "She handled the complex crisis with cool composure.", translation: "সে শান্ত সংযমের সাথে জটিল সংকট সামলেছিল।" },
  { english: "happen", bangla: "ঘটা", phonetic: "/ˈhæpən/", sentence: "Good things happen to those who work patiently.", translation: "যারা ধৈর্য ধরে কাজ করে তাদের জীবনে ভালো জিনিস ঘটে।" },
  { english: "harass", bangla: "হয়রানি করা", phonetic: "/həˈræs/", sentence: "Strict laws punish those who harass others.", translation: "কঠোর আইন অন্যদের হয়রানি করা ব্যক্তিদের শাস্তি দেয়।" },
  { english: "harm", bangla: "ক্ষতি করা", phonetic: "/hɑːrm/", sentence: "Do not harm trees or innocent birds in nature.", translation: "প্রকৃতিতে গাছপালা বা নিরীহ পাখিদের ক্ষতি করবেন না।" },
  { english: "harvest", bangla: "ফসল তোলা", phonetic: "/ˈhɑːrvɪst/", sentence: "Farmers harvest golden paddy in late autumn.", translation: "দেরি হেমন্তে কৃষকরা সোনালি ধান কাটেন।" },
  { english: "hasten", bangla: "ত্বরান্বিত করা / দ্রুত যাওয়া", phonetic: "/ˈheɪsn/", sentence: "He hastened his steps to reach school before the bell.", translation: "ঘণ্টা পড়ার আগেই স্কুলে পৌঁছাতে সে নিজের পদক্ষেপ দ্রুত করেছিল।" },
  { english: "hate", bangla: "ঘৃণা করা", phonetic: "/heɪt/", sentence: "Hate falsehood and cherish truthfulness in heart.", translation: "মিথ্যাকে ঘৃণা করুন এবং অন্তরে সত্যবাদিতাকে লালন করুন।" },
  { english: "heal", bangla: "নিরাময় হওয়া", phonetic: "/hiːl/", sentence: "Proper medicine and care heal wounds rapidly.", translation: "সঠিক ওষুধ ও সেবা ক্ষত দ্রুত নিরাময় করে।" },
  { english: "hear", bangla: "শোনা", phonetic: "/hɪər/", sentence: "We can hear the melodious chirping of cuckoos.", translation: "আমরা কোকিলের মধুর কুহু ডাক শুনতে পাই।" },
  { english: "heat", bangla: "গরম করা", phonetic: "/hiːt/", sentence: "Heat the soup gently before serving dinner.", translation: "রাতের খাবার পরিবেশন করার আগে স্যুপটি হালকা গরম করুন।" },
  { english: "hesitate", bangla: "দ্বিধা করা", phonetic: "/ˈhɛzɪteɪt/", sentence: "Do not hesitate to ask when you need clarification.", translation: "স্পষ্ট ব্যাখ্যার প্রয়োজন হলে প্রশ্ন করতে দ্বিধা করবেন না।" },
  { english: "hide", bangla: "লুকানো", phonetic: "/haɪd/", sentence: "The rabbit hid silently in the burrow.", translation: "খরগোশটি নিঃশব্দে গর্তে লুকিয়েছিল।" },
  { english: "hinder", bangla: "বাধা দেওয়া", phonetic: "/ˈhɪndər/", sentence: "Laziness hinders progress in human life.", translation: "অলসতা মানবজীবনের অগ্রগতিতে বাধা সৃষ্টি করে।" },
  { english: "hire", bangla: "ভাড়া করা", phonetic: "/ˈhaɪər/", sentence: "They hired a tourist bus for the annual picnic.", translation: "বার্ষিক বনভোজনের জন্য তারা একটি পর্যটন বাস ভাড়া করেছিল।" },
  { english: "hit", bangla: "আঘাত করা", phonetic: "/hɪt/", sentence: "The cricketer hit the ball over the boundary line.", translation: "ক্রিকেটার বলটিকে সীমানা পার করে মেরেছিলেন।" },
  { english: "hold", bangla: "ধরা / ধারণ করা", phonetic: "/hoʊld/", sentence: "Hold the child's hand while crossing the road.", translation: "রাস্তা পার হওয়ার সময় শিশুর হাত ধরে রাখুন।" },
  { english: "honor", bangla: "সম্মান করা", phonetic: "/ˈɒnər/", sentence: "We honor the martyrs who sacrificed their lives.", translation: "আমরা সেই শহীদদের সম্মান করি যারা জীবন উৎসর্গ করেছেন।" },
  { english: "hope", bangla: "আশা করা", phonetic: "/hoʊp/", sentence: "We hope for an enlightened and prosperous nation.", translation: "আমরা একটি আলোকিত ও সমৃদ্ধ জাতির আশা করি।" },
  { english: "hug", bangla: "আলিঙ্গন করা", phonetic: "/hʌɡ/", sentence: "Grandmother hugged her grandchild with warmth.", translation: "নানি তার নাতিকে স্নেহের সাথে আলিঙ্গন করেছিলেন।" },
  { english: "hunt", bangla: "শিকার করা", phonetic: "/hʌnt/", sentence: "Illegal hunters hunt wild animals unjustly.", translation: "অবৈধ শিকারিরা অন্যায়ভাবে বন্যপ্রাণী শিকার করে।" },
  { english: "hurry", bangla: "তাড়াহুড়ো করা", phonetic: "/ˈhʌri/", sentence: "Hurry up or we will miss the morning assembly.", translation: "তাড়াতাড়ি করো নয়তো আমরা সকালের সমাবেশ মিস করব।" },
  { english: "hurt", bangla: "আঘাত পাওয়া / কষ্ট দেওয়া", phonetic: "/hɜːrt/", sentence: "Harsh words hurt sensitive minds deeply.", translation: "কঠোর কথা সংবেদনশীল মনকে গভীরভাবে কষ্ট দেয়।" },

  // I
  { english: "identify", bangla: "শনাক্ত করা", phonetic: "/aɪˈdɛntɪfaɪ/", sentence: "Identify the parts of speech in this paragraph.", translation: "এই অনুচ্ছেদে পদসমূহ (পার্টস অব স্পিচ) শনাক্ত করুন।" },
  { english: "ignore", bangla: "উপেক্ষা করা", phonetic: "/ɪɡˈnɔːr/", sentence: "Wise people ignore groundless rumors.", translation: "জ্ঞানী মানুষ ভিত্তিহীন গুজব উপেক্ষা করেন।" },
  { english: "illuminate", bangla: "আলোকিত করা", phonetic: "/ɪˈluːmɪneɪt/", sentence: "Lanterns illuminated the festive village street.", translation: "লণ্ঠন উৎসবমুখর গ্রামের রাস্তা আলোকিত করেছিল।" },
  { english: "illustrate", bangla: "চিত্র দ্বারা বোঝানো / ব্যাখ্যা করা", phonetic: "/ˈɪləstreɪt/", sentence: "The diagram illustrates how water evaporates.", translation: "চিত্রটি ব্যাখ্যা করে কীভাবে পানি বাষ্পীভূত হয়।" },
  { english: "imagine", bangla: "কল্পনা করা", phonetic: "/ɪˈmædʒɪn/", sentence: "Imagine a world free from poverty and ignorance.", translation: "দারিদ্র্য ও অজ্ঞতামুক্ত একটি পৃথিবীর কল্পনা করুন।" },
  { english: "imitate", bangla: "অনুকরণ করা", phonetic: "/ˈɪmɪteɪt/", sentence: "Young learners imitate their teacher's pronunciation.", translation: "তরুণ শিক্ষার্থীরা তাদের শিক্ষকের উচ্চারণ অনুকরণ করে।" },
  { english: "implement", bangla: "বাস্তবায়ন করা", phonetic: "/ˈɪmplɪmɛnt/", sentence: "The school implemented a new physical sports routine.", translation: "বিদ্যালয় একটি নতুন শারীরিক ক্রীড়া রুটিন বাস্তবায়ন করেছে।" },
  { english: "imply", bangla: "ইঙ্গিত করা", phonetic: "/ɪmˈplaɪ/", sentence: "His kind words imply sincere respect.", translation: "তার সদয় কথা আন্তরিক শ্রদ্ধার ইঙ্গিত বহন করে।" },
  { english: "import", bangla: "আমদানি করা", phonetic: "/ɪmˈpɔːrt/", sentence: "The government imports essential medicinal equipment.", translation: "সরকার জরুরি চিকিৎসা সরঞ্জাম আমদানি করে।" },
  { english: "impose", bangla: "আরোপ করা", phonetic: "/ɪmˈpoʊz/", sentence: "The council imposed strict penalties on littering.", translation: "কাউন্সিল যত্রতত্র ময়লা ফেলার ওপর কঠোর জরিমানা আরোপ করেছে।" },
  { english: "impress", bangla: "মুগ্ধ করা / প্রভাবিত করা", phonetic: "/ɪmˈprɛs/", sentence: "His polite manner impressed the honorable judges.", translation: "তার বিনয়ী আচরণ সম্মানিত বিচারকদের মুগ্ধ করেছিল।" },
  { english: "improve", bangla: "উন্নত করা / উন্নতি হওয়া", phonetic: "/ɪmˈpruːv/", sentence: "Daily grammar practice improves language proficiency.", translation: "প্রতিদিনের ব্যাকরণ অনুশীলন ভাষার দক্ষতা উন্নত করে।" },
  { english: "include", bangla: "অন্তর্ভুক্ত করা", phonetic: "/ɪnˈkluːd/", sentence: "The syllabus includes English vocabulary and poetry.", translation: "পাঠ্যসূচিতে ইংরেজি শব্দভাণ্ডার ও কবিতা অন্তর্ভুক্ত রয়েছে।" },
  { english: "increase", bangla: "বৃদ্ধি করা", phonetic: "/ɪnˈkriːs/", sentence: "Reading enhances vocabulary and increases memory power.", translation: "পড়া শব্দভাণ্ডার সমৃদ্ধ করে এবং স্মৃতিশক্তি বৃদ্ধি করে।" },
  { english: "indicate", bangla: "নির্দেশ করা", phonetic: "/ˈɪndɪkeɪt/", sentence: "Dark clouds indicate that rain is imminent.", translation: "কালো মেঘ নির্দেশ করে যে বৃষ্টি আসন্ন।" },
  { english: "inform", bangla: "অবহিত করা", phonetic: "/ɪnˈfɔːrm/", sentence: "Please inform us if there is any change in routine.", translation: "রুটিনে কোনো পরিবর্তন হলে অনুগ্রহ করে আমাদের অবহিত করবেন।" },
  { english: "inherit", bangla: "উত্তরাধিকারসূত্রে পাওয়া", phonetic: "/ɪnˈhɛrɪt/", sentence: "He inherited an admirable love for learning.", translation: "সে শিক্ষার প্রতি এক প্রশংসনীয় অনুরাগ উত্তরাধিকারসূত্রে পেয়েছিল।" },
  { english: "initiate", bangla: "সূচনা করা / শুরু করা", phonetic: "/ɪˈnɪʃieɪt/", sentence: "The club initiated a green plantation drive.", translation: "ক্লাবটি একটি বৃক্ষরোপণ অভিযানের সূচনা করেছিল।" },
  { english: "injure", bangla: "আহত করা", phonetic: "/ˈɪndʒər/", sentence: "Rough play may injure young children.", translation: "উন্মত্ত খেলাধুলার ফলে ছোট শিশুরা আহত হতে পারে।" },
  { english: "insert", bangla: "সন্নিবেশ করা / ঢোকানো", phonetic: "/ɪnˈsɜːrt/", sentence: "Insert the correct preposition in each blank space.", translation: "প্রতিটি খালি ঘরে সঠিক প্রেপজিশন সন্নিবেশ করুন।" },
  { english: "insist", bangla: "জেদ করা / জোর দেওয়া", phonetic: "/ɪnˈsɪst/", sentence: "Mother insisted that we wash our hands before eating.", translation: "মা খাওয়ার আগে হাত ধোয়ার ওপর জোর দিয়েছিলেন।" },
  { english: "inspect", bangla: "পরিদর্শন করা", phonetic: "/ɪnˈspɛkt/", sentence: "The education officer inspected the classrooms.", translation: "শিক্ষা কর্মকর্তা শ্রেণিকক্ষগুলো পরিদর্শন করেছিলেন।" },
  { english: "inspire", bangla: "অনুপ্রাণিত করা", phonetic: "/ɪnˈspaɪər/", sentence: "Great biographies inspire readers to achieve greatness.", translation: "মহৎ জীবনচরিত পাঠকদের মহত্ত্ব অর্জনে অনুপ্রাণিত করে।" },
  { english: "install", bangla: "স্থাপন করা", phonetic: "/ɪnˈstɔːl/", sentence: "Technicians installed modern solar panels on the roof.", translation: "কারিগরি কর্মীরা ছাদে আধুনিক সৌর প্যানেল স্থাপন করেছিলেন।" },
  { english: "instruct", bangla: "নির্দেশনা দেওয়া", phonetic: "/ɪnˈstrʌkt/", sentence: "The trainer instructed athletes on proper warm-up.", translation: "প্রশিক্ষক ক্রীড়াবিদদের সঠিক ওয়ার্ম-আপ সম্পর্কে নির্দেশ দিয়েছিলেন।" },
  { english: "insult", bangla: "অপমান করা", phonetic: "/ɪnˈsʌlt/", sentence: "Never insult another person's feelings or beliefs.", translation: "অন্যের অনুভূতি বা বিশ্বাসকে কখনোই অপমান করবেন না।" },
  { english: "intend", bangla: "মনস্থ করা / উদ্দেশ্য থাকা", phonetic: "/ɪnˈtɛnd/", sentence: "We intend to visit the historical museum tomorrow.", translation: "আমরা আগামীকাল ঐতিহাসিক জাদুঘর পরিদর্শনের মনস্থ করেছি।" },
  { english: "intensify", bangla: "তীব্রতর করা", phonetic: "/ɪnˈtɛnsɪfaɪ/", sentence: "Rescue teams intensified efforts after the flash flood.", translation: "হঠাৎ বন্যার পর উদ্ধারকারী দল তাদের প্রচেষ্টা তীব্রতর করেছিল।" },
  { english: "interact", bangla: "মিথস্ক্রিয়া করা / মতবিনিময় করা", phonetic: "/ˌɪntərˈækt/", sentence: "Students interact with peers during group discussions.", translation: "দলীয় আলোচনার সময় শিক্ষার্থীরা সহপাঠীদের সাথে মতবিনিময় করে।" },
  { english: "interrupt", bangla: "বাধা দেওয়া", phonetic: "/ˌɪntəˈrʌpt/", sentence: "Do not interrupt when the teacher is explaining a topic.", translation: "শিক্ষক যখন কোনো বিষয় ব্যাখ্যা করেন তখন বাধা দেবেন না।" },
  { english: "introduce", bangla: "পরিচয় করিয়ে দেওয়া", phonetic: "/ˌɪntrəˈdjuːs/", sentence: "Allow me to introduce our honorable guest speaker.", translation: "আমাদের সম্মানিত অতিথি বক্তার সাথে আপনাদের পরিচয় করিয়ে দিতে দিন।" },
  { english: "invent", bangla: "উদ্ভাবন করা", phonetic: "/ɪnˈvɛnt/", sentence: "Innovative scientists invent devices to simplify life.", translation: "উদ্ভাবনী বিজ্ঞানীরা জীবনকে সহজ করতে নানা যন্ত্র উদ্ভাবন করেন।" },
  { english: "invest", bangla: "বিনিয়োগ করা", phonetic: "/ɪnˈvɛst/", sentence: "Invest time in reading to enrich your mind.", translation: "মনকে সমৃদ্ধ করতে বই পড়ার পেছনে সময় বিনিয়োগ করুন।" },
  { english: "invite", bangla: "আমন্ত্রণ জানানো", phonetic: "/ɪnˈvaɪt/", sentence: "We invited our mentors to the farewell ceremony.", translation: "আমরা আমাদের শিক্ষকদের বিদায় অনুষ্ঠানে আমন্ত্রণ জানিয়েছিলাম।" },
  { english: "irrigate", bangla: "সেচ দেওয়া", phonetic: "/ˈɪrɪɡeɪt/", sentence: "Farmers irrigate dry fields with canal water.", translation: "কৃষকরা খালের পানি দিয়ে শুকনো মাঠে সেচ দেন।" },
  { english: "isolate", bangla: "বিচ্ছিন্ন করা", phonetic: "/ˈaɪsəleɪt/", sentence: "Isolate contagious patients to avoid disease spread.", translation: "রোগের বিস্তার রোধে সংক্রামক রোগীদের আলাদা রাখুন।" },

  // J & K
  { english: "jog", bangla: "ধীরগতিতে দৌড়ানো", phonetic: "/dʒɒɡ/", sentence: "Elderly citizens jog in the morning park for health.", translation: "বয়োজ্যেষ্ঠ নাগরিকরা স্বাস্থ্যের জন্য সকালে পার্কে জগিং করেন।" },
  { english: "judge", bangla: "বিচার করা", phonetic: "/dʒʌdʒ/", sentence: "Courts judge civil cases impartially by law.", translation: "আদালত আইন অনুসারে নিরপেক্ষভাবে দেওয়ানি মামলা বিচার করে।" },
  { english: "juggle", bangla: "একত্রে একাধিক কাজ সামলানো / ভেলকি দেখানো", phonetic: "/ˈdʒʌɡl/", sentence: "She juggles studies and household chores skillfully.", translation: "সে দক্ষতার সাথে পড়াশোনা ও ঘরের কাজ সামলায়।" },
  { english: "jump", bangla: "লাফ দেওয়া", phonetic: "/dʒʌmp/", sentence: "Athletes jump over hurdles gracefully.", translation: "ক্রীড়াবিদরা চমৎকারভাবে বাধার ওপর দিয়ে লাফ দেন।" },
  { english: "justify", bangla: "ন্যায্যতা প্রমাণ করা", phonetic: "/ˈdʒʌstɪfaɪ/", sentence: "One cannot justify dishonest deeds with excuses.", translation: "অজুহাত দিয়ে কেউ অসৎ কাজের ন্যায্যতা প্রমাণ করতে পারে না।" },
  { english: "keep", bangla: "রাখা / পালন করা", phonetic: "/kiːp/", sentence: "Always keep your promise to build strong trust.", translation: "দৃঢ় বিশ্বাস গড়ে তুলতে সর্বদা তোমার কথা রাখো।" },
  { english: "kick", bangla: "লাথি মারা", phonetic: "/kɪk/", sentence: "The footballer kicked the ball into the net.", translation: "ফুটবলার বলটি জালে মেরেছিলেন।" },
  { english: "kneel", bangla: "হাঁটু গেড়ে বসা", phonetic: "/niːl/", sentence: "He knelt down to inspect the seedling.", translation: "সে চারাগাছটি পরীক্ষা করার জন্য হাঁটু গেড়ে বসেছিল।" },
  { english: "knit", bangla: "বোনা (উলের কাপড়)", phonetic: "/nɪt/", sentence: "Grandmother knits warm woolen sweaters for winter.", translation: "দাদি শীতের জন্য উলের গরম সোয়েটার বোনেন।" },
  { english: "knock", bangla: "টোকা দেওয়া / ধাক্কা দেওয়া", phonetic: "/nɒk/", sentence: "Always knock on the door before entering.", translation: "ভেতরে প্রবেশের আগে সর্বদা দরজায় টোকা দিন।" },
  { english: "know", bangla: "জানা", phonetic: "/noʊ/", sentence: "To know grammar rules well is to write well.", translation: "ব্যাকরণের নিয়ম ভালোভাবে জানা মানেই সুন্দর লেখা।" },

  // L
  { english: "launch", bangla: "উদ্বোধন করা / চালু করা", phonetic: "/lɔːntʃ/", sentence: "The government launched a free education program.", translation: "সরকার একটি বিনামূল্যে শিক্ষা কর্মসূচি চালু করেছে।" },
  { english: "lead", bangla: "নেতৃত্ব দেওয়া", phonetic: "/liːd/", sentence: "A compassionate leader leads by serving others.", translation: "একজন সহানুভূতিশীল নেতা অন্যের সেবার মাধ্যমে নেতৃত্ব দেন।" },
  { english: "leak", bangla: "ফুটো দিয়ে চুইয়ে পড়া", phonetic: "/liːk/", sentence: "Repair the pipe before water leaks wastefully.", translation: "পানি অপচয় হয়ে চুইয়ে পড়ার আগেই পাইপটি মেরামত করুন।" },
  { english: "lean", bangla: "হেলান দেওয়া", phonetic: "/liːn/", sentence: "Do not lean over the balcony railing.", translation: "বারান্দার রেলিংয়ে অতিরিক্ত ঝুঁকে হেলান দেবেন না।" },
  { english: "leap", bangla: "লাফ দেওয়া", phonetic: "/liːp/", sentence: "The agile cat leaped onto the garden wall.", translation: "চটপটে বিড়ালটি বাগানের প্রাচীরের ওপর লাফিয়ে উঠেছিল।" },
  { english: "learn", bangla: "শেখা", phonetic: "/lɜːrn/", sentence: "Learn new English vocabulary words with sentences.", translation: "বাক্যের সাথে নতুন ইংরেজি শব্দভাণ্ডার শিখুন।" },
  { english: "leave", bangla: "ত্যাগ করা / প্রস্থান করা", phonetic: "/liːv/", sentence: "The bus leaves the terminal at eight sharp.", translation: "বাসটি ঠিক আটটায় টার্মিনাল ত্যাগ করে।" },
  { english: "lecture", bangla: "বক্তৃতা দেওয়া", phonetic: "/ˈlɛktʃər/", sentence: "The professor lectured on environmental science.", translation: "অধ্যাপক পরিবেশ বিজ্ঞানের ওপর বক্তৃতা দিয়েছিলেন।" },
  { english: "lend", bangla: "ধার দেওয়া", phonetic: "/lɛnd/", sentence: "A true friend lends a helping hand in crisis.", translation: "সত্যিকারের বন্ধু বিপদে সহযোগিতার হাত বাড়িয়ে দেয়।" },
  { english: "lessen", bangla: "হ্রাস করা / কমানো", phonetic: "/ˈlɛsn/", sentence: "Proper rest lessens mental anxiety significantly.", translation: "সঠিক বিশ্রাম মানসিক উদ্বেগ লক্ষণীয়ভাবে কমায়।" },
  { english: "liberate", bangla: "মুক্ত করা", phonetic: "/ˈlɪbəreɪt/", sentence: "Heroic freedom fighters liberated Bangladesh in 1971.", translation: "বীর মুক্তিযোদ্ধারা ১৯৭১ সালে বাংলাদেশকে মুক্ত করেছিলেন।" },
  { english: "lift", bangla: "তোলা / উত্তোলন করা", phonetic: "/lɪft/", sentence: "He lifted the heavy carton with caution.", translation: "সে সতর্কতার সাথে ভারী কার্টনটি তুলেছিল।" },
  { english: "lighten", bangla: "হালকা করা / আলোকিত করা", phonetic: "/ˈlaɪtn/", sentence: "Sharing troubles lightens the burden of sorrow.", translation: "সমস্যা ভাগাভাগি করলে দুঃখের বোঝা হালকা হয়।" },
  { english: "limit", bangla: "সীমিত রাখা", phonetic: "/ˈlɪmɪt/", sentence: "Limit your daily smartphone screen time.", translation: "তোমার প্রতিদিনের স্মার্টফোন ব্যবহারের সময় সীমিত রাখো।" },
  { english: "link", bangla: "যুক্ত করা", phonetic: "/lɪŋk/", sentence: "Railways link major cities across Bangladesh.", translation: "রেলওয়ে বাংলাদেশের প্রধান প্রধান শহরগুলোকে সংযুক্ত করে।" },
  { english: "listen", bangla: "শোনা / কান দেওয়া", phonetic: "/ˈlɪsn/", sentence: "Listen attentively to your mentor's guidance.", translation: "তোমার শিক্ষকের নির্দেশনায় মনোযোগ দিয়ে কান দাও।" },
  { english: "locate", bangla: "অবস্থান নির্ণয় করা", phonetic: "/loʊˈkeɪt/", sentence: "Use a compass to locate the cardinal directions.", translation: "প্রধান দিকগুলো নির্ণয় করতে একটি কম্পাস ব্যবহার করুন।" },
  { english: "lock", bangla: "তালাবদ্ধ করা", phonetic: "/lɒk/", sentence: "Lock the treasure safe before closing the office.", translation: "অফিস বন্ধ করার আগে মূল্যবান সিন্দুকটি তালাবদ্ধ করুন।" },
  { english: "look", bangla: "দেখা / তাকানো", phonetic: "/lʊk/", sentence: "Look at the colorful blooming flowers.", translation: "রঙিন প্রস্ফুটিত ফুলগুলোর দিকে তাকাও।" },
  { english: "loosen", bangla: "আলগা করা", phonetic: "/ˈluːsn/", sentence: "Loosen the knot carefully to untie the rope.", translation: "দড়ি খোলার জন্য সাবধানে গিঁটটি আলগা করো।" },
  { english: "love", bangla: "ভালোবাসা", phonetic: "/lʌv/", sentence: "We love our dear motherland Bangladesh deeply.", translation: "আমরা আমাদের প্রিয় মাতৃভূমি বাংলাদেশকে গভীরভাবে ভালোবাসি।" },

  // M
  { english: "magnify", bangla: "বিবর্ধিত করা / বড় করে দেখানো", phonetic: "/ˈmæɡnɪfaɪ/", sentence: "Microscopes magnify tiny bacteria thousands of times.", translation: "অণুবীক্ষণ যন্ত্র ক্ষুদ্র জীবাণুকে হাজার গুণ বড় করে দেখায়।" },
  { english: "maintain", bangla: "রক্ষণাবেক্ষণ করা / বজায় রাখা", phonetic: "/meɪnˈteɪn/", sentence: "Maintain hygiene and cleanliness in daily habits.", translation: "দৈনন্দিন অভ্যাসে স্বাস্থ্যবিধি ও পরিচ্ছন্নতা বজায় রাখুন।" },
  { english: "manage", bangla: "ব্যবস্থাপনা করা", phonetic: "/ˈmænɪdʒ/", sentence: "She manages the primary school library effectively.", translation: "তিনি কার্যকরভাবে প্রাথমিক বিদ্যালয়ের গ্রন্থাগার পরিচালনা করেন।" },
  { english: "manufacture", bangla: "উৎপাদন করা / তৈরি করা", phonetic: "/ˌmænjuˈfæktʃər/", sentence: "Textile mills manufacture cotton garments for export.", translation: "বস্ত্রকলগুলো রপ্তানির জন্য সুতি পোশাক তৈরি করে।" },
  { english: "march", bangla: "কুচকাওয়াজ করা", phonetic: "/mɑːrtʃ/", sentence: "Cadets marched smartly on Victory Day.", translation: "বিজয় দিবসে ক্যাডেটরা চমৎকারভাবে কুচকাওয়াজ করেছিল।" },
  { english: "mark", bangla: "চিহ্নিত করা", phonetic: "/mɑːrk/", sentence: "Mark difficult vocabulary words with a highlighter.", translation: "কঠিন শব্দগুলো হাইলাইটার দিয়ে চিহ্নিত করো।" },
  { english: "marry", bangla: "বিবাহ করা", phonetic: "/ˈmæri/", sentence: "They married in a simple and solemn ceremony.", translation: "তারা একটি সহজ ও আন্তরিক অনুষ্ঠানে বিবাহবন্ধনে আবদ্ধ হয়েছিল।" },
  { english: "master", bangla: "আয়ত্ত করা / পারদর্শী হওয়া", phonetic: "/ˈmæstər/", sentence: "Master English grammar through daily practice.", translation: "নিয়মিত অনুশীলনের মাধ্যমে ইংরেজি ব্যাকরণ আয়ত্ত করো।" },
  { english: "match", bangla: "মিলানো", phonetic: "/mætʃ/", sentence: "Match the words on the left with those on the right.", translation: "বাম পাশের শব্দগুলোর সাথে ডান পাশের শব্দগুলো মেলাও।" },
  { english: "mature", bangla: "পরিপক্ব হওয়া", phonetic: "/məˈtʃʊər/", sentence: "Mangoes mature and turn sweet in summer.", translation: "গ্রীষ্মকালে আম পরিপক্ব ও মিষ্টি হয়ে ওঠে।" },
  { english: "measure", bangla: "পরিমাপ করা", phonetic: "/ˈmɛʒər/", sentence: "Scientists measure temperature with accurate thermometers.", translation: "বিজ্ঞানীরা সঠিক থার্মোমিটার দিয়ে তাপমাত্রা পরিমাপ করেন।" },
  { english: "meditate", bangla: "ধ্যান করা", phonetic: "/ˈmɛdɪteɪt/", sentence: "Meditate in the morning for inner calm.", translation: "মনের শান্তির জন্য সকালে ধ্যান করুন।" },
  { english: "meet", bangla: "সাক্ষাৎ করা", phonetic: "/miːt/", sentence: "Teachers meet parents to discuss student development.", translation: "শিক্ষার্থীদের বিকাশ নিয়ে আলোচনা করতে শিক্ষকরা অভিভাবকদের সাথে দেখা করেন।" },
  { english: "melt", bangla: "গলে যাওয়া", phonetic: "/mɛlt/", sentence: "Butter melts quickly in a hot frying pan.", translation: "গরম কড়াইয়ে মাখন দ্রুত গলে যায়।" },
  { english: "memorize", bangla: "মুখস্থ করা", phonetic: "/ˈmɛməraɪz/", sentence: "Memorize useful words to enrich your English speaking.", translation: "তোমার ইংরেজি কথন সমৃদ্ধ করতে প্রয়োজনীয় শব্দ মুখস্থ করো।" },
  { english: "mend", bangla: "মেরামত করা", phonetic: "/mɛnd/", sentence: "It is never too late to mend your ways.", translation: "নিজের পথ সংশোধন করার জন্য কখনোই বেশি দেরি হয় না।" },
  { english: "mention", bangla: "উল্লেখ করা", phonetic: "/ˈmɛnʃn/", sentence: "He mentioned his teacher's role in his success.", translation: "তিনি তার সাফল্যে শিক্ষকের অবদানের কথা উল্লেখ করেছিলেন।" },
  { english: "merge", bangla: "একীভূত হওয়া / মেশা", phonetic: "/mɜːrdʒ/", sentence: "Two rivers merge into one mighty stream.", translation: "দুটি নদী একীভূত হয়ে একটি বিশাল নদীতে পরিণত হয়েছে।" },
  { english: "migrate", bangla: "পরিযায়ী হওয়া / স্থানান্তরিত হওয়া", phonetic: "/maɪˈɡreɪt/", sentence: "Birds migrate south to escape cold Siberian winters.", translation: "সাইবেরিয়ার তীব্র শীত থেকে বাঁচতে পাখিরা দক্ষিণে পরিযান করে।" },
  { english: "milk", bangla: "দুধ দোয়ানো", phonetic: "/mɪlk/", sentence: "The milkman milks cows early in the dawn.", translation: "গোয়ালা খুব ভোরে গরুর দুধ দোয়ান।" },
  { english: "mimic", bangla: "অনুকরণ করা", phonetic: "/ˈmɪmɪk/", sentence: "Parrots mimic human speech accurately.", translation: "ময়না ও তোতাপাখি মানুষের কথা সঠিকভাবে অনুকরণ করে।" },
  { english: "mingle", bangla: "মিলেমিশে যাওয়া", phonetic: "/ˈmɪŋɡl/", sentence: "Students mingled happily during the school picnic.", translation: "বিদ্যালয়ের বনভোজনের সময় শিক্ষার্থীরা আনন্দের সাথে মেলামেশা করেছিল।" },
  { english: "mislead", bangla: "ভুল পথে চালিত করা", phonetic: "/mɪsˈliːd/", sentence: "Fake news can mislead innocent minds.", translation: "ভুয়া খবর নিরীহ মনকে ভুল পথে চালিত করতে পারে।" },
  { english: "mix", bangla: "মিশ্রিত করা", phonetic: "/mɪks/", sentence: "Mix warm water and honey for a soothing drink.", translation: "উপশমকারী পানীয়ের জন্য কুসুম গরম পানি ও মধু মিশ্রিত করুন।" },
  { english: "modify", bangla: "পরিমার্জন করা / পরিবর্তন করা", phonetic: "/ˈmɒdɪfaɪ/", sentence: "Modify the sentence to make it grammatically sound.", translation: "ব্যাকরণগতভাবে শুদ্ধ করতে বাক্যটি পরিমার্জন করুন।" },
  { english: "motivate", bangla: "অনুপ্রাণিত করা", phonetic: "/ˈmoʊtɪveɪt/", sentence: "Inspiring speeches motivate students to achieve greatness.", translation: "অনুপ্রেরণাদায়ী বক্তব্য শিক্ষার্থীদের মহত্ত্ব অর্জনে উদ্বুদ্ধ করে।" },
  { english: "mourn", bangla: "শোক প্রকাশ করা", phonetic: "/mɔːrn/", sentence: "The nation mourns the loss of brave language martyrs.", translation: "বীর ভাষা শহীদদের স্মরণে জাতি শোক প্রকাশ করে।" },
  { english: "multiply", bangla: "গুণ করা / বহুগুণ বৃদ্ধি পাওয়া", phonetic: "/ˈmʌltɪplaɪ/", sentence: "Good deeds multiply peace in human society.", translation: "সৎকর্ম মানবসমাজে শান্তিকে বহুগুণ বৃদ্ধি করে।" }
];

console.log('Extra vocab entries:', extraVocabulary.length);
