const fs = require('fs');

// We have 394 items in parsed_first_395.json.
// To reach 1260 items (9 weeks * 7 days * 20 words = 1260 items), we need 1260 - 394 = 866 more items.
// Let's create an exhaustive, rich collection of authentic educational verbs and adjectives
// with phonetics, Bangla meanings, English sentences, and Bengali translations.

const first394 = JSON.parse(fs.readFileSync('scripts/parsed_first_395.json', 'utf8'));

// Verify no duplicates in new additions
const existingEnglish = new Set(first394.map(item => item.english.toLowerCase()));

// Next batch: 450 comprehensive everyday, academic, educational, and professional action verbs
const verbsBatch = [
  // A
  { english: "absorb", bangla: "শোষণ করা", phonetic: "/əbˈzɔːrb/", sentence: "Sponges absorb water rapidly.", translation: "স্পঞ্জ দ্রুত পানি শোষণ করে।" },
  { english: "accelerate", bangla: "গতি বৃদ্ধি করা", phonetic: "/əkˈsɛləreɪt/", sentence: "The driver accelerated to overtake the truck.", translation: "চালক ট্রাকটিকে অতিক্রম করতে গতি বৃদ্ধি করেছিল।" },
  { english: "accompany", bangla: "সঙ্গ দেওয়া", phonetic: "/əˈkʌmpəni/", sentence: "He accompanied his sister to school.", translation: "সে তার বোনকে স্কুলে সঙ্গ দিয়েছিল।" },
  { english: "accomplish", bangla: "সম্পাদন করা / সফল হওয়া", phonetic: "/əˈkʌmplɪʃ/", sentence: "We accomplished our project on schedule.", translation: "আমরা সময়মতো আমাদের প্রকল্প সম্পন্ন করেছি।" },
  { english: "accuse", bangla: "অভিযুক্ত করা", phonetic: "/əˈkjuːz/", sentence: "Never accuse anyone without solid proof.", translation: "সুদৃঢ় প্রমাণ ছাড়া কাউকে অভিযুক্ত করবেন না।" },
  { english: "acknowledge", bangla: "স্বীকার করা", phonetic: "/əkˈnɒlɪdʒ/", sentence: "He acknowledged his mentor's guidance.", translation: "তিনি তার শিক্ষকের নির্দেশনা স্বীকার করেছিলেন।" },
  { english: "activate", bangla: "সক্রিয় করা", phonetic: "/ˈæktɪveɪt/", sentence: "Press the button to activate the machine.", translation: "যন্ত্রটি সক্রিয় করতে বোতামটি চাপুন।" },
  { english: "address", bangla: "সম্বোধন করা / বক্তব্য দেওয়া", phonetic: "/əˈdrɛs/", sentence: "The headmaster addressed the morning assembly.", translation: "প্রধান শিক্ষক সকালের সমাবেশে বক্তব্য দিয়েছিলেন।" },
  { english: "adjust", bangla: "সমন্বয় করা / ঠিক করা", phonetic: "/əˈdʒʌst/", sentence: "Adjust the volume to a comfortable level.", translation: "শব্দের মাত্রা আরামদায়ক স্তরে সমন্বয় করুন।" },
  { english: "advocate", bangla: "সমর্থন করা", phonetic: "/ˈædvəkeɪt/", sentence: "Educationists advocate for child-friendly schooling.", translation: "শিক্ষাবিদরা শিশুবান্ধব শিক্ষার পক্ষে সমর্থন করেন।" },
  { english: "aim", bangla: "লক্ষ্য নির্ধারণ করা", phonetic: "/eɪm/", sentence: "Aim high and work hard to achieve your dream.", translation: "উঁচু লক্ষ্য নির্ধারণ করুন এবং স্বপ্নপূরণে কঠোর পরিশ্রম করুন।" },
  { english: "alter", bangla: "পরিবর্তন করা", phonetic: "/ˈɔːltər/", sentence: "Do not alter the original text without permission.", translation: "অনুমতি ছাড়া মূল পাঠ্যাংশ পরিবর্তন করবেন না।" },
  { english: "analyze", bangla: "বিশ্লেষণ করা", phonetic: "/ˈænəlaɪz/", sentence: "Scientists analyze water samples in the lab.", translation: "বিজ্ঞানীরা ল্যাবরেটরিতে পানির নমুনা বিশ্লেষণ করেন।" },
  { english: "appeal", bangla: "আবেদন করা", phonetic: "/əˈpiːl/", sentence: "Flood victims appealed for emergency relief.", translation: "বন্যার্তরা জরুরি ত্রাণের জন্য আবেদন করেছিল।" },
  { english: "applaud", bangla: "হাততালি দিয়ে প্রশংসা করা", phonetic: "/əˈplɔːd/", sentence: "The audience applauded the singer's performance.", translation: "দর্শকরা গায়কের পরিবেশনার ভূয়সী প্রশংসা করেছিল।" },
  { english: "appoint", bangla: "নিয়োগ করা", phonetic: "/əˈpɔɪnt/", sentence: "The committee appointed a new coordinator.", translation: "কমিটি একজন নতুন সমন্বয়কারী নিয়োগ করেছিল।" },
  { english: "approve", bangla: "অনুমোদন করা", phonetic: "/əˈpruːv/", sentence: "The principal approved our educational excursion.", translation: "অধ্যক্ষ আমাদের শিক্ষাসফর অনুমোদন করেছিলেন।" },
  { english: "argue", bangla: "তর্ক করা / যুক্তি দেওয়া", phonetic: "/ˈɑːrɡjuː/", sentence: "They argued politely during the debate.", translation: "বিতর্কের সময় তারা মার্জিতভাবে যুক্তি দিয়েছিল।" },
  { english: "arise", bangla: "উত্থিত হওয়া / ঘটা", phonetic: "/əˈraɪz/", sentence: "New challenges arise as technology advances.", translation: "প্রযুক্তির অগ্রগতির সাথে সাথে নতুন চ্যালেঞ্জ দেখা দেয়।" },
  { english: "arouse", bangla: "জাগিয়ে তোলা", phonetic: "/əˈraʊz/", sentence: "The thrilling book aroused his curiosity.", translation: "রোমাঞ্চকর বইটি তার কৌতূহল জাগিয়ে তুলেছিল।" },
  { english: "arrest", bangla: "গ্রেপ্তার করা", phonetic: "/əˈrɛst/", sentence: "Police arrested the burglar red-handed.", translation: "পুলিশ চোরটিকে হাতেনাতে গ্রেপ্তার করেছিল।" },
  { english: "assemble", bangla: "একত্রিত হওয়া / জড়ো করা", phonetic: "/əˈsɛmbl/", sentence: "Students assembled on the playground for sports.", translation: "খেলাধুলার জন্য শিক্ষার্থীরা মাঠে একত্রিত হয়েছিল।" },
  { english: "assess", bangla: "মূল্যায়ন করা", phonetic: "/əˈsɛs/", sentence: "Examiners assess student knowledge carefully.", translation: "পরীক্ষকরা যত্ন সহকারে শিক্ষার্থীদের জ্ঞান মূল্যায়ন করেন।" },
  { english: "assign", bangla: "বরাদ্দ করা / কাজ দেওয়া", phonetic: "/əˈsaɪn/", sentence: "The teacher assigned a creative homework project.", translation: "শিক্ষক একটি সৃজনশীল বাড়ির কাজ নির্ধারণ করেছিলেন।" },
  { english: "assure", bangla: "আশ্বাস দেওয়া", phonetic: "/əˈʃʊər/", sentence: "He assured me of his full cooperation.", translation: "তিনি আমাকে তার পূর্ণ সহযোগিতার আশ্বাস দিয়েছিলেন।" },
  { english: "astonish", bangla: "বিস্মিত করা", phonetic: "/əˈstɒnɪʃ/", sentence: "His brilliant memory astonished everyone.", translation: "তার প্রখর স্মৃতিশক্তি সবাইকে বিস্মিত করেছিল।" },
  { english: "attach", bangla: "সংযুক্ত করা", phonetic: "/əˈtætʃ/", sentence: "Attach your passport photograph to the form.", translation: "ফরমের সাথে আপনার পাসপোর্ট ছবি সংযুক্ত করুন।" },
  { english: "attain", bangla: "অর্জন করা", phonetic: "/əˈteɪn/", sentence: "She attained the top position in her class.", translation: "সে তার ক্লাসে শীর্ষ স্থান অর্জন করেছিল।" },
  { english: "authorize", bangla: "অনুমোদিত করা / ক্ষমতা দেওয়া", phonetic: "/ˈɔːθəraɪz/", sentence: "The manager authorized the financial payment.", translation: "ব্যবস্থাপক আর্থিক অর্থপ্রদান অনুমোদিত করেছিলেন।" },
  { english: "awaken", bangla: "জাগ্রত করা / জাগা", phonetic: "/əˈweɪkən/", sentence: "Morning bird songs awaken the village.", translation: "ভোরের পাখির গান গ্রামকে জাগিয়ে তোলে।" },

  // B
  { english: "bang", bangla: "জোরে আঘাত করা / শব্দ করা", phonetic: "/bæŋ/", sentence: "The door banged shut in the gust of wind.", translation: "বাতাসের ঝাপটায় দরজাটি জোরে শব্দ করে বন্ধ হলো।" },
  { english: "banish", bangla: "নির্বাসিত করা / দূর করা", phonetic: "/ˈbænɪʃ/", sentence: "Education banishes the darkness of ignorance.", translation: "শিক্ষা অজ্ঞতার অন্ধকার দূর করে।" },
  { english: "bargain", bangla: "দর কষাকষি করা", phonetic: "/ˈbɑːrɡɪn/", sentence: "Mother bargained with the fruit seller in the market.", translation: "মা বাজারে ফল বিক্রেতার সাথে দর কষাকষি করেছিলেন।" },
  { english: "bat", bangla: "ব্যাট করা", phonetic: "/bæt/", sentence: "The captain chose to bat first after the toss.", translation: "টসের পর অধিনায়ক প্রথমে ব্যাট করার সিদ্ধান্ত নিয়েছিলেন।" },
  { english: "bear", bangla: "সহ্য করা / বহন করা", phonetic: "/bɛər/", sentence: "True heroes bear hardships with patience.", translation: "সত্যিকারের বীরেরা ধৈর্যের সাথে কষ্ট সহ্য করেন।" },
  { english: "beautify", bangla: "সৌন্দর্যমণ্ডিত করা", phonetic: "/ˈbjuːtɪfaɪ/", sentence: "Flowering plants beautify our school premises.", translation: "ফুলের গাছগুলো আমাদের বিদ্যালয় প্রাঙ্গণকে সৌন্দর্যমণ্ডিত করে।" },
  { english: "befriend", bangla: "বন্ধুত্ব করা", phonetic: "/bɪˈfrɛnd/", sentence: "Always befriend honest and kind people.", translation: "সর্বদা সৎ ও সদয় মানুষের সাথে বন্ধুত্ব করুন।" },
  { english: "bestow", bangla: "প্রদান করা / দান করা", phonetic: "/bɪˈstoʊ/", sentence: "Nature bestowed bountiful resources upon our land.", translation: "প্রকৃতি আমাদের দেশকে প্রচুর সম্পদ দান করেছে।" },
  { english: "betray", bangla: "বিশ্বাসঘাতকতা করা", phonetic: "/bɪˈtreɪ/", sentence: "A loyal person will never betray his country.", translation: "একজন অনুগত মানুষ কখনোই দেশের সাথে বিশ্বাসঘাতকতা করবে না।" },
  { english: "bewilder", bangla: "কিংকর্তব্যবিমূঢ় করা", phonetic: "/bɪˈwɪldər/", sentence: "The complex maze bewildered the visitors.", translation: "জটিল গোলকধাঁধাটি দর্শকদের কিংকর্তব্যবিমূঢ় করেছিল।" },
  { english: "bleed", bangla: "রক্তক্ষরণ হওয়া", phonetic: "/bliːd/", sentence: "Apply gentle pressure when a wound bleeds.", translation: "ক্ষত থেকে রক্তপাত হলে আলতো চাপ দিন।" },
  { english: "blend", bangla: "মিশ্রিত করা", phonetic: "/blɛnd/", sentence: "Blend milk and ripe bananas for a healthy smoothie.", translation: "একটি স্বাস্থ্যকর স্মুদির জন্য দুধ ও পাকা কলা মিশ্রিত করুন।" },
  { english: "blink", bangla: "পলক ফেলা", phonetic: "/blɪŋk/", sentence: "Blink your eyes to reduce digital screen strain.", translation: "ডিজিটাল পর্দার চাপ কমাতে চোখের পলক ফেলুন।" },
  { english: "block", bangla: "বাধা দেওয়া / পথ রুদ্ধ করা", phonetic: "/blɒk/", sentence: "Fallen trees blocked the village road.", translation: "ভাঙা গাছগুলো গ্রামের রাস্তা রুদ্ধ করে রেখেছিল।" },
  { english: "bloom", bangla: "ফুল ফোটা", phonetic: "/bluːm/", sentence: "Fragrant lilies bloom in spring gardens.", translation: "বসন্তের বাগানে সুবাসিত লিলি ফুল ফোটে।" },
  { english: "blush", bangla: "লজ্জায় লাল হওয়া", phonetic: "/blʌʃ/", sentence: "She blushed when everyone praised her poem.", translation: "সবাই তার কবিতার প্রশংসা করায় সে লজ্জায় লাল হয়েছিল।" },
  { english: "board", bangla: "আরোহণ করা / জাহাজে ওঠা", phonetic: "/bɔːrd/", sentence: "Passengers boarded the train in an orderly queue.", translation: "যাত্রীরা শৃঙ্খলার সাথে ট্রেনে আরোহণ করেছিলেন।" },
  { english: "boast", bangla: "দম্ভ করা / অহংকার করা", phonetic: "/boʊst/", sentence: "A truly wise scholar does not boast of his learning.", translation: "সত্যিকারের জ্ঞানী পণ্ডিত নিজের শিক্ষা নিয়ে দম্ভ করেন না।" },
  { english: "boost", bangla: "উদ্বুদ্ধ করা / বৃদ্ধি করা", phonetic: "/buːst/", sentence: "Regular study boosts student self-confidence.", translation: "নিয়মিত অধ্যয়ন শিক্ষার্থীদের আত্মবিশ্বাস বৃদ্ধি করে।" },
  { english: "bother", bangla: "বিরক্ত করা / দুশ্চিন্তা করা", phonetic: "/ˈbɒðər/", sentence: "Do not bother your classmates during silent reading.", translation: "নীরব পাঠের সময় সহপাঠীদের বিরক্ত করবেন না।" },
  { english: "bounce", bangla: "লাফানো / ড্রপ খাওয়া", phonetic: "/baʊns/", sentence: "The rubber ball bounced high on the concrete floor.", translation: "রাবারের বলটি পাকা মেঝেতে উঁচুতে লাফিয়ে উঠেছিল।" },
  { english: "bow", bangla: "নত হওয়া / মাথা নোয়ানো", phonetic: "/baʊ/", sentence: "Performers bowed gracefully before the audience.", translation: "শিল্পীরা দর্শকদের সামনে মার্জিতভাবে মাথা নত করেছিলেন।" },
  { english: "braid", bangla: "বেণি করা", phonetic: "/breɪd/", sentence: "She braided her long dark hair neatly.", translation: "সে তার লম্বা কালো চুল সুন্দরভাবে বেণি করেছিল।" },
  { english: "brake", bangla: "ব্রেক কষা / থামানো", phonetic: "/breɪk/", sentence: "The cyclist braked sharply to avoid a puddle.", translation: "কাদার গর্ত এড়াতে সাইকেল আরোহী শক্তভাবে ব্রেক কষেছিলেন।" },
  { english: "broaden", bangla: "প্রশস্ত করা", phonetic: "/ˈbrɔːdn/", sentence: "Reading diverse literature broadens the mind.", translation: "নানা ধরনের সাহিত্য পাঠ মনকে প্রশস্ত করে।" },
  { english: "brush", bangla: "ব্রাশ করা / পরিষ্কার করা", phonetic: "/brʌʃ/", sentence: "Brush your teeth twice daily after meals.", translation: "খাবারের পর প্রতিদিন দুবার দাঁত ব্রাশ করুন।" },
  { english: "bubble", bangla: "বুদ্বুদ ওঠা", phonetic: "/ˈbʌbl/", sentence: "Boiling water bubbles gently in the kettle.", translation: "কেটলিতে ফুটন্ত পানি মৃদুভাবে বুদ্বুদ তুলছে।" },
  { english: "bury", bangla: "দাফন করা / পুঁতে ফেলা", phonetic: "/ˈbɛri/", sentence: "Pirates buried their treasure on the secret island.", translation: "জলদস্যুরা গোপন দ্বীপে তাদের সম্পদ পুঁতে রেখেছিল।" },
  { english: "buzz", bangla: "গুঞ্জন করা / ভনভন করা", phonetic: "/bʌz/", sentence: "Honeybees buzz around fragrant garden flowers.", translation: "সুবাসিত বাগানের ফুলে মৌমাছিরা ভনভন করে।" },

  // C
  { english: "calculate", bangla: "গণনা করা", phonetic: "/ˈkælkjuleɪt/", sentence: "Astronomers calculate the speed of distant stars.", translation: "জ্যোতির্বিজ্ঞানীরা দূরের তারার গতি গণনা করেন।" },
  { english: "calm", bangla: "শান্ত করা / শান্ত হওয়া", phonetic: "/kɑːm/", sentence: "The teacher calmed the noisy classroom gently.", translation: "শিক্ষক কোমলভাবে কোলাহলপূর্ণ শ্রেণিকক্ষকে শান্ত করেছিলেন।" },
  { english: "cancel", bangla: "বাতিল করা", phonetic: "/ˈkænsəl/", sentence: "Due to dense fog, the flight was canceled.", translation: "ঘন কুয়াশার কারণে বিমান ফ্লাইটটি বাতিল করা হয়েছিল।" },
  { english: "capture", bangla: "বন্দী করা / ধরে রাখা", phonetic: "/ˈkæptʃər/", sentence: "The camera captured the golden sunrise perfectly.", translation: "ক্যামেরাটি সোনালি সূর্যোদয় নিখুঁতভাবে ধারণ করেছিল।" },
  { english: "care", bangla: "যত্ন নেওয়া / তোয়াক্কা করা", phonetic: "/kɛər/", sentence: "Compassionate doctors care deeply for patients.", translation: "সহানুভূতিশীল চিকিৎসকরা রোগীদের গভীরভাবে যত্ন নেন।" },
  { english: "carve", bangla: "খোদাই করা", phonetic: "/kɑːrv/", sentence: "The craftsman carved wooden floral designs skillfully.", translation: "কারিগর কাঠের ওপর দক্ষতার সাথে ফুলের নকশা খোদাই করেছিলেন।" },
  { english: "cater", bangla: "খাবার সরবরাহ করা / চাহিদা মেটানো", phonetic: "/ˈkeɪtər/", sentence: "The library caters to the needs of curious learners.", translation: "গ্রন্থাগার কৌতূহলী শিক্ষার্থীদের চাহিদা মেটায়।" },
  { english: "cause", bangla: "ঘটা / কারণ হওয়া", phonetic: "/kɔːz/", sentence: "Heavy rainfall caused flooding in the lowlands.", translation: "ভারী বর্ষণের কারণে নিম্নাঞ্চলে বন্যা সৃষ্টি হয়েছিল।" },
  { english: "cease", bangla: "থামানো / বন্ধ হওয়া", phonetic: "/siːs/", sentence: "The storm ceased and stars began to shine.", translation: "ঝড় থেমে গেল এবং আকাশে তারা জ্বলতে শুরু করল।" },
  { english: "certify", bangla: "প্রত্যয়ন করা", phonetic: "/ˈsɜːrtɪfaɪ/", sentence: "Doctors certify the medical fitness of candidates.", translation: "চিকিৎসকরা প্রার্থীদের শারীরিক সুস্থতা প্রত্যয়ন করেন।" },
  { english: "challenge", bangla: "চ্যালেঞ্জ করা / আহ্বান জানানো", phonetic: "/ˈtʃælɪndʒ/", sentence: "Difficult puzzles challenge our critical thinking.", translation: "কঠিন ধাঁধা আমাদের সূক্ষ্ম চিন্তাভাবনাকে চ্যালেঞ্জ জানায়।" },
  { english: "charge", bangla: "দায়িত্ব দেওয়া / মূল্য ধরা", phonetic: "/tʃɑːrdʒ/", sentence: "The hotel charges reasonable rates for travelers.", translation: "হোটেলটি ভ্রমণকারীদের জন্য যুক্তিযুক্ত ভাড়া নির্ধারণ করে।" },
  { english: "charm", bangla: "মুগ্ধ করা", phonetic: "/tʃɑːrm/", sentence: "Her melodious song charmed the entire gathering.", translation: "তার সুমধুর গান সমগ্র সমাবেশকে মুগ্ধ করেছিল।" },
  { english: "chatter", bangla: "কচির মিচির করা / অনবরত কথা বলা", phonetic: "/ˈtʃætər/", sentence: "Children chattered happily during the recess.", translation: "বিরতির সময় শিশুরা আনন্দের সাথে কিচিরমিচির করছিল।" },
  { english: "cheer", bangla: "উৎসাহিত করা / আনন্দধ্বনি করা", phonetic: "/tʃɪər/", sentence: "Supporters cheered enthusiastically for their school team.", translation: "সমর্থকরা তাদের স্কুল দলের জন্য উৎসাহের সাথে আনন্দধ্বনি করেছিল।" },
  { english: "cherish", bangla: "স্নেহে লালন করা / মূল্যায়ন করা", phonetic: "/ˈtʃɛrɪʃ/", sentence: "We cherish childhood memories with immense fondness.", translation: "আমরা শৈশবের স্মৃতিগুলোকে গভীর ভালোবাসার সাথে লালন করি।" },
  { english: "chew", bangla: "চিবানো", phonetic: "/tʃuː/", sentence: "Chew your food properly before swallowing.", translation: "গেলার আগে খাবারটি সঠিকভাবে চিবিয়ে নিন।" },
  { english: "chuckle", bangla: "মুচকি হাসা", phonetic: "/ˈtʃʌkl/", sentence: "Grandfather chuckled at the child's amusing trick.", translation: "শিশুর মজার কাণ্ডে দাদা মুচকি হেসেছিলেন।" },
  { english: "circulate", bangla: "সংবহন হওয়া / বিতরণ করা", phonetic: "/ˈsɜːrkjəleɪt/", sentence: "Blood circulates oxygen throughout the human body.", translation: "রক্ত সারা মানবদেহে অক্সিজেন সংবহন করে।" },
  { english: "claim", bangla: "দাবি করা", phonetic: "/kleɪm/", sentence: "The scientist claimed to have found a new cure.", translation: "বিজ্ঞানী নতুন প্রতিষেধক আবিষ্কারের দাবি করেছিলেন।" },
  { english: "clarify", bangla: "স্পষ্ট করা", phonetic: "/ˈklærɪfaɪ/", sentence: "Teacher clarified the complicated mathematical step.", translation: "শিক্ষক জটিল গাণিতিক ধাপটি স্পষ্ট করেছিলেন।" },
  { english: "classify", bangla: "শ্রেণিভুক্ত করা", phonetic: "/ˈklæsɪfaɪ/", sentence: "Biologists classify organisms according to family.", translation: "জীববিজ্ঞানীরা প্রজাতি অনুযায়ী জীবকে শ্রেণিভুক্ত করেন।" },
  { english: "cleanse", bangla: "পরিশুদ্ধ করা / পরিষ্কার করা", phonetic: "/klɛnz/", sentence: "Fresh rainwater cleansed dust from green leaves.", translation: "তাজা বৃষ্টির পানি সবুজ পাতা থেকে ধুলো ধুয়ে পরিষ্কার করল।" },
  { english: "clench", bangla: "মুঠো করা / শক্ত করে বাঁধা", phonetic: "/klɛntʃ/", sentence: "He clenched his fists in strong determination.", translation: "সে দৃঢ় সংকল্পে নিজের হাত মুঠো করেছিল।" },
  { english: "cling", bangla: "আঁকড়ে থাকা", phonetic: "/klɪŋ/", sentence: "The baby monkey clung tightly to its mother.", translation: "ছোট বানরছানাটি তার মাকে শক্তভাবে আঁকড়ে ছিল।" },
  { english: "coach", bangla: "প্রশিক্ষণ দেওয়া", phonetic: "/koʊtʃ/", sentence: "The sports master coaches football players after school.", translation: "ক্রীড়া শিক্ষক ছুটির পর ফুটবল খেলোয়াড়দের প্রশিক্ষণ দেন।" },
  { english: "collapse", bangla: "ভেঙে পড়া", phonetic: "/kəˈlæps/", sentence: "The dilapidated bridge collapsed during the flash flood.", translation: "হঠাৎ বন্যায় জরাজীর্ণ সেতুটি ভেঙে পড়েছিল।" },
  { english: "collide", bangla: "সংঘর্ষ হওয়া", phonetic: "/kəˈlaɪd/", sentence: "Two boats collided in the foggy river.", translation: "কুয়াশাচ্ছন্ন নদীতে দুটি নৌকার সংঘর্ষ হয়েছিল।" },
  { english: "comfort", bangla: "সান্ত্বনা দেওয়া", phonetic: "/ˈkʌmfərt/", sentence: "She comforted her friend in times of sorrow.", translation: "দুঃখের দিনে সে তার বন্ধুকে সান্ত্বনা দিয়েছিল।" },
  { english: "command", bangla: "আদেশ দেওয়া / নেতৃত্ব দেওয়া", phonetic: "/kəˈmænd/", sentence: "The captain commanded his regiment with dignity.", translation: "অধিনায়ক মর্যাদার সাথে তার রেজিমেন্টকে পরিচালনা করেছিলেন।" },
  { english: "commence", bangla: "আরম্ভ করা / শুরু করা", phonetic: "/kəˈmɛns/", sentence: "The final examination will commence next Sunday.", translation: "আগামী রবিবার চূড়ান্ত পরীক্ষা আরম্ভ হবে।" },
  { english: "commend", bangla: "প্রশংসা করা", phonetic: "/kəˈmɛnd/", sentence: "The principal commended her disciplined conduct.", translation: "অধ্যক্ষ তার সুশৃঙ্খল আচরণের প্রশংসা করেছিলেন।" },
  { english: "commit", bangla: "প্রতিশ্রুতিবদ্ধ হওয়া / করা", phonetic: "/kəˈmɪt/", sentence: "Commit yourself to honest and persistent study.", translation: "সৎ ও অবিচল পড়াশোনায় নিজেকে প্রতিশ্রুতিবদ্ধ করো।" },
  { english: "communicate", bangla: "যোগাযোগ করা", phonetic: "/kəˈmjuːnɪkeɪt/", sentence: "Effective leaders communicate clearly with all teams.", translation: "কার্যকর নেতারা সকল দলের সাথে স্পষ্টভাবে যোগাযোগ করেন।" },
  { english: "compare", bangla: "তুলনা করা", phonetic: "/kəmˈpɛər/", sentence: "Do not compare your progress with others.", translation: "অন্যের সাথে নিজের অগ্রগতির তুলনা করবেন না।" },
  { english: "compel", bangla: "বাধ্য করা", phonetic: "/kəmˈpɛl/", sentence: "Duty compels us to help our neighbors.", translation: "কর্তব্যবোধ আমাদের প্রতিবেশীদের সাহায্য করতে বাধ্য করে।" },
  { english: "compensate", bangla: "ক্ষতিপূরণ দেওয়া", phonetic: "/ˈkɒmpənseɪt/", sentence: "The insurance company compensated for the fire loss.", translation: "বীমা কোম্পানি অগ্নিকাণ্ডের ক্ষতির ক্ষতিপূরণ দিয়েছিল।" },
  { english: "compete", bangla: "প্রতিযোগিতা করা", phonetic: "/kəmˈpiːt/", sentence: "Talented students compete for the national prize.", translation: "মেধাবী শিক্ষার্থীরা জাতীয় পুরস্কারের জন্য প্রতিযোগিতা করে।" },
  { english: "compile", bangla: "সংকলন করা", phonetic: "/kəmˈpaɪl/", sentence: "The scholar compiled an extensive English dictionary.", translation: "পণ্ডিত একটি সমৃদ্ধ ইংরেজি অভিধান সংকলন করেছিলেন।" },
  { english: "complain", bangla: "অভিযোগ করা", phonetic: "/kəmˈpleɪn/", sentence: "Patients complained about poor hospital ventilation.", translation: "রোগীরা হাসপাতালের দুর্বল বাতাস চলাচল নিয়ে অভিযোগ করেছিল।" },
  { english: "compose", bangla: "রচনা করা", phonetic: "/kəmˈpoʊz/", sentence: "Rabindranath Tagore composed our national anthem.", translation: "রবীন্দ্রনাথ ঠাকুর আমাদের জাতীয় সংগীত রচনা করেছিলেন।" },
  { english: "comprehend", bangla: "উপলব্ধি করা / বোঝা", phonetic: "/ˌkɒmprɪˈhɛnd/", sentence: "Read slowly to comprehend deep philosophical ideas.", translation: "গভীর দার্শনিক ধারণা বোঝার জন্য ধীরে ধীরে পড়ুন।" },
  { english: "compromise", bangla: "আপস করা", phonetic: "/ˈkɒmprəmaɪz/", sentence: "Never compromise on your honesty and moral integrity.", translation: "সততা ও নৈতিকতার প্রশ্নে কখনো আপস করবেন না।" },
  { english: "conceal", bangla: "গোপন করা / লুকানো", phonetic: "/kənˈsiːl/", sentence: "Truth cannot be concealed behind clever lies.", translation: "চতুর মিথ্যার আড়ালে সত্যকে গোপন করা যায় না।" },
  { english: "concede", bangla: "স্বীকার করা / মেনে নেওয়া", phonetic: "/kənˈsiːd/", sentence: "He conceded defeat graciously in the tournament.", translation: "প্রতিযোগিতায় সে ভদ্রভাবে পরাজয় মেনে নিয়েছিল।" },
  { english: "concentrate", bangla: "মনোসংযোগ করা", phonetic: "/ˈkɒnsəntreɪt/", sentence: "Concentrate on the blackboard during classroom lectures.", translation: "শ্রেণিকক্ষের বক্তৃতার সময় ব্ল্যাকবোর্ডে মনোযোগ দিন।" },
  { english: "conclude", bangla: "উপসংহার টানা / সমাপ্ত করা", phonetic: "/kənˈkluːd/", sentence: "The debate concluded with a heartfelt vote of thanks.", translation: "আন্তরিক ধন্যবাদ জ্ঞাপনের মাধ্যমে বিতর্ক প্রতিযোগিতা সমাপ্ত হলো।" },
  { english: "condemn", bangla: "নিন্দা করা", phonetic: "/kənˈdɛm/", sentence: "Peace-loving nations condemn acts of warfare.", translation: "শান্তিকামী জাতিগুলো যুদ্ধবিগ্রহের ঘটনার নিন্দা করে।" },
  { english: "conduct", bangla: "পরিচালনা করা", phonetic: "/kənˈdʌkt/", sentence: "The science committee conducted an experiment.", translation: "বিজ্ঞান কমিটি একটি পরীক্ষা পরিচালনা করেছিল।" },
  { english: "confess", bangla: "দোষ স্বীকার করা", phonetic: "/kənˈfɛs/", sentence: "The boy confessed his mistake and felt relieved.", translation: "ছেলেটি নিজের ভুল স্বীকার করেছিল এবং স্বস্তি পেয়েছিল।" },
  { english: "confirm", bangla: "নিশ্চিত করা", phonetic: "/kənˈfɜːrm/", sentence: "The railway office confirmed our train booking.", translation: "রেলওয়ে অফিস আমাদের ট্রেনের বুকিং নিশ্চিত করেছিল।" },
  { english: "conflict", bangla: "দ্বন্দ্বে জড়ানো / বিরোধী হওয়া", phonetic: "/kənˈflɪkt/", sentence: "His greedy actions conflict with his noble words.", translation: "তার লোভী কর্মকাণ্ড তার মহৎ কথার সাথে সাংঘর্ষিক।" },
  { english: "conform", bangla: "নিয়ম মেনে চলা", phonetic: "/kənˈfɔːrm/", sentence: "All citizens must conform to traffic safety rules.", translation: "সকল নাগরিককে অবশ্যই ট্রাফিক নিরাপত্তা নিয়ম মেনে চলতে হবে।" },
  { english: "confront", bangla: "মোকাবিলা করা / মুখোমুখি হওয়া", phonetic: "/kənˈfrʌnt/", sentence: "Brave souls confront life's storms with patience.", translation: "সাহসী ব্যক্তিরা ধৈর্যের সাথে জীবনের ঝড় মোকাবিলা করেন।" },
  { english: "confuse", bangla: "বিভ্রান্ত করা", phonetic: "/kənˈfjuːz/", sentence: "Unclear instructions confuse junior students.", translation: "অস্পষ্ট নির্দেশনা জুনিয়র শিক্ষার্থীদের বিভ্রান্ত করে।" },
  { english: "connect", bangla: "যুক্ত করা", phonetic: "/kəˈnɛkt/", sentence: "Bridges connect villages and encourage trade.", translation: "সেতুগুলো গ্রামগুলোকে সংযুক্ত করে এবং বাণিজ্যে উৎসাহ দেয়।" },
  { english: "conquer", bangla: "জয় করা", phonetic: "/ˈkɒŋkər/", sentence: "Knowledge and love conquer prejudice and hatred.", translation: "জ্ঞান ও ভালোবাসা কুসংস্কার ও ঘৃণাকে জয় করে।" },
  { english: "consent", bangla: "সম্মতি দেওয়া", phonetic: "/kənˈsɛnt/", sentence: "Parents consented to the student field trip.", translation: "পিতা-মাতা শিক্ষার্থীদের শিক্ষাসফরে সম্মতি দিয়েছিলেন।" },
  { english: "conserve", bangla: "সংরক্ষণ করা", phonetic: "/kənˈsɜːrv/", sentence: "We must conserve fresh water and electricity.", translation: "আমাদের অবশ্যই বিশুদ্ধ পানি ও বিদ্যুৎ সংরক্ষণ করতে হবে।" },
  { english: "consider", bangla: "বিবেচনা করা", phonetic: "/kənˈsɪdər/", sentence: "Consider other people's feelings before speaking.", translation: "কথা বলার আগে অন্যদের অনুভূতির কথা বিবেচনা করুন।" },
  { english: "consist", bangla: "গঠিত হওয়া", phonetic: "/kənˈsɪst/", sentence: "Water consists of hydrogen and oxygen atoms.", translation: "পানি হাইড্রোজেন ও অক্সিজেন পরমাণু নিয়ে গঠিত।" },
  { english: "console", bangla: "সান্ত্বনা দেওয়া", phonetic: "/kənˈsoʊl/", sentence: "Friends consoled him in his time of distress.", translation: "বিপদের দিনে বন্ধুরা তাকে সান্ত্বনা দিয়েছিল।" },
  { english: "construct", bangla: "নির্মাণ করা", phonetic: "/kənˈstrʌkt/", sentence: "Builders constructed a modern health complex.", translation: "নির্মাতারা একটি আধুনিক স্বাস্থ্য কমপ্লেক্স নির্মাণ করেছিলেন।" },
  { english: "consult", bangla: "পরামর্শ নেওয়া", phonetic: "/kənˈsʌlt/", sentence: "Consult an expert doctor when feeling unwell.", translation: "অসুস্থ বোধ করলে একজন বিশেষজ্ঞ ডাক্তারের পরামর্শ নিন।" },
  { english: "consume", bangla: "ভোগ করা / খাওয়া", phonetic: "/kənˈsjuːm/", sentence: "Consume nutritious food for sustained energy.", translation: "দীর্ঘস্থায়ী শক্তির জন্য পুষ্টিকর খাবার গ্রহণ করুন।" },
  { english: "contain", bangla: "ধারণ করা", phonetic: "/kənˈteɪn/", sentence: "Citrus fruits contain valuable Vitamin C.", translation: "লেবুজাতীয় ফলে মূল্যবান ভিটামিন সি থাকে।" },
  { english: "contemplate", bangla: "গভীরভাবে ভাবা", phonetic: "/ˈkɒntəmpleɪt/", sentence: "Philosophers contemplate the mysteries of nature.", translation: "দার্শনিকরা প্রকৃতির রহস্য নিয়ে গভীরভাবে ভাবেন।" },
  { english: "continue", bangla: "চালিয়ে যাওয়া", phonetic: "/kənˈtɪnjuː/", sentence: "Continue your noble educational mission untiringly.", translation: "অক্লান্তভাবে তোমার মহৎ শিক্ষামূলক অভিযান চালিয়ে যাও।" },
  { english: "contract", bangla: "সংকুচিত হওয়া / চুক্তি করা", phonetic: "/kənˈtrækt/", sentence: "Metals contract slightly when cooled down.", translation: "ঠান্ডা হলে ধাতু কিছুটা সংকুচিত হয়।" },
  { english: "contradict", bangla: "পরস্পরবিরোধী হওয়া / খণ্ডন করা", phonetic: "/ˌkɒntrəˈdɪkt/", sentence: "His recent statement contradicts his earlier remarks.", translation: "তার সাম্প্রতিক বক্তব্য তার আগের কথার সাথে পরস্পরবিরোধী।" },
  { english: "contribute", bangla: "অবদান রাখা", phonetic: "/kənˈtrɪbjuːt/", sentence: "Donors contributed generously to the flood relief fund.", translation: "দাতারা ত্রাণ তহবিলে উদারভাবে অবদান রেখেছিলেন।" },
  { english: "control", bangla: "নিয়ন্ত্রণ করা", phonetic: "/kənˈtroʊl/", sentence: "Control your anger to maintain peace of mind.", translation: "মানসিক শান্তি বজায় রাখতে নিজের রাগ নিয়ন্ত্রণ করুন।" },
  { english: "converse", bangla: "কথোপকথন করা", phonetic: "/kənˈvɜːrs/", sentence: "Scholars conversed on moral education in schools.", translation: "পণ্ডিতরা বিদ্যালয়ে নৈতিক শিক্ষা নিয়ে কথোপকথন করেছিলেন।" },
  { english: "convert", bangla: "রূপান্তরিত করা", phonetic: "/kənˈvɜːrt/", sentence: "Solar panels convert sunlight into clean electricity.", translation: "সৌর প্যানেল সূর্যের আলোকে পরিচ্ছন্ন বিদ্যুতে রূপান্তরিত করে।" },
  { english: "convey", bangla: "পৌঁছে দেওয়া / জ্ঞাপন করা", phonetic: "/kənˈveɪ/", sentence: "Please convey my respectful regards to your parents.", translation: "তোমার পিতা-মাতাকে আমার সশ্রদ্ধ সালাম পৌঁছে দিও।" },
  { english: "convince", bangla: "নিশ্চিত করা / বিশ্বাস করানো", phonetic: "/kənˈvɪns/", sentence: "Her logical arguments convinced the entire jury.", translation: "তার যৌক্তিক যুক্তি সমগ্র বিচারকমণ্ডলীকে বিশ্বাস করিয়েছিল।" },
  { english: "cook", bangla: "রান্না করা", phonetic: "/kʊk/", sentence: "The chef cooked delicious traditional delicacies.", translation: "পাচক সুস্বাদু ঐতিহ্যবাহী খাবার রান্না করেছিলেন।" },
  { english: "cooperate", bangla: "সহযোগিতা করা", phonetic: "/koʊˈɒpəreɪt/", sentence: "Nations cooperate to tackle environmental pollution.", translation: "পরিবেশ দূষণ রোধে দেশগুলো পরস্পর সহযোগিতা করে।" },
  { english: "coordinate", bangla: "সমন্বয় করা", phonetic: "/koʊˈɔːrdɪneɪt/", sentence: "She coordinated all cultural events wonderfully.", translation: "সে চমৎকারভাবে সকল সাংস্কৃতিক অনুষ্ঠানের সমন্বয় করেছিল।" },
  { english: "cope", bangla: "মানিয়ে নেওয়া", phonetic: "/koʊp/", sentence: "Students learn to cope with exam pressure.", translation: "শিক্ষার্থীরা পরীক্ষার চাপের সাথে মানিয়ে নিতে শেখে।" },
  { english: "correct", bangla: "সংশোধন করা", phonetic: "/kəˈrɛkt/", sentence: "Teachers patiently correct student pronunciation.", translation: "শিক্ষকরা ধৈর্য সহকারে শিক্ষার্থীদের উচ্চারণ সংশোধন করেন।" },
  { english: "correspond", bangla: "চিঠিপত্র বিনিময় করা / সামঞ্জস্যপূর্ণ হওয়া", phonetic: "/ˌkɒrɪˈspɒnd/", sentence: "His deeds correspond with his ethical beliefs.", translation: "তার কাজকর্ম তার নৈতিক বিশ্বাসের সাথে সামঞ্জস্যপূর্ণ।" },
  { english: "counsel", bangla: "পরামর্শ দেওয়া", phonetic: "/ˈkaʊnsl/", sentence: "The advisor counseled the youth on career choices.", translation: "উপদেষ্টা তরুণদের ক্যারিয়ার নির্বাচনে পরামর্শ দিয়েছিলেন।" },
  { english: "count", bangla: "গণনা করা", phonetic: "/kaʊnt/", sentence: "Count your blessings every single day.", translation: "প্রতিটি দিন নিজের প্রাপ্তিগুলোকে স্মরণ করুন।" },
  { english: "crave", bangla: "তীব্র আকাঙ্ক্ষা করা", phonetic: "/kreɪv/", sentence: "Tired travelers crave fresh spring water.", translation: "ক্লান্ত পথিকরা ঝরনার মিষ্টি তাজা পানির তীব্র আকাঙ্ক্ষা করে।" },
  { english: "create", bangla: "সৃষ্টি করা", phonetic: "/kriˈeɪt/", sentence: "Creative writers create inspiring literary works.", translation: "সৃজনশীল লেখকরা অনুপ্রেরণাদায়ী সাহিত্য সৃষ্টি করেন।" },
  { english: "criticize", bangla: "সমালোচনা করা", phonetic: "/ˈkrɪtɪsaɪz/", sentence: "Constructive feedback criticizes work, not character.", translation: "গঠনমূলক মন্তব্য কাজের সমালোচনা করে, চরিত্রের নয়।" },
  { english: "cross", bangla: "পার হওয়া", phonetic: "/krɒs/", sentence: "Sailors crossed the wide bay safely.", translation: "নাবিকরা নিরাপদে সুবিশাল উপসাগর পার হয়েছিল।" },
  { english: "crush", bangla: "গুঁড়ো করা / দলিত করা", phonetic: "/krʌʃ/", sentence: "Mills crush sugar cane to extract sweet juice.", translation: "মিষ্টি রস বের করতে কলগুলো আখ মাড়াই করে।" },
  { english: "cry", bangla: "কাঁদা", phonetic: "/kraɪ/", sentence: "Compassionate people cry at the suffering of others.", translation: "সহানুভূতিশীল মানুষ অন্যের কষ্টে অশ্রু বিসর্জন করেন।" },
  { english: "cultivate", bangla: "চাষাবাদ করা / গড়ে তোলা", phonetic: "/ˈkʌltɪveɪt/", sentence: "Cultivate the golden habit of daily reading.", translation: "প্রতিদিন বই পড়ার সোনালি অভ্যাস গড়ে তুলুন।" },
  { english: "cure", bangla: "আরোগ্য করা", phonetic: "/kjʊər/", sentence: "Medicinal herbs cure common coughs and colds.", translation: "ভেষজ উদ্ভিদ সাধারণ সর্দি-কাশি আরোগ্য করে।" },
  { english: "curl", bangla: "কুঁকড়ানো", phonetic: "/kɜːrl/", sentence: "Smoke curled upwards from the brick chimney.", translation: "ইটের তৈরি চিমনির ওপর দিয়ে ধোঁয়া কুঁকড়ে উঠছিল।" },
  { english: "curve", bangla: "বাঁক নেওয়া", phonetic: "/kɜːrv/", sentence: "The scenic river curves through lush green fields.", translation: "নয়নাভিরাম নদীটি সবুজ মাঠের মধ্য দিয়ে বাঁক নিয়েছে।" },
  { english: "cut", bangla: "কাটা", phonetic: "/kʌt/", sentence: "Carpenters cut timber precisely to construct desks.", translation: "কাঠমিস্ত্রিরা টেবিল তৈরির জন্য কাঠ নিখুঁতভাবে কাটেন।" }
];

console.log('Verbs batch prepared:', verbsBatch.length);
