const fs = require('fs');

// We have 394 items in scripts/parsed_first_395.json.
// We need exactly 1260 items (866 items to add).
// Let's create comprehensive datasets for the remaining weeks and days!

const first394 = JSON.parse(fs.readFileSync('scripts/parsed_first_395.json', 'utf8'));

// Standard list of authentic verbs and vocabulary with Bengali translations
const verbVocabList = [
  // D
  { english: "dare", bangla: "সাহস করা", phonetic: "/dɛər/", sentence: "He dared to speak the truth in public.", translation: "সে জনসমক্ষে সত্য বলার সাহস করেছিল।" },
  { english: "dash", bangla: "ছুটে যাওয়া", phonetic: "/dæʃ/", sentence: "The boy dashed across the field to catch the ball.", translation: "বলটি ধরতে ছেলেটি মাঠজুড়ে ছুটে গিয়েছিল।" },
  { english: "dazzle", bangla: "চোখ ধাঁধানো", phonetic: "/ˈdæzl/", sentence: "The fireworks dazzled the night sky.", translation: "আতশবাজি রাতের আকাশকে চোখ ধাঁধিয়ে দিয়েছিল।" },
  { english: "deal", bangla: "ব্যবহার করা / লেনদেন করা", phonetic: "/diːl/", sentence: "Always deal honestly in business transactions.", translation: "ব্যবসায়িক লেনদেনে সর্বদা সততার সাথে আচরণ করুন।" },
  { english: "debate", bangla: "বিতর্ক করা", phonetic: "/dɪˈbeɪt/", sentence: "Students debated on environmental conservation.", translation: "শিক্ষার্থীরা পরিবেশ সংরক্ষণ বিষয়ে বিতর্ক করেছিল।" },
  { english: "decay", bangla: "ক্ষয়প্রাপ্ত হওয়া", phonetic: "/dɪˈkeɪ/", sentence: "Fallen leaves decay and enrich the soil.", translation: "ঝরা পাতা ক্ষয়প্রাপ্ত হয়ে মাটিকে সমৃদ্ধ করে।" },
  { english: "deceive", bangla: "প্রতারণা করা", phonetic: "/dɪˈsiːv/", sentence: "An honest person will never deceive others.", translation: "একজন সৎ মানুষ কখনোই অন্যদের প্রতারণা করবে না।" },
  { english: "decide", bangla: "সিদ্ধান্ত নেওয়া", phonetic: "/dɪˈsaɪd/", sentence: "Decide your future goals with careful planning.", translation: "সতর্ক পরিকল্পনার সাথে তোমার ভবিষ্যৎ লক্ষ্য নির্ধারণ করো।" },
  { english: "declare", bangla: "ঘোষণা করা", phonetic: "/dɪˈklɛər/", sentence: "The referee declared the winning team.", translation: "রেফারি বিজয়ী দলের নাম ঘোষণা করেছিলেন।" },
  { english: "decorate", bangla: "সাজানো", phonetic: "/ˈdɛkəreɪt/", sentence: "They decorated the hall for the annual festival.", translation: "বার্ষিক উৎসবের জন্য তারা হলরুমটি সাজিয়েছিল।" },
  { english: "decrease", bangla: "কমানো / হ্রাস পাওয়া", phonetic: "/dɪˈkriːs/", sentence: "Pollution decreases when green energy is used.", translation: "সবুজ শক্তি ব্যবহার করলে দূষণ হ্রাস পায়।" },
  { english: "dedicate", bangla: "উৎসর্গ করা", phonetic: "/ˈdɛdɪkeɪt/", sentence: "He dedicated his life to teaching underprivileged children.", translation: "তিনি সুবিধাবঞ্চিত শিশুদের শিক্ষাদানে নিজের জীবন উৎসর্গ করেছেন।" },
  { english: "defend", bangla: "রক্ষা করা", phonetic: "/dɪˈfɛnd/", sentence: "Soldiers defend their country's border vigilantly.", translation: "সৈনিকরা সতর্কতার সাথে দেশের সীমান্ত রক্ষা করেন।" },
  { english: "define", bangla: "সংজ্ঞায়িত করা", phonetic: "/dɪˈfaɪn/", sentence: "Dictionaries define the precise meanings of words.", translation: "অভিধান শব্দের সুনির্দিষ্ট অর্থ সংজ্ঞায়িত করে।" },
  { english: "delay", bangla: "দেরি করা / বিলম্ব করা", phonetic: "/dɪˈleɪ/", sentence: "Never delay doing good deeds.", translation: "ভালো কাজ করতে কখনোই দেরি করবেন না।" },
  { english: "deliver", bangla: "বিতরণ করা / পৌঁছানো", phonetic: "/dɪˈlɪvər/", sentence: "Couriers deliver parcels to customers quickly.", translation: "কুরিয়ার কর্মীরা গ্রাহকদের কাছে পার্সেল দ্রুত পৌঁছে দেন।" },
  { english: "demonstrate", bangla: "প্রদর্শন করা", phonetic: "/ˈdɛmənstreɪt/", sentence: "The science teacher demonstrated the experiment.", translation: "বিজ্ঞান শিক্ষক পরীক্ষাটি প্রদর্শন করেছিলেন।" },
  { english: "deny", bangla: "অস্বীকার করা", phonetic: "/dɪˈnaɪ/", sentence: "He denied taking part in the gossip.", translation: "সে পরচর্চায় অংশ নেওয়ার কথা অস্বীকার করেছিল।" },
  { english: "depart", bangla: "প্রস্থান করা", phonetic: "/dɪˈpɑːrt/", sentence: "The steamer departs for Barisal at night.", translation: "স্টিমারটি রাতে বরিশালের উদ্দেশ্যে প্রস্থান করে।" },
  { english: "depend", bangla: "নির্ভর করা", phonetic: "/dɪˈpɛnd/", sentence: "Success depends on persistent and honest hard work.", translation: "সাফল্য অবিচল ও সৎ কঠোর পরিশ্রমের উপর নির্ভর করে।" },
  { english: "depict", bangla: "চিত্রিত করা", phonetic: "/dɪˈpɪkt/", sentence: "The novel depicts rural life in Bangladesh.", translation: "উপন্যাসটি বাংলাদেশের গ্রামীণ জীবনকে চিত্রিত করে।" },
  { english: "deposit", bangla: "জমা রাখা", phonetic: "/dɪˈpɒzɪt/", sentence: "She deposits a portion of her savings monthly.", translation: "সে প্রতি মাসে তার সঞ্চয়ের একটি অংশ জমা রাখে।" },
  { english: "derive", bangla: "উৎস থেকে লাভ করা / আহরণ করা", phonetic: "/dɪˈraɪv/", sentence: "Human beings derive nourishment from natural foods.", translation: "মানুষ প্রাকৃতিক খাবার থেকে পুষ্টি আহরণ করে।" },
  { english: "describe", bangla: "বর্ণনা করা", phonetic: "/dɪˈskraɪb/", sentence: "Describe the historic monuments of our land.", translation: "আমাদের দেশের ঐতিহাসিক নিদর্শনগুলো বর্ণনা করো।" },
  { english: "deserve", bangla: "যোগ্য হওয়া", phonetic: "/dɪˈzɜːrv/", sentence: "Diligent students deserve high appreciation.", translation: "পরিশ্রমী শিক্ষার্থীরা উচ্চ প্রশংসার যোগ্য।" },
  { english: "design", bangla: "নকশা তৈরি করা", phonetic: "/dɪˈzaɪn/", sentence: "Architects design earthquake-resistant buildings.", translation: "স্থপতিরা ভূমিকম্প সহনশীল ভবনের নকশা তৈরি করেন।" },
  { english: "desire", bangla: "আকাঙ্ক্ষা করা", phonetic: "/dɪˈzaɪər/", sentence: "Every student desires good academic results.", translation: "প্রতিটি শিক্ষার্থী ভালো প্রাতিষ্ঠানিক ফলাফল আকাঙ্ক্ষা করে।" },
  { english: "destroy", bangla: "ধ্বংস করা", phonetic: "/dɪˈstrɔɪ/", sentence: "Carelessness can destroy precious forest ecosystems.", translation: "অসতর্কতা মূল্যবান বনাঞ্চলের বাস্তুতন্ত্র ধ্বংস করতে পারে।" },
  { english: "detect", bangla: "শনাক্ত করা", phonetic: "/dɪˈtɛkt/", sentence: "Doctors detect diseases using modern scanners.", translation: "চিকিৎসকরা আধুনিক স্ক্যানার ব্যবহার করে রোগ শনাক্ত করেন।" },
  { english: "deter", bangla: "বাধা দেওয়া / নিবৃত্ত করা", phonetic: "/dɪˈtɜːr/", sentence: "Severe punishment deters crime in society.", translation: "কঠোর শাস্তি সমাজে অপরাধ থেকে নিবৃত্ত করে।" },
  { english: "develop", bangla: "উন্নয়ন করা / বিকাশ করা", phonetic: "/dɪˈvɛləp/", sentence: "Continuous practice develops your English fluency.", translation: "ধারাবাহিক অনুশীলন তোমার ইংরেজি সাবলীলতা বিকাশ করে।" },
  { english: "devote", bangla: "উৎসর্গ করা", phonetic: "/dɪˈvoʊt/", sentence: "Devote your spare time to acquiring new skills.", translation: "নতুন দক্ষতা অর্জনে তোমার অবসর সময় উৎসর্গ করো।" },
  { english: "dictate", bangla: "শ্রুতিলিপি দেওয়া / নির্দেশ দেওয়া", phonetic: "/dɪkˈteɪt/", sentence: "The teacher dictated vocabulary for spelling practice.", translation: "বানান অনুশীলনের জন্য শিক্ষক শব্দভাণ্ডার শ্রুতিলিপি দিয়েছিলেন।" },
  { english: "differ", bangla: "ভিন্ন হওয়া", phonetic: "/ˈdɪfər/", sentence: "Opinions differ, but respect should remain intact.", translation: "মতামত ভিন্ন হতে পারে, তবে পারস্পরিক শ্রদ্ধা অক্ষুণ্ণ থাকা উচিত।" },
  { english: "digest", bangla: "হজম করা", phonetic: "/daɪˈdʒɛst/", sentence: "Drink water to help your body digest food easily.", translation: "খাবার সহজে হজম করতে শরীরকে সাহায্য করার জন্য পানি পান করুন।" },
  { english: "diminish", bangla: "হ্রাস পাওয়া", phonetic: "/dɪˈmɪnɪʃ/", sentence: "Patience diminishes tension during stressful days.", translation: "ধৈর্য মানসিক চাপের দিনগুলোতে উদ্বেগ হ্রাস করে।" },
  { english: "direct", bangla: "পরিচালনা করা / পথ দেখানো", phonetic: "/daɪˈrɛkt/", sentence: "The traffic police directed the vehicles smoothly.", translation: "ট্রাফিক পুলিশ যানবাহনগুলো সুশৃঙ্খলভাবে পরিচালনা করেছিল।" },
  { english: "disagree", bangla: "দ্বিমত পোষণ করা", phonetic: "/ˌdɪsəˈɡriː/", sentence: "We can disagree politely without being hostile.", translation: "শত্রুভাবাপন্ন না হয়েও আমরা মার্জিতভাবে দ্বিমত পোষণ করতে পারি।" },
  { english: "disappear", bangla: "অদৃশ্য হওয়া", phonetic: "/ˌdɪsəˈpɪər/", sentence: "The deer disappeared behind the tall green grass.", translation: "হরিণটি লম্বা সবুজ ঘাসের আড়ালে অদৃশ্য হয়ে গেল।" },
  { english: "disclose", bangla: "উন্মোচন করা", phonetic: "/dɪsˈkloʊz/", sentence: "The officer disclosed official findings to the press.", translation: "কর্মকর্তা সংবাদমাধ্যমের কাছে সরকারি তথ্য উন্মোচন করেছিলেন।" },
  { english: "discover", bangla: "আবিষ্কার করা", phonetic: "/dɪˈskʌvər/", sentence: "Explorers discovered an ancient stone cave.", translation: "অভিযাত্রীরা একটি প্রাচীন পাথুরে গুহা আবিষ্কার করেছিলেন।" },
  { english: "discuss", bangla: "আলোচনা করা", phonetic: "/dɪˈskʌs/", sentence: "Teachers discuss moral education in the assembly.", translation: "শিক্ষকরা সমাবেশে নৈতিক শিক্ষা নিয়ে আলোচনা করেন।" },
  { english: "dismiss", bangla: "বরখাস্ত করা / শেষ করা", phonetic: "/dɪsˈmɪs/", sentence: "The headmaster dismissed the class at four.", translation: "প্রধান শিক্ষক চারটায় ক্লাস শেষ করেছিলেন।" },
  { english: "display", bangla: "প্রদর্শন করা", phonetic: "/dɪˈspleɪ/", sentence: "Museums display rare historical artifacts.", translation: "জাদুঘরগুলো বিরল ঐতিহাসিক নিদর্শন প্রদর্শন করে।" },
  { english: "distinguish", bangla: "পার্থক্য করা / বিশিষ্ট করা", phonetic: "/dɪˈstɪŋɡwɪʃ/", sentence: "A wise person can distinguish right from wrong.", translation: "একজন জ্ঞানী মানুষ সঠিক ও ভুলের পার্থক্য করতে পারেন।" },
  { english: "distribute", bangla: "বিতরণ করা", phonetic: "/dɪˈstrɪbjuːt/", sentence: "They distributed warm clothes to chilly winter victims.", translation: "তারা শীতবস্ত্র বিতরণ করেছিল শীতার্ত মানুষের মাঝে।" },
  { english: "dive", bangla: "ডুব দেওয়া", phonetic: "/daɪv/", sentence: "The pearl diver dived deep into the blue ocean.", translation: "মুক্তা শিকারি নীল সাগরের গভীরে ডুব দিয়েছিল।" },
  { english: "divide", bangla: "ভাগ করা", phonetic: "/dɪˈvaɪd/", sentence: "Divide your revision syllabus equally over the week.", translation: "সপ্তাহজুড়ে তোমার পাঠ্যসূচি সমানভাবে ভাগ করে নাও।" },
  { english: "donate", bangla: "দান করা", phonetic: "/doʊˈneɪt/", sentence: "Generous people donate books to local libraries.", translation: "উদার ব্যক্তিরা স্থানীয় লাইব্রেরিতে বই দান করেন।" },
  { english: "drag", bangla: "টানা / টেনে আনা", phonetic: "/dræɡ/", sentence: "He dragged the heavy sack into the storehouse.", translation: "সে ভারী বস্তাটি গুদামঘরে টেনে এনেছিল।" },
  { english: "drain", bangla: "নিষ্কাশন করা", phonetic: "/dreɪn/", sentence: "Workers drained waterlogged streets after heavy rain.", translation: "ভারী বৃষ্টির পর শ্রমিকরা জলাবদ্ধ রাস্তা নিষ্কাশন করেছিলেন।" },
  { english: "dream", bangla: "স্বপ্ন দেখা", phonetic: "/driːm/", sentence: "Dream high and take practical steps every day.", translation: "উঁচু স্বপ্ন দেখুন এবং প্রতিদিন বাস্তব পদক্ষেপ নিন।" },
  { english: "dress", bangla: "পোশাক পরা", phonetic: "/drɛs/", sentence: "Students dress in neat uniforms for the parade.", translation: "কুচকাওয়াজের জন্য শিক্ষার্থীরা পরিচ্ছন্ন পোশাক পরে।" },
  { english: "drink", bangla: "পান করা", phonetic: "/drɪŋk/", sentence: "Drink boiled or filtered water for good health.", translation: "সুস্বাস্থ্যের জন্য ফোটানো বা পরিশোধিত পানি পান করুন।" },
  { english: "drive", bangla: "চালানো", phonetic: "/draɪv/", sentence: "Drive safely and follow the highway guidelines.", translation: "নিরাপদে গাড়ি চালান এবং মহাসড়কের নির্দেশিকা মেনে চলুন।" },
  { english: "drop", bangla: "ফেলে দেওয়া / ঝরে পড়া", phonetic: "/drɒp/", sentence: "Dewdrops drop from leaves in the fresh morning.", translation: "স্নিগ্ধ সকালে পাতা থেকে শিশিরবিন্দু ঝরে পড়ে।" },

  // E
  { english: "earn", bangla: "উপার্জন করা", phonetic: "/ɜːrn/", sentence: "Honest people earn their livelihood with dignity.", translation: "সৎ মানুষ সম্মানের সাথে তাদের জীবিকা উপার্জন করেন।" },
  { english: "echo", bangla: "প্রতিধ্বনি করা", phonetic: "/ˈɛkoʊ/", sentence: "His joyous laughter echoed throughout the valley.", translation: "তার আনন্দময় হাসি উপত্যকাজুড়ে প্রতিধ্বনিত হয়েছিল।" },
  { english: "educate", bangla: "শিক্ষিত করা", phonetic: "/ˈɛdʒukeɪt/", sentence: "Parents educate children with love and patience.", translation: "পিতা-মাতা স্নেহ ও ধৈর্যের সাথে সন্তানদের শিক্ষিত করেন।" },
  { english: "elaborate", bangla: "বিস্তারিত বলা", phonetic: "/ɪˈlæbəreɪt/", sentence: "Please elaborate on your points during the presentation.", translation: "উপস্থাপনার সময় অনুগ্রহ করে তোমার যুক্তিগুলো বিস্তারিত বলো।" },
  { english: "elect", bangla: "নির্বাচিত করা", phonetic: "/ɪˈlɛkt/", sentence: "Voters elected their community representative.", translation: "ভোটাররা তাদের সম্প্রদায় প্রতিনিধি নির্বাচন করেছিলেন।" },
  { english: "elevate", bangla: "উন্নত করা / উচ্চে তোলা", phonetic: "/ˈɛlɪveɪt/", sentence: "Education elevates the mind and soul of humanity.", translation: "শিক্ষা মানবজাতির মন ও আত্মাকে উন্নত করে।" },
  { english: "eliminate", bangla: "বর্জন করা / দূর করা", phonetic: "/ɪˈlɪmɪneɪt/", sentence: "Proper sanitation eliminates infectious diseases.", translation: "সঠিক স্যানিটেশন সংক্রামক রোগ দূর করে।" },
  { english: "embark", bangla: "যাত্রা শুরু করা", phonetic: "/ɪmˈbɑːrk/", sentence: "Students embarked on an educational tour.", translation: "শিক্ষার্থীরা একটি শিক্ষাসফরে যাত্রা শুরু করেছিল।" },
  { english: "embarrass", bangla: "বিব্রত করা", phonetic: "/ɪmˈbærəs/", sentence: "Never embarrass anyone in front of others.", translation: "অন্যের সামনে কখনোই কাউকে বিব্রত করবেন না।" },
  { english: "embrace", bangla: "আলিঙ্গন করা / গ্রহণ করা", phonetic: "/ɪmˈbreɪs/", sentence: "Embrace good habits and reject harmful ones.", translation: "ভালো অভ্যাস গ্রহণ করুন এবং ক্ষতিকর অভ্যাস বর্জন করুন।" },
  { english: "emerge", bangla: "উঠে আসা / আবির্ভূত হওয়া", phonetic: "/ɪˈmɜːrdʒ/", sentence: "The sun emerged from behind the morning clouds.", translation: "সকালের মেঘের আড়াল থেকে সূর্য আবির্ভূত হলো।" },
  { english: "emphasize", bangla: "গুরুত্ব আরোপ করা", phonetic: "/ˈɛmfəsaɪz/", sentence: "Teachers emphasize the habit of reading daily.", translation: "শিক্ষকরা প্রতিদিন বই পড়ার অভ্যাসের ওপর গুরুত্ব দেন।" },
  { english: "employ", bangla: "নিয়োগ করা / কাজে লাগানো", phonetic: "/ɪmˈplɔɪ/", sentence: "The new factory employs many skilled workers.", translation: "নতুন কারখানাটি অনেক দক্ষ শ্রমিক নিয়োগ করেছে।" },
  { english: "enable", bangla: "সক্ষম করা", phonetic: "/ɪˈneɪbl/", sentence: "Digital tools enable students to learn remotely.", translation: "ডিজিটাল সরঞ্জাম শিক্ষার্থীদের দূরশিক্ষণে সক্ষম করে।" },
  { english: "encourage", bangla: "উৎসাহ দেওয়া", phonetic: "/ɪnˈkʌrɪdʒ/", sentence: "Always encourage friends when they face difficulties.", translation: "বন্ধুরা সমস্যায় পড়লে সর্বদা তাদের উৎসাহিত করুন।" },
  { english: "endure", bangla: "সহ্য করা / টিকে থাকা", phonetic: "/ɪnˈdjʊər/", sentence: "Patient people endure hardships without complaints.", translation: "ধৈর্যশীল মানুষ অভিযোগ ছাড়াই কষ্ট সহ্য করেন।" },
  { english: "engage", bangla: "যুক্ত হওয়া / ব্যস্ত থাকা", phonetic: "/ɪnˈɡeɪdʒ/", sentence: "Engage yourself in productive activities daily.", translation: "প্রতিদিন উৎপাদনশীল কর্মকাণ্ডে নিজেকে যুক্ত রাখুন।" },
  { english: "enhance", bangla: "বৃদ্ধি করা / উন্নত করা", phonetic: "/ɪnˈhæns/", sentence: "Reading books enhances your language proficiency.", translation: "বই পড়া আপনার ভাষার দক্ষতা বৃদ্ধি করে।" },
  { english: "enjoy", bangla: "উপভোগ করা", phonetic: "/ɪnˈdʒɔɪ/", sentence: "We enjoyed the refreshing morning breeze.", translation: "আমরা সতেজ সকালের বাতাস উপভোগ করেছিলাম।" },
  { english: "enlighten", bangla: "আলোকিত করা", phonetic: "/ɪnˈlaɪtn/", sentence: "Moral education enlightens human conscience.", translation: "নৈতিক শিক্ষা মানুষের বিবেককে আলোকিত করে।" },
  { english: "enrich", bangla: "সমৃদ্ধ করা", phonetic: "/ɪnˈrɪtʃ/", sentence: "Learning vocabulary enriches your speaking power.", translation: "শব্দভাণ্ডার শেখা আপনার কথ্য দক্ষতাকে সমৃদ্ধ করে।" },
  { english: "enter", bangla: "প্রবেশ করা", phonetic: "/ˈɛntər/", sentence: "Enter the examination hall quietly.", translation: "শান্তভাবে পরীক্ষার হলে প্রবেশ করুন।" },
  { english: "entertain", bangla: "বিনোদন দেওয়া", phonetic: "/ˌɛntərˈteɪn/", sentence: "The clown entertained children at the birthday party.", translation: "জোকার জন্মদিনের অনুষ্ঠানে শিশুদের বিনোদন দিয়েছিল।" },
  { english: "equip", bangla: "সজ্জিত করা / প্রস্তুত করা", phonetic: "/ɪˈkwɪp/", sentence: "Schools equip learners with modern computer skills.", translation: "বিদ্যালয় শিক্ষার্থীদের আধুনিক কম্পিউটার দক্ষতায় সজ্জিত করে।" },
  { english: "erase", bangla: "মুছে ফেলা", phonetic: "/ɪˈreɪs/", sentence: "Use an eraser to erase pencil marks neatly.", translation: "পেন্সিলের দাগ সুন্দরভাবে মুছতে ইরেজার ব্যবহার করুন।" },
  { english: "escape", bangla: "পলায়ন করা", phonetic: "/ɪˈskeɪp/", sentence: "The rabbit escaped from the cage.", translation: "খরগোশটি খাঁচা থেকে পলায়ন করেছিল।" },
  { english: "establish", bangla: "প্রতিষ্ঠা করা", phonetic: "/ɪˈstæblɪʃ/", sentence: "The community established a charitable hospital.", translation: "এলাকাবাসী একটি দাতব্য হাসপাতাল প্রতিষ্ঠা করেছিলেন।" },
  { english: "evaluate", bangla: "মূল্যায়ন করা", phonetic: "/ɪˈvæljueɪt/", sentence: "Teachers evaluate answer scripts with fairness.", translation: "শিক্ষকরা নিরপেক্ষতার সাথে উত্তরপত্র মূল্যায়ন করেন।" },
  { english: "examine", bangla: "পরীক্ষা করা", phonetic: "/ɪɡˈzæmɪn/", sentence: "Doctors examine patients with stethoscope.", translation: "চিকিৎসকরা স্টেথোস্কোপ দিয়ে রোগীদের পরীক্ষা করেন।" },
  { english: "exceed", bangla: "অতিক্রম করা / বেশি হওয়া", phonetic: "/ɪkˈsiːd/", sentence: "Never exceed the prescribed vehicle speed limit.", translation: "যানবাহনের নির্ধারিত গতিসীমা কখনো অতিক্রম করবেন না।" },
  { english: "excel", bangla: "শ্রেষ্ঠত্ব অর্জন করা", phonetic: "/ɪkˈsɛl/", sentence: "Diligence helps students excel in studies.", translation: "অধ্যবসায় শিক্ষার্থীদের পড়াশোনায় শ্রেষ্ঠত্ব অর্জনে সহায়তা করে।" },
  { english: "exchange", bangla: "বিনিময় করা", phonetic: "/ɪksˈtʃeɪndʒ/", sentence: "Friends exchanged books during library hour.", translation: "লাইব্রেরির সময় বন্ধুরা বই বিনিময় করেছিল।" },
  { english: "excite", bangla: "উত্তেজিত করা / উদ্দীপিত করা", phonetic: "/ɪkˈsaɪt/", sentence: "The upcoming sports fest excites all students.", translation: "আসন্ন ক্রীড়া উৎসব সকল শিক্ষার্থীকে উদ্দীপিত করে।" },
  { english: "exclude", bangla: "বাদ দেওয়া", phonetic: "/ɪkˈskluːd/", sentence: "Do not exclude anyone from group activities.", translation: "দলীয় কাজ থেকে কাউকেই বাদ দেবেন না।" },
  { english: "excuse", bangla: "ক্ষমা করা / রেহাই দেওয়া", phonetic: "/ɪkˈskjuːz/", sentence: "Excuse my delay due to road traffic.", translation: "রাস্তার যানজটের কারণে আমার দেরির জন্য ক্ষমা করবেন।" },
  { english: "execute", bangla: "বাস্তবায়ন করা", phonetic: "/ˈɛksɪkjuːt/", sentence: "Engineers executed the project according to plan.", translation: "প্রকৌশলীরা পরিকল্পনা অনুযায়ী প্রকল্পটি বাস্তবায়ন করেছিলেন।" },
  { english: "exercise", bangla: "ব্যায়াম করা", phonetic: "/ˈɛksərsaɪz/", sentence: "Exercise daily to maintain physical and mental fitness.", translation: "শারীরিক ও মানসিক সুস্থতা বজায় রাখতে প্রতিদিন ব্যায়াম করুন।" },
  { english: "exert", bangla: "প্রয়োগ করা / খাটা", phonetic: "/ɪɡˈzɜːrt/", sentence: "Exert your utmost effort to achieve excellence.", translation: "শ্রেষ্ঠত্ব অর্জনে তোমার সর্বোচ্চ প্রচেষ্টা প্রয়োগ করো।" },
  { english: "exhibit", bangla: "প্রদর্শন করা", phonetic: "/ɪɡˈzɪbɪt/", sentence: "The museum exhibits rare prehistoric fossils.", translation: "জাদুঘরটি বিরল প্রাগৈতিহাসিক জীবাশ্ম প্রদর্শন করে।" },
  { english: "exist", bangla: "বিদ্যমান থাকা / বেঁচে থাকা", phonetic: "/ɪɡˈzɪst/", sentence: "Fish cannot exist outside water.", translation: "পানির বাইরে মাছ বেঁচে থাকতে পারে না।" },
  { english: "expand", bangla: "সম্প্রসারিত করা", phonetic: "/ɪkˈspænd/", sentence: "Metals expand when heated.", translation: "উত্তপ্ত হলে ধাতু সম্প্রসারিত হয়।" },
  { english: "expect", bangla: "প্রত্যাশা করা", phonetic: "/ɪkˈspɛkt/", sentence: "Teachers expect honest performance from all pupils.", translation: "শিক্ষকরা সকল শিক্ষার্থীর কাছ থেকে সৎ কর্মক্ষমতা প্রত্যাশা করেন।" },
  { english: "experience", bangla: "অভিজ্ঞতা লাভ করা", phonetic: "/ɪkˈspɪəriəns/", sentence: "Travelers experience diverse cultures across the globe.", translation: "ভ্রমণকারীরা বিশ্বজুড়ে বৈচিত্র্যময় সংস্কৃতির অভিজ্ঞতা লাভ করেন।" },
  { english: "explain", bangla: "ব্যাখ্যা করা", phonetic: "/ɪkˈspleɪn/", sentence: "Explain the main theme in simple English words.", translation: "সহজ ইংরেজি শব্দে মূল বিষয়টি ব্যাখ্যা করো।" },
  { english: "explore", bangla: "অন্বেষণ করা", phonetic: "/ɪkˈsplɔːr/", sentence: "Young researchers explore new scientific horizons.", translation: "তরুণ গবেষকরা নতুন বৈজ্ঞানিক দিগন্ত অন্বেষণ করেন।" },
  { english: "export", bangla: "রপ্তানি করা", phonetic: "/ɪkˈspɔːrt/", sentence: "Bangladesh exports high-quality tea and jute.", translation: "বাংলাদেশ উচ্চমানের চা এবং পাট রপ্তানি করে।" },
  { english: "expose", bangla: "উন্মোচিত করা", phonetic: "/ɪkˈspoʊz/", sentence: "Investigative journalists exposed the corrupt scheme.", translation: "অনুসন্ধানী সাংবাদিকরা দুর্নীতির নকশা উন্মোচিত করেছিলেন।" },
  { english: "express", bangla: "প্রকাশ করা", phonetic: "/ɪkˈsprɛs/", sentence: "Express your gratitude towards kind mentors.", translation: "সদয় শিক্ষকদের প্রতি তোমার কৃতজ্ঞতা প্রকাশ করো।" },
  { english: "extend", bangla: "প্রসারিত করা", phonetic: "/ɪkˈstɛnd/", sentence: "The railway line was extended to the border.", translation: "রেললাইনটি সীমান্ত পর্যন্ত প্রসারিত করা হয়েছিল।" },
  { english: "extract", bangla: "নিষ্কাশন করা", phonetic: "/ɪkˈstrækt/", sentence: "Bees extract sweet nectar from blossoms.", translation: "মৌমাছিরা ফুলের কুঁড়ি থেকে মিষ্টি মধু নিষ্কাশন করে।" },

  // F
  { english: "facilitate", bangla: "সহজতর করা", phonetic: "/fəˈsɪlɪteɪt/", sentence: "Modern libraries facilitate student learning greatly.", translation: "আধুনিক গ্রন্থাগার শিক্ষার্থীদের শিক্ষণকে ব্যাপকভাবে সহজতর করে।" },
  { english: "fade", bangla: "মলিন হওয়া", phonetic: "/feɪd/", sentence: "Colors of old pictures fade over time.", translation: "সময়ের সাথে সাথে পুরানো ছবির রঙ মলিন হয়ে যায়।" },
  { english: "fail", bangla: "ব্যর্থ হওয়া", phonetic: "/feɪl/", sentence: "Do not fear to fail; learn and rise again.", translation: "ব্যর্থ হতে ভয় পাবেন না; শিখুন এবং আবার ঘুরে দাঁড়ান।" },
  { english: "faint", bangla: "অজ্ঞান হওয়া", phonetic: "/feɪnt/", sentence: "The thirsty traveler fainted in the scorching sun.", translation: "তৃষ্ণার্ত পথিক প্রখর রোদে অজ্ঞান হয়ে পড়েছিল।" },
  { english: "fasten", bangla: "আটকে দেওয়া / বাঁধা", phonetic: "/ˈfɑːsn/", sentence: "Fasten your seat belt before the plane takes off.", translation: "বিমান ওড়ার আগে আপনার সিটবেল্ট বেঁধে নিন।" },
  { english: "favour", bangla: "অনুকূল হওয়া / অনুগ্রহ করা", phonetic: "/ˈfeɪvər/", sentence: "Fortune favors the bold and hard-working.", translation: "ভাগ্য সাহসী ও পরিশ্রমীদের অনুকূলে থাকে।" },
  { english: "fear", bangla: "ভয় পাওয়া", phonetic: "/fɪər/", sentence: "True patriots fear nothing when serving the nation.", translation: "সত্যিকারের দেশপ্রেমিকরা দেশের সেবায় কোনো কিছুকে ভয় পান না।" },
  { english: "feed", bangla: "খাওয়ানো", phonetic: "/fiːd/", sentence: "Feed stray animals with kindness and care.", translation: "দয়া ও যত্নের সাথে পথপ্রাণীদের খাবার খাওয়ান।" },
  { english: "feel", bangla: "অনুভব করা", phonetic: "/fiːl/", sentence: "I feel delighted to witness your grand success.", translation: "তোমার মহতী সাফল্য প্রত্যক্ষ করতে পেরে আমি আনন্দ অনুভব করছি।" },
  { english: "fetch", bangla: "গিয়ে নিয়ে আসা", phonetic: "/fɛtʃ/", sentence: "The obedient boy fetched a glass of water for his guest.", translation: "বাধ্য ছেলেটি অতিথির জন্য এক গ্লাস পানি এনে দিয়েছিল।" },
  { english: "fight", bangla: "লড়াই করা", phonetic: "/faɪt/", sentence: "People fought heroically for independence in 1971.", translation: "১৯৭১ সালে মানুষ স্বাধীনতার জন্য বীরত্বের সাথে লড়াই করেছিল।" },
  { english: "fill", bangla: "পূর্ণ করা", phonetic: "/fɪl/", sentence: "Fill the clay pot with crystal-clear water.", translation: "মাটির পাত্রটি স্ফটিক-স্বচ্ছ পানি দিয়ে পূর্ণ করো।" },
  { english: "filter", bangla: "পরিশোধন করা", phonetic: "/ˈfɪltər/", sentence: "Filter drinking water to prevent waterborne diseases.", translation: "পানিবাহিত রোগ প্রতিরোধে খাবার পানি ফিল্টার করুন।" },
  { english: "finance", bangla: "অর্থায়ন করা", phonetic: "/ˈfaɪnæns/", sentence: "The bank finances small business entrepreneurs.", translation: "ব্যাংক ক্ষুদ্র ব্যবসায়িক উদ্যোক্তাদের অর্থায়ন করে।" },
  { english: "find", bangla: "খুঁজে পাওয়া", phonetic: "/faɪnd/", sentence: "Diligent search will find the right answer.", translation: "নিষ্ঠাবান অনুসন্ধান সঠিক উত্তর খুঁজে বের করবে।" },
  { english: "finish", bangla: "সম্পন্ন করা / শেষ করা", phonetic: "/ˈfɪnɪʃ/", sentence: "Finish your daily revision before sleeping.", translation: "ঘুমানোর আগে তোমার দৈনন্দিন পুনরাবৃত্তি সম্পন্ন করো।" },
  { english: "fit", bangla: "উপযুক্ত হওয়া / খাপ খাওয়া", phonetic: "/fɪt/", sentence: "These shoes fit comfortably on my feet.", translation: "এই জুতো জোড়া আমার পায়ে আরামদায়কভাবে খাপ খায়।" },
  { english: "fix", bangla: "মেরামত করা / ঠিক করা", phonetic: "/fɪks/", sentence: "The technician fixed the broken electric fan.", translation: "কারিগরি কর্মী নষ্ট বৈদ্যুতিক পাখাটি মেরামত করেছিলেন।" },
  { english: "flash", bangla: "ঝলকানি দেওয়া", phonetic: "/flæʃ/", sentence: "Lightning flashed brightly during the stormy night.", translation: "ঝড়ো রাতে আকাশে বিজলি তীব্রভাবে চমকে উঠেছিল।" },
  { english: "flee", bangla: "পালিয়ে যাওয়া", phonetic: "/fliː/", sentence: "The thief fled when police arrived at the scene.", translation: "ঘটনাস্থলে পুলিশ পৌঁছালে চোর পালিয়ে গিয়েছিল।" },
  { english: "float", bangla: "ভাসা", phonetic: "/floʊt/", sentence: "Dry wooden leaves float gently on river currents.", translation: "শুকনো কাঠের পাতা নদীর স্রোতে আলতো করে ভাসে।" },
  { english: "flood", bangla: "প্লাবিত করা", phonetic: "/flʌd/", sentence: "Monsoon rains flood the low-lying agricultural fields.", translation: "বর্ষার বৃষ্টি নিম্নাঞ্চলের ফসলি জমি প্লাবিত করে।" },
  { english: "flow", bangla: "প্রবাহিত হওয়া", phonetic: "/floʊ/", sentence: "The river Padma flows calmly toward the sea.", translation: "পদ্মা নদী শান্তভাবে সাগরের দিকে প্রবাহিত হয়।" },
  { english: "fly", bangla: "ওড়া", phonetic: "/flaɪ/", sentence: "Kites fly high in the breezy autumn sky.", translation: "শরতের মিষ্টি বাতাসে ঘুড়িগুলো আকাশে উঁচুতে ওড়ে।" },
  { english: "focus", bangla: "মনোনিবেশ করা", phonetic: "/ˈfoʊkəs/", sentence: "Focus on learning grammar rules with dedication.", translation: "নিষ্ঠার সাথে ব্যাকরণের নিয়ম শেখার প্রতি মনোনিবেশ করুন।" },
  { english: "fold", bangla: "ভাঁজ করা", phonetic: "/foʊld/", sentence: "Fold your clothes neatly before putting them in the wardrobe.", translation: "আলমারিতে রাখার আগে তোমার জামাকাপড় পরিপাটি করে ভাঁজ করো।" },
  { english: "follow", bangla: "অনুসরণ করা", phonetic: "/ˈfɒloʊ/", sentence: "Follow the footsteps of great historical scholars.", translation: "মহান ঐতিহাসিক পণ্ডিতদের পদচিহ্ন অনুসরণ করো।" },
  { english: "forbid", bangla: "নিষেধ করা", phonetic: "/fərˈbɪd/", sentence: "School discipline forbids littering on the ground.", translation: "বিদ্যালয়ের শৃঙ্খলা মাঠে ময়লা ফেলা নিষেধ করে।" },
  { english: "force", bangla: "বাধ্য করা / বলপ্রয়োগ করা", phonetic: "/fɔːrs/", sentence: "Never force children against their natural talents.", translation: "শিশুদের তাদের স্বাভাবিক প্রতিভার বিরুদ্ধে কখনো বাধ্য করবেন না।" },
  { english: "forecast", bangla: "পূর্বাভাস দেওয়া", phonetic: "/ˈfɔːrkæst/", sentence: "Weathermen forecast sunny weather for the weekend.", translation: "আবহাওয়াবিদরা সপ্তাহান্তে রৌদ্রোজ্জ্বল আবহাওয়ার পূর্বাভাস দিয়েছেন।" },
  { english: "foresee", bangla: "পূর্বেই দেখতে পাওয়া", phonetic: "/fɔːrˈsiː/", sentence: "Wise leaders foresee future difficulties and prepare.", translation: "জ্ঞানী নেতারা ভবিষ্যতের সমস্যা আগেই দেখতে পান ও প্রস্তুতি নেন।" },
  { english: "forget", bangla: "ভুলে যাওয়া", phonetic: "/fərˈɡɛt/", sentence: "Do not forget to say 'Bismillah' before meals.", translation: "খাবার আগে 'বিসমিল্লাহ' বলতে ভুলবেন না।" },
  { english: "forgive", bangla: "ক্ষমা করা", phonetic: "/fərˈɡɪv/", sentence: "To forgive others is a mark of noble character.", translation: "অন্যদের ক্ষমা করা মহৎ চরিত্রের পরিচায়ক।" },
  { english: "form", bangla: "গঠন করা", phonetic: "/fɔːrm/", sentence: "Students formed an English conversation club.", translation: "শিক্ষার্থীরা একটি ইংরেজি কথপোকথন ক্লাব গঠন করেছিল।" },
  { english: "found", bangla: "প্রতিষ্ঠা করা", phonetic: "/faʊnd/", sentence: "Philanthropists founded this school for village children.", translation: "হিতৈষী ব্যক্তিরা গ্রামের শিশুদের জন্য এই বিদ্যালয়টি প্রতিষ্ঠা করেছিলেন।" },
  { english: "freeze", bangla: "জমে যাওয়া", phonetic: "/friːz/", sentence: "Ponds freeze in extremely cold northern winters.", translation: "উত্তরের চরম ঠান্ডা শীতে পুকুরগুলো জমে বরফ হয়ে যায়।" },
  { english: "frighten", bangla: "ভয় দেখানো", phonetic: "/ˈfraɪtn/", sentence: "Sudden thunder frightened the stray cat.", translation: "হঠাৎ বজ্রপাত পথবিড়ালটিকে ভয় দেখিয়েছিল।" },
  { english: "fulfill", bangla: "পূরণ করা", phonetic: "/fʊlˈfɪl/", sentence: "Work hard to fulfill your parents' honest expectations.", translation: "তোমার পিতা-মাতার সৎ প্রত্যাশা পূরণ করতে কঠোর পরিশ্রম করো।" }
];

console.log('Verbs list ready, count:', verbVocabList.length);
