const fs = require('fs');

// We will build comprehensive list of adjectives and verbs with Bengali meaning, phonetic, sentence & translation
// to reach exactly 1260 authentic, high-quality educational vocabulary items.

const baseVocab = [
  // --- VERBS: ACTION, DAILY LIFE, STUDY, WORK ---
  { english: "accept", bangla: "গ্রহণ করা", phonetic: "/əkˈsɛpt/", sentence: "She accepted the proposal gladly.", translation: "সে আনন্দের সাথে প্রস্তাবটি গ্রহণ করেছিল।" },
  { english: "achieve", bangla: "অর্জন করা", phonetic: "/əˈtʃiːv/", sentence: "He worked hard to achieve success.", translation: "সাফল্য অর্জন করতে সে কঠোর পরিশ্রম করেছিল।" },
  { english: "acquire", bangla: "অর্জন করা / লাভ করা", phonetic: "/əˈkwaɪər/", sentence: "Students acquire knowledge through reading.", translation: "শিক্ষার্থীরা পড়ার মাধ্যমে জ্ঞান অর্জন করে।" },
  { english: "act", bangla: "কাজ করা / অভিনয় করা", phonetic: "/ækt/", sentence: "You must act quickly in an emergency.", translation: "জরুরি পরিস্থিতিতে তোমাকে দ্রুত কাজ করতে হবে।" },
  { english: "adapt", bangla: "খাপ খাওয়ানো", phonetic: "/əˈdæpt/", sentence: "Animals adapt to their environment.", translation: "প্রাণীরা তাদের পরিবেশের সাথে খাপ খাইয়ে নেয়।" },
  { english: "add", bangla: "যোগ করা", phonetic: "/æd/", sentence: "Please add some sugar to the tea.", translation: "দয়া করে চায়ে কিছু চিনি যোগ করুন।" },
  { english: "admire", bangla: "প্রশংসা করা", phonetic: "/ədˈmaɪər/", sentence: "We admire his honesty and courage.", translation: "আমরা তার সততা ও সাহসের প্রশংসা করি।" },
  { english: "admit", bangla: "স্বীকার করা / ভর্তি করা", phonetic: "/ədˈmɪt/", sentence: "He admitted his mistake politely.", translation: "সে ভদ্রভাবে তার ভুল স্বীকার করেছিল।" },
  { english: "adopt", bangla: "দত্তক নেওয়া / গ্রহণ করা", phonetic: "/əˈdɒpt/", sentence: "They decided to adopt a new strategy.", translation: "তারা একটি নতুন কৌশল গ্রহণ করার সিদ্ধান্ত নিয়েছিল।" },
  { english: "advise", bangla: "উপদেশ দেওয়া", phonetic: "/ədˈvaɪz/", sentence: "The doctor advised him to rest.", translation: "ডাক্তার তাকে বিশ্রাম নেওয়ার উপদেশ দিয়েছিলেন।" },
  { english: "affect", bangla: "প্রভাবিত করা", phonetic: "/əˈfɛkt/", sentence: "Cold weather affects his health.", translation: "ঠান্ডা আবহাওয়া তার স্বাস্থ্যকে প্রভাবিত করে।" },
  { english: "afford", bangla: "সামর্থ্য থাকা", phonetic: "/əˈfɔːrd/", sentence: "We can afford to buy a new laptop.", translation: "আমাদের একটি নতুন ল্যাপটপ কেনার সামর্থ্য আছে।" },
  { english: "agree", bangla: "একমত হওয়া", phonetic: "/əˈɡriː/", sentence: "I agree with your suggestion completely.", translation: "আমি তোমার প্রস্তাবের সাথে সম্পূর্ণ একমত।" },
  { english: "allow", bangla: "অনুমতি দেওয়া", phonetic: "/əˈlaʊ/", sentence: "Parents should allow children to play.", translation: "বাবা-মায়ের উচিত শিশুদের খেলতে অনুমতি দেওয়া।" },
  { english: "announce", bangla: "ঘোষণা করা", phonetic: "/əˈnaʊns/", sentence: "The headmaster announced the holiday.", translation: "প্রধান শিক্ষক ছুটির ঘোষণা করেছিলেন।" },
  { english: "apologize", bangla: "ক্ষমা চাওয়া", phonetic: "/əˈpɒlədʒaɪz/", sentence: "You should apologize for your rude behavior.", translation: "তোমার অভদ্র আচরণের জন্য ক্ষমা চাওয়া উচিত।" },
  { english: "appear", bangla: "উপস্থিত হওয়া / মনে হওয়া", phonetic: "/əˈpɪər/", sentence: "The moon appeared behind the clouds.", translation: "মেঘের আড়াল থেকে চাঁদ দেখা গেল।" },
  { english: "apply", bangla: "আবেদন করা / প্রয়োগ করা", phonetic: "/əˈplaɪ/", sentence: "He applied for a scholarship.", translation: "সে একটি বৃত্তির জন্য আবেদন করেছিল।" },
  { english: "appreciate", bangla: "প্রশংসা করা / কদর করা", phonetic: "/əˈpriːʃieɪt/", sentence: "I appreciate your kind assistance.", translation: "আমি তোমার সদয় সহযোগিতার কদর করি।" },
  { english: "approach", bangla: "নিকটবর্তী হওয়া", phonetic: "/əˈproʊtʃ/", sentence: "The train approached the station slowly.", translation: "ট্রেনটি ধীরে ধীরে স্টেশনের নিকটবর্তী হলো।" },
  { english: "arrange", bangla: "ব্যবস্থা করা / সাজানো", phonetic: "/əˈreɪndʒ/", sentence: "They arranged a beautiful farewell party.", translation: "তারা একটি সুন্দর বিদায় অনুষ্ঠানের ব্যবস্থা করেছিল।" },
  { english: "arrive", bangla: "পৌঁছানো", phonetic: "/əˈraɪv/", sentence: "The guests arrived on time.", translation: "অতিথিরা সময়মতো পৌঁছেছিলেন।" },
  { english: "ask", bangla: "জিজ্ঞাসা করা", phonetic: "/ɑːsk/", sentence: "Feel free to ask any question.", translation: "নির্দ্বিধায় যেকোনো প্রশ্ন জিজ্ঞাসা করুন।" },
  { english: "assist", bangla: "সাহায্য করা", phonetic: "/əˈsɪst/", sentence: "She assisted the elderly lady across the street.", translation: "সে বৃদ্ধা মহিলাকে রাস্তা পার হতে সাহায্য করেছিল।" },
  { english: "assume", bangla: "ধরে নেওয়া", phonetic: "/əˈsjuːm/", sentence: "Do not assume things without evidence.", translation: "প্রমাণ ছাড়া কোনো কিছু ধরে নেবেন না।" },
  { english: "attack", bangla: "আক্রমণ করা", phonetic: "/əˈtæk/", sentence: "The army attacked the enemy camp.", translation: "সেনাবাহিনী শত্রু শিবিরে আক্রমণ করেছিল।" },
  { english: "attempt", bangla: "চেষ্টা করা", phonetic: "/əˈtɛmpt/", sentence: "He attempted to solve the hard puzzle.", translation: "সে কঠিন ধাঁধাটি সমাধান করার চেষ্টা করেছিল।" },
  { english: "attend", bangla: "উপস্থিত থাকা", phonetic: "/əˈtɛnd/", sentence: "Students must attend class regularly.", translation: "শিক্ষার্থীদের অবশ্যই নিয়মিত ক্লাসে উপস্থিত থাকতে হবে।" },
  { english: "attract", bangla: "আকর্ষণ করা", phonetic: "/əˈtrækt/", sentence: "Bright flowers attract honeybees.", translation: "উজ্জ্বল ফুল মৌমাছিদের আকর্ষণ করে।" },
  { english: "avoid", bangla: "এড়িয়ে চলা", phonetic: "/əˈvɔɪd/", sentence: "Avoid eating junk food daily.", translation: "প্রতিদিন ফাস্টফুড খাওয়া এড়িয়ে চলুন।" },
  { english: "bake", bangla: "সেঁকা / বেক করা", phonetic: "/beɪk/", sentence: "Mother baked a delicious chocolate cake.", translation: "মা একটি সুস্বাদু চকলেট কেক বেক করেছিলেন।" },
  { english: "balance", bangla: "ভারসাম্য রাখা", phonetic: "/ˈbæləns/", sentence: "Try to balance work and personal life.", translation: "কাজ ও ব্যক্তিগত জীবনের ভারসাম্য রাখার চেষ্টা করুন।" },
  { english: "bark", bangla: "ঘেউ ঘেউ করা", phonetic: "/bɑːrk/", sentence: "The watchdog barked at the stranger.", translation: "পাহাড়াদার কুকুরটি অপরিচিত ব্যক্তির দিকে ঘেউ ঘেউ করেছিল।" },
  { english: "bathe", bangla: "স্নান করা", phonetic: "/beɪð/", sentence: "He bathes in the river every morning.", translation: "সে প্রতিদিন সকালে নদীতে স্নান করে।" },
  { english: "beat", bangla: "প্রহার করা / হারানো", phonetic: "/biːt/", sentence: "Our team beat the opponent easily.", translation: "আমাদের দল প্রতিপক্ষকে সহজেই হারিয়েছিল।" },
  { english: "become", bangla: "হওয়া", phonetic: "/bɪˈkʌm/", sentence: "She wants to become a doctor.", translation: "সে একজন ডাক্তার হতে চায়।" },
  { english: "beg", bangla: "ভিক্ষা চাওয়া / অনুনয় করা", phonetic: "/bɛɡ/", sentence: "He begged for mercy.", translation: "সে ক্ষমার জন্য অনুনয় করেছিল।" },
  { english: "begin", bangla: "শুরু করা", phonetic: "/bɪˈɡɪn/", sentence: "Let us begin our English lesson today.", translation: "চলুন আজ আমাদের ইংরেজি পাঠ শুরু করি।" },
  { english: "behave", bangla: "আচরণ করা", phonetic: "/bɪˈheɪv/", sentence: "Children should behave politely with elders.", translation: "শিশুদের গুরুজনদের সাথে ভদ্রভাবে আচরণ করা উচিত।" },
  { english: "believe", bangla: "বিশ্বাস করা", phonetic: "/bɪˈliːv/", sentence: "Always believe in yourself and work hard.", translation: "সবসময় নিজের উপর বিশ্বাস রাখুন এবং কঠোর পরিশ্রম করুন।" },
  { english: "belong", bangla: "অধীনে থাকা / উপযুক্ত হওয়া", phonetic: "/bɪˈlɒŋ/", sentence: "This pen belongs to my teacher.", translation: "এই কলমটি আমার শিক্ষকের।" },
  { english: "bend", bangla: "বাঁকা করা / নত হওয়া", phonetic: "/bɛnd/", sentence: "Bend your knees while lifting weights.", translation: "ভার তোলার সময় হাঁটু ভাঁজ করুন।" },
  { english: "bind", bangla: "বাঁধা / আবদ্ধ করা", phonetic: "/baɪnd/", sentence: "Love binds all members of the family.", translation: "ভালোবাসা পরিবারের সকল সদস্যকে আবদ্ধ করে।" },
  { english: "bite", bangla: "কামড়ানো", phonetic: "/baɪt/", sentence: "Be careful, the puppy might bite.", translation: "সাবধান থাকুন, কুকুরছানাটি কামড়াতে পারে।" },
  { english: "blame", bangla: "দোষারোপ করা", phonetic: "/bleɪm/", sentence: "Do not blame others for your mistake.", translation: "নিজের ভুলের জন্য অন্যদের দোষারোপ করবেন না।" },
  { english: "bleed", bangla: "রক্তপাত হওয়া", phonetic: "/bliːd/", sentence: "His finger started to bleed after the cut.", translation: "কেটে যাওয়ার পর তার আঙুল থেকে রক্তপাত হতে লাগল।" },
  { english: "bless", bangla: "আশীর্বাদ করা", phonetic: "/blɛs/", sentence: "May the Almighty bless you with good health.", translation: "সর্বশক্তিমান আপনাকে সুস্বাস্থ্য দান করুন।" },
  { english: "blow", bangla: "বাতাস বওয়া / ফুঁ দেওয়া", phonetic: "/bloʊ/", sentence: "The gentle morning breeze blows softly.", translation: "ভোরের মৃদুমন্দ বাতাস ধীরে ধীরে বয়ে যায়।" },
  { english: "boil", bangla: "ফোটানো", phonetic: "/bɔɪl/", sentence: "Always drink boiled water for safety.", translation: "নিরাপত্তার জন্য সর্বদা ফোটানো পানি পান করুন।" },
  { english: "borrow", bangla: "ধার নেওয়া", phonetic: "/ˈbɒroʊ/", sentence: "He borrowed a history book from the library.", translation: "সে লাইব্রেরি থেকে একটি ইতিহাসের বই ধার নিয়েছিল।" },
  { english: "breathe", bangla: "শ্বাস নেওয়া", phonetic: "/briːð/", sentence: "Take a deep breath of fresh air.", translation: "টাটকা বাতাসে গভীর শ্বাস নিন।" },
  { english: "bring", bangla: "আনা", phonetic: "/brɪŋ/", sentence: "Please bring your notebook tomorrow.", translation: "দয়া করে আগামীকাল তোমার খাতা নিয়ে এসো।" },
  { english: "build", bangla: "নির্মাণ করা", phonetic: "/bɪld/", sentence: "Engineers are building a grand bridge.", translation: "প্রকৌশলীরা একটি বিশাল সেতু নির্মাণ করছেন।" },
  { english: "burn", bangla: "পোড়ানো / জ্বলা", phonetic: "/bɜːrn/", sentence: "Dry wood burns quickly.", translation: "শুকনো কাঠ দ্রুত জ্বলে।" },
  { english: "buy", bangla: "কেনা", phonetic: "/baɪ/", sentence: "I want to buy some English storybooks.", translation: "আমি কিছু ইংরেজি গল্পের বই কিনতে চাই।" },
  { english: "calculate", bangla: "গণনা করা", phonetic: "/ˈkælkjuleɪt/", sentence: "Use a calculator to calculate the total sum.", translation: "মোট অঙ্ক গণনা করতে একটি ক্যালকুলেটর ব্যবহার করুন।" },
  { english: "call", bangla: "ডাকা / ফোন করা", phonetic: "/kɔːl/", sentence: "Call me whenever you need help.", translation: "যখনই সাহায্যের প্রয়োজন হয় আমাকে ডাকবেন।" },
  { english: "care", bangla: "যত্ন নেওয়া", phonetic: "/kɛər/", sentence: "We must care for sick and poor people.", translation: "আমাদের অবশ্যই অসুস্থ ও গরিব মানুষের যত্ন নিতে হবে।" },
  { english: "carry", bangla: "বহন করা", phonetic: "/ˈkæri/", sentence: "The porter carried the heavy luggage.", translation: "কুলি ভারী মালপত্র বহন করেছিল।" },
  { english: "catch", bangla: "ধরা", phonetic: "/kætʃ/", sentence: "The fielder caught the cricket ball.", translation: "ফিল্ডার ক্রিকেট বলটি ধরে ফেলেছিল।" },
  { english: "celebrate", bangla: "উদযাপন করা", phonetic: "/ˈsɛlɪbreɪt/", sentence: "We celebrated our victory happily.", translation: "আমরা আনন্দের সাথে আমাদের বিজয় উদযাপন করেছি।" },
  { english: "change", bangla: "পরিবর্তন করা", phonetic: "/tʃeɪndʒ/", sentence: "Technology changes human life continuously.", translation: "প্রযুক্তি মানুষের জীবনকে নিরবচ্ছিন্নভাবে পরিবর্তন করে।" },
  { english: "charge", bangla: "দায়িত্ব দেওয়া / মূল্য ধরা", phonetic: "/tʃɑːrdʒ/", sentence: "Charge your mobile phone before leaving.", translation: "বের হওয়ার আগে মোবাইল ফোন চার্জ করে নিন।" },
  { english: "chase", bangla: "পিছু নেওয়া / তাড়া করা", phonetic: "/tʃeɪs/", sentence: "The cat chased the mouse across the hall.", translation: "বিড়ালটি ঘরের মধ্যে ইঁদুরটিকে তাড়া করেছিল।" },
  { english: "cheat", bangla: "প্রতারণা করা", phonetic: "/tʃiːt/", sentence: "Never cheat in examinations.", translation: "পরীক্ষায় কখনো প্রতারণা (নকল) করবেন না।" },
  { english: "check", bangla: "পরীক্ষা করা / যাচাই করা", phonetic: "/tʃɛk/", sentence: "Check your answers before submitting the script.", translation: "খাতা জমা দেওয়ার আগে তোমার উত্তরগুলো যাচাই করো।" },
  { english: "cheer", bangla: "উৎসাহ দেওয়া", phonetic: "/tʃɪər/", sentence: "The crowd cheered for their favorite player.", translation: "জনতা তাদের প্রিয় খেলোয়াড়কে উৎসাহিত করেছিল।" },
  { english: "choose", bangla: "পছন্দ করা / বেছে নেওয়া", phonetic: "/tʃuːz/", sentence: "Choose the correct answer from four options.", translation: "চারটি বিকল্প থেকে সঠিক উত্তরটি বেছে নিন।" },
  { english: "clap", bangla: "হাততালি দেওয়া", phonetic: "/klæp/", sentence: "Audience clapped loudly after the performance.", translation: "পরিবেশনার পর দর্শকরা জোরে হাততালি দিয়েছিল।" },
  { english: "clean", bangla: "পরিষ্কার করা", phonetic: "/kliːn/", sentence: "Clean your hands thoroughly before eating.", translation: "খাওয়ার আগে হাত ভালোভাবে পরিষ্কার করুন।" },
  { english: "climb", bangla: "আরোহণ করা / ওঠা", phonetic: "/klaɪm/", sentence: "He climbed the tall coconut tree skillfully.", translation: "সে দক্ষতার সাথে উঁচু নারকেল গাছে উঠেছিল।" },
  { english: "close", bangla: "বন্ধ করা", phonetic: "/kloʊz/", sentence: "Close the windows before it starts raining.", translation: "বৃষ্টি শুরু হওয়ার আগেই জানালাগুলো বন্ধ করো।" },
  { english: "collect", bangla: "সংগ্রহ করা", phonetic: "/kəˈlɛkt/", sentence: "She likes to collect rare stamps.", translation: "সে বিরল ডাকটিকিট সংগ্রহ করতে পছন্দ করে।" },
  { english: "combine", bangla: "একত্রিত করা", phonetic: "/kəmˈbaɪn/", sentence: "Combine study with sports for good health.", translation: "সুস্বাস্থ্যের জন্য পড়াশোনার সাথে খেলাধুলা একত্রিত করুন।" },
  { english: "come", bangla: "আসা", phonetic: "/kʌm/", sentence: "Come to school punctually every day.", translation: "প্রতিদিন সময়মতো বিদ্যালয়ে আসুন।" },
  { english: "comfort", bangla: "সান্ত্বনা দেওয়া", phonetic: "/ˈkʌmfərt/", sentence: "She comforted her crying little sister.", translation: "সে তার ক্রন্দনরত ছোট বোনকে সান্ত্বনা দিয়েছিল।" },
  { english: "command", bangla: "আদেশ দেওয়া", phonetic: "/kəˈmænd/", sentence: "The captain commanded his soldiers to advance.", translation: "অধিনায়ক তার সেনাদের এগিয়ে যাওয়ার আদেশ দিয়েছিলেন।" },
  { english: "communicate", bangla: "যোগাযোগ করা", phonetic: "/kəˈmjuːnɪkeɪt/", sentence: "We can communicate globally through the internet.", translation: "আমরা ইন্টারনেটের মাধ্যমে বিশ্বব্যাপী যোগাযোগ করতে পারি।" },
  { english: "compare", bangla: "তুলনা করা", phonetic: "/kəmˈpɛər/", sentence: "Compare these two pictures and find differences.", translation: "এই দুটি ছবি তুলনা করে পার্থক্য খুঁজুন।" },
  { english: "compete", bangla: "প্রতিযোগিতা করা", phonetic: "/kəmˈpiːt/", sentence: "Athletes compete bravely in the Olympic games.", translation: "ক্রীড়াবিদরা অলিম্পিক গেমসে সাহসের সাথে প্রতিযোগিতা করেন।" },
  { english: "complain", bangla: "অভিযোগ করা", phonetic: "/kəmˈpleɪn/", sentence: "He complained about the noisy environment.", translation: "সে কোলাহলপূর্ণ পরিবেশ নিয়ে অভিযোগ করেছিল।" },
  { english: "complete", bangla: "সম্পূর্ণ করা", phonetic: "/kəmˈpliːt/", sentence: "Complete your homework before sunset.", translation: "সূর্যাস্তের আগেই তোমার বাড়ির কাজ সম্পন্ন করো।" },
  { english: "compose", bangla: "রচনা করা", phonetic: "/kəmˈpoʊz/", sentence: "Kazi Nazrul Islam composed inspiring poems.", translation: "কাজী নজরুল ইসলাম অনুপ্রেরণাদায়ী কবিতা রচনা করেছিলেন।" },
  { english: "concentrate", bangla: "মনোযোগ দেওয়া", phonetic: "/ˈkɒnsəntreɪt/", sentence: "Concentrate on your studies to get good grades.", translation: "ভালো গ্রেড পেতে তোমার পড়াশোনায় মনোযোগ দাও।" },
  { english: "conclude", bangla: "সমাপ্ত করা / উপসংহার টানা", phonetic: "/kənˈkluːd/", sentence: "The speaker concluded his lecture with a proverb.", translation: "বক্তা একটি প্রবাদের মাধ্যমে তার বক্তব্য সমাপ্ত করেছিলেন।" },
  { english: "confirm", bangla: "নিশ্চিত করা", phonetic: "/kənˈfɜːrm/", sentence: "Please confirm your ticket reservation today.", translation: "অনুগ্রহ করে আজই আপনার টিকিট সংরক্ষণ নিশ্চিত করুন।" },
  { english: "connect", bangla: "সংযুক্ত করা", phonetic: "/kəˈnɛkt/", sentence: "Connect the cable to the computer properly.", translation: "তারটি কম্পিউটারের সাথে সঠিকভাবে সংযুক্ত করুন।" },
  { english: "consider", bangla: "বিবেচনা করা", phonetic: "/kənˈsɪdər/", sentence: "Consider all options before making a decision.", translation: "সিদ্ধান্ত নেওয়ার আগে সব বিকল্প বিবেচনা করুন।" },
  { english: "consist", bangla: "গঠিত হওয়া", phonetic: "/kənˈsɪst/", sentence: "A cricket team consists of eleven players.", translation: "একটি ক্রিকেট দল এগারো জন খেলোয়াড় নিয়ে গঠিত হয়।" },
  { english: "construct", bangla: "নির্মাণ করা", phonetic: "/kənˈstrʌkt/", sentence: "Workers construct a multi-story building.", translation: "শ্রমিকরা একটি বহুতল ভবন নির্মাণ করছেন।" },
  { english: "contain", bangla: "ধারণ করা / থাকা", phonetic: "/kənˈteɪn/", sentence: "This bottle contains pure mineral water.", translation: "এই বোতলে খাঁটি খনিজ পানি রয়েছে।" },
  { english: "continue", bangla: "চালিয়ে যাওয়া", phonetic: "/kənˈtɪnjuː/", sentence: "Continue your efforts until you succeed.", translation: "সফল না হওয়া পর্যন্ত তোমার প্রচেষ্টা চালিয়ে যাও।" },
  { english: "contribute", bangla: "অবদান রাখা", phonetic: "/kənˈtrɪbjuːt/", sentence: "Every citizen should contribute to national growth.", translation: "প্রতিটি নাগরিকের জাতীয় উন্নয়নে অবদান রাখা উচিত।" },
  { english: "control", bangla: "নিয়ন্ত্রণ করা", phonetic: "/kənˈtroʊl/", sentence: "Learn to control your temper in difficult times.", translation: "কঠিন সময়ে নিজের রাগ নিয়ন্ত্রণ করতে শিখুন।" },
  { english: "cook", bangla: "রান্না করা", phonetic: "/kʊk/", sentence: "Mother cooks delicious food for our family.", translation: "মা আমাদের পরিবারের জন্য সুস্বাদু খাবার রান্না করেন।" },
  { english: "cooperate", bangla: "সহযোগিতা করা", phonetic: "/koʊˈɒpəreɪt/", sentence: "We must cooperate to build a peaceful society.", translation: "একটি শান্তিপূর্ণ সমাজ গঠনে আমাদের অবশ্যই সহযোগিতা করতে হবে।" },
  { english: "copy", bangla: "অনুকরণ করা / নকল করা", phonetic: "/ˈkɒpi/", sentence: "Never copy another student's exam paper.", translation: "কখনো অন্য শিক্ষার্থীর পরীক্ষার খাতা নকল করবেন না।" },
  { english: "correct", bangla: "সংশোধন করা", phonetic: "/kəˈrɛkt/", sentence: "Teacher corrected all our spelling mistakes.", translation: "শিক্ষক আমাদের সব বানান ভুল সংশোধন করেছিলেন।" },
  { english: "cough", bangla: "কাশি দেওয়া", phonetic: "/kɒf/", sentence: "Cover your mouth when you cough.", translation: "কাশি দেওয়ার সময় মুখ ঢেকে রাখুন।" },
  { english: "count", bangla: "গণনা করা", phonetic: "/kaʊnt/", sentence: "The boy learned to count numbers from one to ten.", translation: "ছেলেটি এক থেকে দশ পর্যন্ত সংখ্যা গণনা করতে শিখেছিল।" },
  { english: "create", bangla: "সৃষ্টি করা", phonetic: "/kriˈeɪt/", sentence: "Artists create magnificent paintings.", translation: "শিল্পীরা দৃষ্টিনন্দন চিত্রকর্ম সৃষ্টি করেন।" },
  { english: "cross", bangla: "পার হওয়া", phonetic: "/krɒs/", sentence: "Look both ways before you cross the street.", translation: "রাস্তা পার হওয়ার আগে উভয় দিকে তাকান।" },
  { english: "cry", bangla: "কাঁদা / চিৎকার করা", phonetic: "/kraɪ/", sentence: "The baby cried because of severe hunger.", translation: "তীব্র ক্ষুধার কারণে শিশুটি কেঁদে উঠেছিল।" },
  { english: "cure", bangla: "আরোগ্য করা / নিরাময় করা", phonetic: "/kjʊər/", sentence: "Modern medicine cures many serious illnesses.", translation: "আধুনিক ওষুধ অনেক মারাত্মক রোগ নিরাময় করে।" },
  { english: "cut", bangla: "কাটা", phonetic: "/kʌt/", sentence: "Use a sharp knife to cut fruits.", translation: "ফল কাটতে একটি ধারালো ছুরি ব্যবহার করুন।" },
  { english: "dance", bangla: "নাচা", phonetic: "/dɑːns/", sentence: "Children danced cheerfully at the cultural program.", translation: "সাংস্কৃতিক অনুষ্ঠানে শিশুরা আনন্দের সাথে নেচেছিল।" },
  { english: "dare", bangla: "সাহস করা", phonetic: "/dɛər/", sentence: "How dare you speak so rudely!", translation: "এত অভদ্রভাবে কথা বলার সাহস তোমার কেমন করে হলো!" },
  { english: "deal", bangla: "ব্যবসা করা / আচরণ করা", phonetic: "/diːl/", sentence: "He deals in green vegetables at the market.", translation: "সে বাজারে কাঁচা সবজির ব্যবসা করে।" },
  { english: "decide", bangla: "সিদ্ধান্ত নেওয়া", phonetic: "/dɪˈsaɪd/", sentence: "She decided to study English literature.", translation: "সে ইংরেজি সাহিত্য পড়ার সিদ্ধান্ত নিয়েছিল।" },
  { english: "declare", bangla: "ঘোষণা করা", phonetic: "/dɪˈklɛər/", sentence: "The judge declared the honest truth in court.", translation: "বিচারক আদালতে সত্য ঘোষণা করেছিলেন।" },
  { english: "decorate", bangla: "সাজানো", phonetic: "/ˈdɛkəreɪt/", sentence: "They decorated the classroom with colorful balloons.", translation: "তারা রঙিন বেলুন দিয়ে শ্রেণিকক্ষ সাজিয়েছিল।" },
  { english: "decrease", bangla: "কমানো / হ্রাস পাওয়া", phonetic: "/dɪˈkriːs/", sentence: "Good habits decrease mental stress.", translation: "ভালো অভ্যাস মানসিক চাপ হ্রাস করে।" },
  { english: "defend", bangla: "রক্ষা করা", phonetic: "/dɪˈfɛnd/", sentence: "Soldiers defend their country courageously.", translation: "সৈনিকরা সাহসিকতার সাথে দেশকে রক্ষা করেন।" },
  { english: "delay", bangla: "দেরি করা", phonetic: "/dɪˈleɪ/", sentence: "Do not delay doing your daily duty.", translation: "তোমার দৈনন্দিন দায়িত্ব পালনে দেরি করো না।" },
  { english: "deliver", bangla: "বিতরণ করা / পৌঁছানো", phonetic: "/dɪˈlɪvər/", sentence: "The postman delivers letters to our home.", translation: "ডাকপিয়ন আমাদের বাড়িতে চিঠি পৌঁছে দেন।" },
  { english: "demand", bangla: "দাবি করা", phonetic: "/dɪˈmænd/", sentence: "Citizens demand pure drinking water.", translation: "নাগরিকরা বিশুদ্ধ খাবার পানি দাবি করেন।" },
  { english: "deny", bangla: "অস্বীকার করা", phonetic: "/dɪˈnaɪ/", sentence: "He denied all the false accusations.", translation: "সে সব মিথ্যা অভিযোগ অস্বীকার করেছিল।" },
  { english: "depend", bangla: "নির্ভর করা", phonetic: "/dɪˈpɛnd/", sentence: "Children depend on their parents for care.", translation: "শিশুরা যত্নের জন্য তাদের পিতা-মাতার উপর নির্ভর করে।" },
  { english: "describe", bangla: "বর্ণনা করা", phonetic: "/dɪˈskraɪb/", sentence: "Describe the natural beauty of your village.", translation: "তোমার গ্রামের প্রাকৃতিক সৌন্দর্য বর্ণনা করো।" },
  { english: "destroy", bangla: "ধ্বংস করা", phonetic: "/dɪˈstrɔɪ/", sentence: "Cyclones destroy houses and crops in coastal areas.", translation: "ঘূর্ণিঝড় উপকূলীয় এলাকায় ঘরবাড়ি ও ফসল ধ্বংস করে।" },
  { english: "develop", bangla: "উন্নত করা / বিকাশ করা", phonetic: "/dɪˈvɛləp/", sentence: "Reading helps develop your mental skills.", translation: "পড়া তোমার মানসিক দক্ষতার বিকাশ ঘটাতে সাহায্য করে।" },
  { english: "die", bangla: "মারা যাওয়া", phonetic: "/daɪ/", sentence: "Heroes die for their nation but live forever in memory.", translation: "বীররা দেশের জন্য জীবন দেন কিন্তু স্মৃতিতে চিরকাল বেঁচে থাকেন।" },
  { english: "dig", bangla: "খনন করা", phonetic: "/dɪɡ/", sentence: "Farmers dig soil to plant seeds.", translation: "কৃষকরা বীজ রোপণের জন্য মাটি খনন করেন।" },
  { english: "diminish", bangla: "কমে যাওয়া / হ্রাস পাওয়া", phonetic: "/dɪˈmɪnɪʃ/", sentence: "His strength diminished after prolonged fever.", translation: "দীর্ঘ জ্বরের পর তার শক্তি কমে গিয়েছিল।" },
  { english: "disappear", bangla: "অদৃশ্য হওয়া", phonetic: "/ˌdɪsəˈpɪər/", sentence: "The fog disappeared as the bright sun rose.", translation: "উজ্জ্বল সূর্য ওঠার সাথে সাথে কুয়াশা অদৃশ্য হয়ে গেল।" },
  { english: "discover", bangla: "আবিষ্কার করা", phonetic: "/dɪˈskʌvər/", sentence: "Scientists discover new facts about the universe.", translation: "বিজ্ঞানীরা মহাবিশ্ব সম্পর্কে নতুন তথ্য আবিষ্কার করেন।" },
  { english: "discuss", bangla: "আলোচনা করা", phonetic: "/dɪˈskʌs/", sentence: "Let us discuss the lesson in groups.", translation: "চলুন আমরা দলবদ্ধভাবে পাঠটি আলোচনা করি।" },
  { english: "dislike", bangla: "অপছন্দ করা", phonetic: "/dɪsˈlaɪk/", sentence: "She dislikes telling lies.", translation: "সে মিথ্যা বলা অপছন্দ করে।" },
  { english: "distribute", bangla: "বিতরণ করা", phonetic: "/dɪˈstrɪbjuːt/", sentence: "Teacher distributed textbooks among all students.", translation: "শিক্ষক সকল শিক্ষার্থীর মাঝে পাঠ্যবই বিতরণ করেছিলেন।" },
  { english: "divide", bangla: "ভাগ করা", phonetic: "/dɪˈvaɪd/", sentence: "Divide the sweet mango into four equal slices.", translation: "মিষ্টি আমটিকে চারটি সমান অংশে ভাগ করো।" },
  { english: "do", bangla: "করা", phonetic: "/duː/", sentence: "Do your daily duties with full sincerity.", translation: "পূর্ণ আন্তরিকতার সাথে তোমার দৈনন্দিন দায়িত্ব পালন করো।" },
  { english: "donate", bangla: "দান করা", phonetic: "/doʊˈneɪt/", sentence: "Wealthy people should donate generously to schools.", translation: "ধনী ব্যক্তিদের উচিত বিদ্যালয়ে উদারভাবে দান করা।" },
  { english: "doubt", bangla: "সন্দেহ করা", phonetic: "/daʊt/", sentence: "I do not doubt his honest intentions.", translation: "আমি তার সৎ উদ্দেশ্য নিয়ে সন্দেহ করি না।" },
  { english: "draw", bangla: "আঁকা / টানা", phonetic: "/drɔː/", sentence: "Children love to draw colorful scenery.", translation: "শিশুরা রঙিন প্রাকৃতিক দৃশ্য আঁকতে ভালোবাসে।" },
  { english: "dream", bangla: "স্বপ্ন দেখা", phonetic: "/driːm/", sentence: "Dream big and strive hard to succeed.", translation: "বড় স্বপ্ন দেখুন এবং সফল হওয়ার জন্য কঠোর চেষ্টা করুন।" },
  { english: "drink", bangla: "পান করা", phonetic: "/drɪŋk/", sentence: "Drink plenty of clean water every day.", translation: "প্রতিদিন প্রচুর পরিমাণে পরিষ্কার পানি পান করুন।" },
  { english: "drive", bangla: "গাড়ি চালানো", phonetic: "/draɪv/", sentence: "Always drive carefully on busy highways.", translation: "ব্যস্ত মহাসড়কে সর্বদা সাবধানে গাড়ি চালান।" },
  { english: "drop", bangla: "ফেলে দেওয়া / পড়ে যাওয়া", phonetic: "/drɒp/", sentence: "Be careful not to drop the fragile cup.", translation: "সাবধান থাকুন যাতে ভঙ্গুর কাপটি পড়ে না যায়।" },
  { english: "earn", bangla: "উপার্জন করা", phonetic: "/ɜːrn/", sentence: "He works diligently to earn an honest living.", translation: "সৎভাবে জীবিকা নির্বাহ করতে সে নিষ্ঠার সাথে কাজ করে।" },
  { english: "eat", bangla: "খাওয়া", phonetic: "/iːt/", sentence: "Eat fresh fruits and vegetables to stay strong.", translation: "সুস্থ ও সবল থাকতে তাজা ফল ও শাকসবজি খান।" },
  { english: "educate", bangla: "শিক্ষিত করা", phonetic: "/ˈɛdʒukeɪt/", sentence: "Schools educate children for a brighter future.", translation: "বিদ্যালয়গুলো শিশুদের উজ্জ্বল ভবিষ্যতের জন্য শিক্ষিত করে।" },
  { english: "encourage", bangla: "উৎসাহিত করা", phonetic: "/ɪnˈkʌrɪdʒ/", sentence: "Teachers always encourage students to learn new words.", translation: "শিক্ষকরা সবসময় শিক্ষার্থীদের নতুন শব্দ শিখতে উৎসাহিত করেন।" },
  { english: "enjoy", bangla: "উপভোগ করা", phonetic: "/ɪnˈdʒɔɪ/", sentence: "We enjoyed the educational boat tour thoroughly.", translation: "আমরা শিক্ষামূলক নৌকা ভ্রমণটি পুরোপুরি উপভোগ করেছি।" },
  { english: "enter", bangla: "প্রবেশ করা", phonetic: "/ˈɛntər/", sentence: "Knock on the door gently before you enter.", translation: "প্রবেশ করার আগে দরজায় মৃদু টোকা দিন।" },
  { english: "escape", bangla: "পালানো / রক্ষা পাওয়া", phonetic: "/ɪˈskeɪp/", sentence: "The deer escaped into the deep forest.", translation: "হরিণটি গভীর বনে পালিয়ে গিয়েছিল।" },
  { english: "examine", bangla: "পরীক্ষা করা", phonetic: "/ɪɡˈzæmɪn/", sentence: "The doctor examined the patient thoroughly.", translation: "ডাক্তার রোগীকে পুঙ্খানুপুঙ্খভাবে পরীক্ষা করেছিলেন।" },
  { english: "exercise", bangla: "ব্যায়াম করা", phonetic: "/ˈɛksərsaɪz/", sentence: "Exercise regularly to maintain a healthy body.", translation: "সুস্থ শরীর বজায় রাখতে নিয়মিত ব্যায়াম করুন।" },
  { english: "expect", bangla: "প্রত্যাশা করা", phonetic: "/ɪkˈspɛkt/", sentence: "We expect him to win the first prize.", translation: "আমরা প্রত্যাশা করি সে প্রথম পুরস্কারটি জিতবে।" },
  { english: "explain", bangla: "ব্যাখ্যা করা", phonetic: "/ɪkˈspleɪn/", sentence: "Teacher explained the grammar rule very clearly.", translation: "শিক্ষক ব্যাকরণের নিয়মটি খুব পরিষ্কারভাবে ব্যাখ্যা করেছিলেন।" },
  { english: "explore", bangla: "অন্বেষণ করা", phonetic: "/ɪkˈsplɔːr/", sentence: "Travelers explore historic monuments of our land.", translation: "ভ্রমণকারীরা আমাদের দেশের ঐতিহাসিক নিদর্শনসমূহ অন্বেষণ করেন।" },
  { english: "express", bangla: "প্রকাশ করা", phonetic: "/ɪkˈsprɛs/", sentence: "Express your opinions politely in public.", translation: "জনসমক্ষে আপনার মতামত ভদ্রভাবে প্রকাশ করুন।" },
  { english: "fail", bangla: "ব্যর্থ হওয়া", phonetic: "/feɪl/", sentence: "Failure teaches valuable lessons to achieve success.", translation: "ব্যর্থতা সাফল্য অর্জনের মূল্যবান শিক্ষা দেয়।" },
  { english: "fall", bangla: "পড়ে যাওয়া", phonetic: "/fɔːl/", sentence: "Golden leaves fall from trees in autumn.", translation: "শরতে গাছ থেকে সোনালি পাতাগুলো ঝরে পড়ে।" },
  { english: "fear", bangla: "ভয় পাওয়া", phonetic: "/fɪər/", sentence: "A brave person does not fear challenges.", translation: "একজন সাহসী মানুষ প্রতিকূলতাকে ভয় পায় না।" },
  { english: "feed", bangla: "খাওয়ানো", phonetic: "/fiːd/", sentence: "She feeds the birds every morning on her terrace.", translation: "সে প্রতিদিন সকালে তার ছাদে পাখিদের খাবার খাওয়ায়।" },
  { english: "feel", bangla: "অনুভব করা", phonetic: "/fiːl/", sentence: "I feel delighted to meet you here.", translation: "এখানে আপনার সাথে দেখা হয়ে আমি আনন্দ অনুভব করছি।" },
  { english: "fight", bangla: "লড়াই করা", phonetic: "/faɪt/", sentence: "Our freedom fighters fought bravely in 1971.", translation: "১৯৭১ সালে আমাদের মুক্তিযোদ্ধারা বীরত্বের সাথে লড়াই করেছিলেন।" },
  { english: "fill", bangla: "পূর্ণ করা", phonetic: "/fɪl/", sentence: "Fill the pitcher with fresh water.", translation: "কলসিটি তাজা পানি দিয়ে পূর্ণ করো।" },
  { english: "find", bangla: "খুঁজে পাওয়া", phonetic: "/faɪnd/", sentence: "I found my lost keys under the table.", translation: "আমি টেবিলের নিচে আমার হারিয়ে যাওয়া চাবিগুলো খুঁজে পেলাম।" },
  { english: "finish", bangla: "শেষ করা", phonetic: "/ˈfɪnɪʃ/", sentence: "Finish your task before the deadline expires.", translation: "সময়সীমা শেষ হওয়ার আগেই তোমার কাজটি শেষ করো।" },
  { english: "fly", bangla: "ওড়া", phonetic: "/flaɪ/", sentence: "Wild birds fly across the vast blue sky.", translation: "বুনো পাখিরা সুবিশাল নীল আকাশে উড়ে বেড়ায়।" },
  { english: "follow", bangla: "অনুসরণ করা", phonetic: "/ˈfɒloʊ/", sentence: "Follow the traffic signals strictly on the road.", translation: "রাস্তায় ট্রাফিক সংকেত কঠোরভাবে অনুসরণ করুন।" },
  { english: "forbid", bangla: "নিষেধ করা", phonetic: "/fərˈbɪd/", sentence: "The rules forbid plucking flowers in the park.", translation: "নিয়মে পার্কে ফুল তোলা নিষিদ্ধ করা হয়েছে।" },
  { english: "forget", bangla: "ভুলে যাওয়া", phonetic: "/fərˈɡɛt/", sentence: "Never forget your roots and gratitude.", translation: "কখনো নিজের শিকড় ও কৃতজ্ঞতা ভুলে যাবেন না।" },
  { english: "forgive", bangla: "ক্ষমা করা", phonetic: "/fərˈɡɪv/", sentence: "Forgive those who unintentionally hurt you.", translation: "যারা অনিচ্ছাকৃতভাবে আপনাকে কষ্ট দিয়েছে তাদের ক্ষমা করে দিন।" },
  { english: "freeze", bangla: "জমে যাওয়া", phonetic: "/friːz/", sentence: "Water freezes into ice at zero degrees Celsius.", translation: "পানি শূন্য ডিগ্রি সেলসিয়াসে বরফে পরিণত হয়।" },
  { english: "gather", bangla: "একত্রিত করা / জড়ো হওয়া", phonetic: "/ˈɡæðər/", sentence: "Villagers gathered under the large banyan tree.", translation: "গ্রামবাসীরা বিশাল বটগাছের নিচে জড়ো হয়েছিল।" },
  { english: "get", bangla: "পাওয়া", phonetic: "/ɡɛt/", sentence: "You will get good marks if you practice regularly.", translation: "নিয়মিত অনুশীলন করলে তুমি ভালো নম্বর পাবে।" },
  { english: "give", bangla: "দেওয়া", phonetic: "/ɡɪv/", sentence: "Always give helping hands to needy people.", translation: "অসহায় মানুষদের দিকে সর্বদা সহযোগিতার হাত বাড়িয়ে দিন।" },
  { english: "go", bangla: "যাওয়া", phonetic: "/ɡoʊ/", sentence: "Students go to school eagerly every morning.", translation: "শিক্ষার্থীরা প্রতিদিন সকালে আগ্রহের সাথে বিদ্যালয়ে যায়।" },
  { english: "govern", bangla: "শাসন করা", phonetic: "/ˈɡʌvərn/", sentence: "Leaders must govern the country with fairness.", translation: "নেতাদের অবশ্যই নিরপেক্ষতার সাথে দেশ পরিচালনা করা উচিত।" },
  { english: "grab", bangla: "জাপটে ধরা / ধরা", phonetic: "/ɡræb/", sentence: "He grabbed the handrail to avoid falling.", translation: "পড়ে যাওয়া থেকে বাঁচতে সে রেলিংটি চেপে ধরেছিল।" },
  { english: "greet", bangla: "অভিবাদন জানানো", phonetic: "/ɡriːt/", sentence: "Always greet your teachers with a warm smile.", translation: "সর্বদা মৃদু হাসির সাথে আপনার শিক্ষকদের অভিবাদন জানান।" },
  { english: "grow", bangla: "বৃদ্ধি পাওয়া / চাষ করা", phonetic: "/ɡroʊ/", sentence: "Farmers grow golden paddy across the fields.", translation: "কৃষকরা মাঠজুড়ে সোনালি ধান চাষ করেন।" },
  { english: "guide", bangla: "পথ দেখানো / পরিচালনা করা", phonetic: "/ɡaɪd/", sentence: "Good teachers guide students towards wisdom.", translation: "ভালো শিক্ষকরা শিক্ষার্থীদের জ্ঞানের পথে পরিচালিত করেন।" },
  { english: "handle", bangla: "সামলানো / ধরা", phonetic: "/ˈhændl/", sentence: "She handled the emergency situation calmly.", translation: "সে শান্তভাবে জরুরি পরিস্থিতি সামলেছিল।" },
  { english: "happen", bangla: "ঘটা", phonetic: "/ˈhæpən/", sentence: "Miracles happen when you work passionately.", translation: "যখন আপনি নিষ্ঠার সাথে কাজ করেন তখন অলৌকিক কিছু ঘটে।" },
  { english: "hate", bangla: "ঘৃণা করা", phonetic: "/heɪt/", sentence: "We should hate the sin, not the sinner.", translation: "আমাদের পাপকে ঘৃণা করা উচিত, পাপীকে নয়।" },
  { english: "have", bangla: "থাকা / পাওয়া", phonetic: "/hæv/", sentence: "I have great respect for all my mentors.", translation: "আমার সকল শিক্ষকের প্রতি আমার গভীর শ্রদ্ধা রয়েছে।" },
  { english: "heal", bangla: "উপশম হওয়া / আরোগ্য লাভ করা", phonetic: "/hiːl/", sentence: "Kind words heal a wounded heart.", translation: "সদয় কথা আহত হৃদয়কে উপশম করে।" },
  { english: "hear", bangla: "শোনা", phonetic: "/hɪər/", sentence: "Did you hear the sweet sound of birds singing?", translation: "তুমি কি পাখিদের মিষ্টি গানের শব্দ শুনেছ?" },
  { english: "help", bangla: "সাহায্য করা", phonetic: "/hɛlp/", sentence: "Help your classmates whenever they face difficulty.", translation: "সহপাঠীরা সমস্যায় পড়লে তাদের সাহায্য করো।" },
  { english: "hide", bangla: "লুকানো", phonetic: "/haɪd/", sentence: "The rabbit hid behind the green bush.", translation: "খরগোশটি সবুজ ঝোপের আড়ালে লুকিয়েছিল।" },
  { english: "hit", bangla: "আঘাত করা", phonetic: "/hɪt/", sentence: "The batsman hit a magnificent six.", translation: "ব্যাটসম্যান একটি দৃষ্টিনন্দন ছক্কা মেরেছিলেন।" },
  { english: "hold", bangla: "ধরা / আয়োজন করা", phonetic: "/hoʊld/", sentence: "They held an annual sports competition in the field.", translation: "তারা মাঠে বার্ষিক ক্রীড়া প্রতিযোগিতার আয়োজন করেছিল।" },
  { english: "hope", bangla: "আশা করা", phonetic: "/hoʊp/", sentence: "We hope for peace and prosperity in the country.", translation: "আমরা দেশে শান্তি ও সমৃদ্ধি আশা করি।" },
  { english: "hug", bangla: "জড়িয়ে ধরা", phonetic: "/hʌɡ/", sentence: "The mother hugged her child with deep affection.", translation: "মা গভীর স্নেহের সাথে তার সন্তানকে জড়িয়ে ধরেছিলেন।" },
  { english: "hunt", bangla: "শিকার করা", phonetic: "/hʌnt/", sentence: "Lions hunt in groups during twilight.", translation: "সিংহরা গোধূলির সময় দলবদ্ধভাবে শিকার করে।" },
  { english: "ignore", bangla: "উপেক্ষা করা", phonetic: "/ɪɡˈnɔːr/", sentence: "Never ignore good advice from your parents.", translation: "বাবা-মায়ের ভালো উপদেশ কখনো উপেক্ষা করবেন না।" },
  { english: "illustrate", bangla: "ব্যাখ্যা করা / চিত্রিত করা", phonetic: "/ˈɪləstreɪt/", sentence: "The artist illustrated the storybook beautifully.", translation: "শিল্পী গল্পের বইটি সুন্দরভাবে চিত্রিত করেছিলেন।" },
  { english: "imagine", bangla: "কল্পনা করা", phonetic: "/ɪˈmædʒɪn/", sentence: "Imagine a world full of kindness and harmony.", translation: "দয়া ও সম্প্রীতিতে ভরা একটি পৃথিবীর কল্পনা করুন।" },
  { english: "imitate", bangla: "অনুকরণ করা", phonetic: "/ˈɪmɪteɪt/", sentence: "Parrots can imitate human speech amusingly.", translation: "তোতাপাখি মজার সাথে মানুষের কণ্ঠ অনুকরণ করতে পারে।" },
  { english: "improve", bangla: "উন্নত করা", phonetic: "/ɪmˈpruːv/", sentence: "Regular reading will improve your vocabulary.", translation: "নিয়মিত পড়া তোমার শব্দভাণ্ডার উন্নত করবে।" },
  { english: "include", bangla: "অন্তর্ভুক্ত করা", phonetic: "/ɪnˈkluːd/", sentence: "The curriculum includes grammar and spoken English.", translation: "পাঠ্যক্রমে ব্যাকরণ ও কথ্য ইংরেজি অন্তর্ভুক্ত রয়েছে।" },
  { english: "increase", bangla: "বৃদ্ধি করা / বাড়ানো", phonetic: "/ɪnˈkriːs/", sentence: "Hard work increases your chance of achievement.", translation: "কঠোর পরিশ্রম আপনার অর্জনের সুযোগ বৃদ্ধি করে।" },
  { english: "inform", bangla: "অবহিত করা / জানানো", phonetic: "/ɪnˈfɔːrm/", sentence: "Please inform us of your decision quickly.", translation: "অনুগ্রহ করে আপনার সিদ্ধান্ত আমাদের দ্রুত জানান।" },
  { english: "inherit", bangla: "উত্তরাধিকার সূত্রে পাওয়া", phonetic: "/ɪnˈhɛrɪt/", sentence: "He inherited good values from his family.", translation: "সে তার পরিবার থেকে ভালো মূল্যবোধ উত্তরাধিকারসূত্রে পেয়েছিল।" },
  { english: "injure", bangla: "আহত করা", phonetic: "/ˈɪndʒər/", sentence: "Be careful not to injure yourself on the stairs.", translation: "সাবধান থাকুন যাতে সিঁড়িতে আঘাত না পান।" },
  { english: "inspect", bangla: "পরিদর্শন করা", phonetic: "/ɪnˈspɛkt/", sentence: "The education officer inspected the school today.", translation: "শিক্ষা কর্মকর্তা আজ বিদ্যালয়টি পরিদর্শন করেছিলেন।" },
  { english: "inspire", bangla: "অনুপ্রাণিত করা", phonetic: "/ɪnˈspaɪər/", sentence: "Great teachers inspire students to dream big.", translation: "মহান শিক্ষকরা শিক্ষার্থীদের বড় স্বপ্ন দেখতে অনুপ্রাণিত করেন।" },
  { english: "instruct", bangla: "নির্দেশ দেওয়া", phonetic: "/ɪnˈstrʌkt/", sentence: "He instructed students on proper exam techniques.", translation: "তিনি শিক্ষার্থীদের পরীক্ষার সঠিক কৌশল সম্পর্কে নির্দেশ দিয়েছিলেন।" },
  { english: "insult", bangla: "অপমান করা", phonetic: "/ɪnˈsʌlt/", sentence: "It is impolite to insult anyone in public.", translation: "জনসমক্ষে কাউকে অপমান করা অভদ্রতা।" },
  { english: "intend", bangla: "উদ্দেশ্য করা / ইচ্ছা করা", phonetic: "/ɪnˈtɛnd/", sentence: "I intend to complete the course this month.", translation: "আমি এই মাসেই কোর্সটি সম্পন্ন করার ইচ্ছা পোষণ করি।" },
  { english: "interest", bangla: "আগ্রহী করা", phonetic: "/ˈɪntrəst/", sentence: "Science experiments interest young learners.", translation: "বিজ্ঞানের পরীক্ষা-নিরীক্ষা তরুণ শিক্ষার্থীদের আগ্রহী করে তোলে।" },
  { english: "interpret", bangla: "ব্যাখ্যা করা / অনুবাদ করা", phonetic: "/ɪnˈtɜːrprɪt/", sentence: "The scholar interpreted the ancient inscription.", translation: "পণ্ডিত ব্যক্তি প্রাচীন শিলালিপিটি ব্যাখ্যা করেছিলেন।" },
  { english: "interrupt", bangla: "বাধা দেওয়া", phonetic: "/ˌɪntəˈrʌpt/", sentence: "Do not interrupt when someone is speaking.", translation: "কেউ কথা বলার সময় বাধা দেবেন না।" },
  { english: "introduce", bangla: "পরিচয় করিয়ে দেওয়া", phonetic: "/ˌɪntrəˈdjuːs/", sentence: "Let me introduce my close childhood friend.", translation: "আমার শৈশবের ঘনিষ্ঠ বন্ধুর সাথে আপনাকে পরিচয় করিয়ে দিই।" },
  { english: "invent", bangla: "উদ্ভাবন করা", phonetic: "/ɪnˈvɛnt/", sentence: "Alexander Graham Bell invented the telephone.", translation: "আলেকজান্ডার গ্রাহাম বেল টেলিফোন উদ্ভাবন করেছিলেন।" },
  { english: "invite", bangla: "আমন্ত্রণ জানানো", phonetic: "/ɪnˈvaɪt/", sentence: "We invited all our teachers to the cultural fest.", translation: "আমরা আমাদের সকল শিক্ষককে সাংস্কৃতিক উৎসবে আমন্ত্রণ জানিয়েছিলাম।" },
  { english: "irritate", bangla: "বিরক্ত করা", phonetic: "/ˈɪrɪteɪt/", sentence: "Loud noise irritates students while studying.", translation: "পড়াশোনার সময় বিকট শব্দ শিক্ষার্থীদের বিরক্ত করে।" },
  { english: "join", bangla: "যোগ দেওয়া", phonetic: "/dʒɔɪn/", sentence: "Many youth joined the literacy campaign.", translation: "অনেক তরুণ সাক্ষরতা অভিযানে যোগ দিয়েছিল।" },
  { english: "judge", bangla: "বিচার করা", phonetic: "/dʒʌdʒ/", sentence: "Do not judge a book simply by its cover.", translation: "শুধুমাত্র প্রচ্ছদ দেখে কোনো বইকে বিচার করবেন না।" },
  { english: "jump", bangla: "লাফ দেওয়া", phonetic: "/dʒʌmp/", sentence: "The cheerful boy jumped with joy.", translation: "প্রফুল্ল ছেলেটি আনন্দে লাফিয়ে উঠেছিল।" },
  { english: "keep", bangla: "রাখা / পালন করা", phonetic: "/kiːp/", sentence: "Always keep your promises faithfully.", translation: "সর্বদা বিশ্বস্ততার সাথে তোমার প্রতিশ্রুতি পালন করো।" },
  { english: "kick", bangla: "লাথি মারা", phonetic: "/kɪk/", sentence: "The striker kicked the football into the goalpost.", translation: "স্ট্রাইকার ফুটবলটি গোলপোস্টে মেরেছিলেন।" },
  { english: "kill", bangla: "হত্যা করা", phonetic: "/kɪl/", sentence: "Pesticides kill harmful crop pests.", translation: "কীটনাশক ফসলের ক্ষতিকর কীটপতঙ্গ হত্যা করে।" },
  { english: "kiss", bangla: "চুমু খাওয়া / চুম্বন করা", phonetic: "/kɪs/", sentence: "The mother kissed her newborn baby tenderly.", translation: "মা স্নেহের সাথে তার নবজাতক শিশুকে চুম্বন করেছিলেন।" },
  { english: "kneel", bangla: "হাঁটু গেড়ে বসা", phonetic: "/niːl/", sentence: "Devotees knelt in prayer at the sacred mosque.", translation: "ভক্তরা পবিত্র মসজিদে প্রার্থনায় হাঁটু গেড়ে বসেছিলেন।" },
  { english: "know", bangla: "জানা", phonetic: "/noʊ/", sentence: "Knowledge is power when you know how to use it.", translation: "জ্ঞানই শক্তি যখন আপনি জানেন কীভাবে তা ব্যবহার করতে হয়।" },
  { english: "laugh", bangla: "হাসা", phonetic: "/lɑːf/", sentence: "Laughter is the best medicine for the soul.", translation: "হাসি মনের জন্য সর্বোত্তম ওষুধ।" },
  { english: "lead", bangla: "নেতৃত্ব দেওয়া / পরিচালনা করা", phonetic: "/liːd/", sentence: "A wise leader leads his team by example.", translation: "একজন জ্ঞানী নেতা দৃষ্টান্ত স্থাপনের মাধ্যমে দলকে নেতৃত্ব দেন।" },
  { english: "lean", bangla: "হেলান দেওয়া", phonetic: "/liːn/", sentence: "Do not lean against the wet painted wall.", translation: "সদ্য রঙ করা ভেজা দেয়ালে হেলান দেবেন না।" },
  { english: "learn", bangla: "শেখা", phonetic: "/lɜːrn/", sentence: "Eager students learn new vocabulary every day.", translation: "উৎসাহী শিক্ষার্থীরা প্রতিদিন নতুন শব্দভাণ্ডার শেখে।" },
  { english: "leave", bangla: "ত্যাগ করা / চলে যাওয়া", phonetic: "/liːv/", sentence: "The train leaves the platform at nine o'clock.", translation: "ট্রেনটি নয়টায় প্ল্যাটফর্ম ত্যাগ করে।" },
  { english: "lend", bangla: "ধার দেওয়া", phonetic: "/lɛnd/", sentence: "Could you lend me your dictionary for an hour?", translation: "আপনি কি দয়া করে আমাকে এক ঘণ্টার জন্য আপনার অভিধানটি ধার দেবেন?" },
  { english: "let", bangla: "অনুমতি দেওয়া", phonetic: "/lɛt/", sentence: "Let children explore their natural creativity.", translation: "শিশুদের তাদের স্বাভাবিক সৃজনশীলতা অন্বেষণ করতে দিন।" },
  { english: "lie", bangla: "মিথ্যা বলা / শয়ন করা", phonetic: "/laɪ/", sentence: "An honest person will never lie to anyone.", translation: "একজন সৎ মানুষ কখনোই কারো কাছে মিথ্যা বলবে না।" },
  { english: "lift", bangla: "উত্তোলন করা / তোলা", phonetic: "/lɪft/", sentence: "He lifted the heavy parcel with both hands.", translation: "সে দুই হাতে ভারী পার্সেলটি তুলেছিল।" },
  { english: "light", bangla: "জ্বালানো", phonetic: "/laɪt/", sentence: "Light the candle to dispel darkness.", translation: "অন্ধকার দূর করতে মোমবাতিটি জ্বালাও।" },
  { english: "like", bangla: "পছন্দ করা", phonetic: "/laɪk/", sentence: "Children like eating sweet fresh fruits.", translation: "শিশুরা মিষ্টি তাজা ফল খেতে পছন্দ করে।" },
  { english: "listen", bangla: "মনোযোগ দিয়ে শোনা", phonetic: "/ˈlɪsn/", sentence: "Listen carefully to your teacher's speech.", translation: "তোমার শিক্ষকের বক্তব্য মনোযোগ দিয়ে শোনো।" },
  { english: "live", bangla: "বাস করা / বেঁচে থাকা", phonetic: "/lɪv/", sentence: "They live happily in a peaceful green village.", translation: "তারা একটি শান্তিপূর্ণ সবুজ গ্রামে সুখে বাস করে।" },
  { english: "load", bangla: "বোঝাই করা", phonetic: "/loʊd/", sentence: "Workers loaded the truck with agricultural goods.", translation: "শ্রমিকরা ট্রাকে কৃষিপণ্য বোঝাই করেছিলেন।" },
  { english: "lock", bangla: "তালা লাগানো", phonetic: "/lɒk/", sentence: "Lock the main door securely before sleeping.", translation: "ঘুমানোর আগে প্রধান দরজায় নিরাপদে তালা লাগান।" },
  { english: "look", bangla: "তাকানো / দেখা", phonetic: "/lʊk/", sentence: "Look at the colorful rainbow in the sky.", translation: "আকাশে রঙিন রংধনুর দিকে তাকাও।" },
  { english: "lose", bangla: "হারানো / পরাজিত হওয়া", phonetic: "/luːz/", sentence: "Never lose your courage in adversity.", translation: "প্রতিকূলতায় কখনো নিজের সাহস হারাবেন না।" },
  { english: "love", bangla: "ভালোবাসা", phonetic: "/lʌv/", sentence: "We love our motherland Bangladesh deeply.", translation: "আমরা আমাদের মাতৃভূমি বাংলাদেশকে গভীরভাবে ভালোবাসি।" },
  { english: "maintain", bangla: "বজায় রাখা", phonetic: "/meɪnˈteɪn/", sentence: "Maintain discipline and cleanliness everywhere.", translation: "সর্বত্র শৃঙ্খলা ও পরিচ্ছন্নতা বজায় রাখুন।" },
  { english: "make", bangla: "তৈরি করা", phonetic: "/meɪk/", sentence: "Practice makes a person perfect in learning.", translation: "অনুশীলন মানুষকে শেখার ক্ষেত্রে নিখুঁত করে তোলে।" },
  { english: "manage", bangla: "পরিচালনা করা / সামলানো", phonetic: "/ˈmænɪdʒ/", sentence: "She manages the organization efficiently.", translation: "তিনি দক্ষতার সাথে সংস্থাটি পরিচালনা করেন।" },
  { english: "marry", bangla: "বিয়ে করা", phonetic: "/ˈmæri/", sentence: "They decided to marry with family blessings.", translation: "তারা পারিবারিক আশীর্বাদে বিয়ে করার সিদ্ধান্ত নিয়েছিল।" },
  { english: "match", bangla: "মেলানো / সমান হওয়া", phonetic: "/mætʃ/", sentence: "Match each English word with its Bengali meaning.", translation: "প্রতিটি ইংরেজি শব্দের সাথে তার বাংলা অর্থ মেলান।" },
  { english: "mean", bangla: "অর্থ প্রকাশ করা / বোঝানো", phonetic: "/miːn/", sentence: "What does this new vocabulary word mean?", translation: "এই নতুন শব্দটির অর্থ কী?" },
  { english: "measure", bangla: "পরিমাপ করা", phonetic: "/ˈmɛʒər/", sentence: "Tailors measure cloth before cutting.", translation: "দর্জিরা কাটার আগে কাপড় পরিমাপ করেন।" },
  { english: "meet", bangla: "সাক্ষাৎ করা", phonetic: "/miːt/", sentence: "We will meet at the library this evening.", translation: "আজ সন্ধ্যায় আমরা লাইব্রেরিতে সাক্ষাৎ করব।" },
  { english: "melt", bangla: "গলে যাওয়া", phonetic: "/mɛlt/", sentence: "Ice melts quickly under warm sunlight.", translation: "উষ্ণ সূর্যালোকের নিচে বরফ দ্রুত গলে যায়।" },
  { english: "memorize", bangla: "মুখস্থ করা / আত্মস্থ করা", phonetic: "/ˈmɛməraɪz/", sentence: "Memorize vocabulary through regular sentence usage.", translation: "নিয়মিত বাক্য ব্যবহারের মাধ্যমে শব্দভাণ্ডার আত্মস্থ করুন।" },
  { english: "mend", bangla: "মেরামত করা", phonetic: "/mɛnd/", sentence: "The cobbler mended the broken shoe.", translation: "মুচি ছেঁড়া জুতোটি মেরামত করেছিল।" },
  { english: "mention", bangla: "উল্লেখ করা", phonetic: "/ˈmɛnʃn/", sentence: "He mentioned several examples in his speech.", translation: "তিনি তার বক্তব্যে কয়েকটি উদাহরণ উল্লেখ করেছিলেন।" },
  { english: "mind", bangla: "মন দেওয়া / আপত্তি করা", phonetic: "/maɪnd/", sentence: "Mind your language when speaking to teachers.", translation: "শিক্ষকদের সাথে কথা বলার সময় ভাষার প্রতি যত্নশীল হোন।" },
  { english: "miss", bangla: "মিস করা / হাতছাড়া করা", phonetic: "/mɪs/", sentence: "He ran fast so that he would not miss the bus.", translation: "সে দ্রুত দৌড়েছিল যাতে বাসটি মিস না হয়।" },
  { english: "mix", bangla: "মেশানো", phonetic: "/mɪks/", sentence: "Mix colors to create a new shade.", translation: "একটি নতুন শেড তৈরি করতে রঙ মেশান।" },
  { english: "move", bangla: "নড়াচড়া করা / চলা", phonetic: "/muːv/", sentence: "Planets move in orbits around the sun.", translation: "গ্রহগুলো সূর্যের চারপাশে কক্ষপথে ঘোরে।" },
  { english: "multiply", bangla: "গুণ করা / বৃদ্ধি পাওয়া", phonetic: "/ˈmʌltɪplaɪ/", sentence: "Multiply five by four to get twenty.", translation: "পাঁচকে চার দিয়ে গুণ করলে কুড়ি হয়।" },
  { english: "name", bangla: "নাম দেওয়া / নামকরণ করা", phonetic: "/neɪm/", sentence: "They named their newborn child Fayez.", translation: "তারা তাদের নবজাতক সন্তানের নাম রেখেছিল ফায়েজ।" },
  { english: "need", bangla: "প্রয়োজন হওয়া", phonetic: "/niːd/", sentence: "We need good books to enlighten our minds.", translation: "মনকে আলোকিত করতে আমাদের ভালো বই প্রয়োজন।" },
  { english: "neglect", bangla: "অবহেলা করা", phonetic: "/nɪˈɡlɛkt/", sentence: "Never neglect your studies before examinations.", translation: "পরীক্ষার আগে কখনোই পড়াশোনায় অবহেলা করবেন না।" },
  { english: "nod", bangla: "মাথা নাড়া (সম্মতি)", phonetic: "/nɒd/", sentence: "He nodded his head in agreement.", translation: "সে সম্মতিতে মাথা নেড়েছিল।" },
  { english: "notice", bangla: "লক্ষ করা", phonetic: "/ˈnoʊtɪs/", sentence: "Did you notice the error in that calculation?", translation: "তুমি কি সেই গণনার ভুলটি লক্ষ করেছিলে?" },
  { english: "obey", bangla: "মান্য করা / আদেশ পালন করা", phonetic: "/əˈbeɪ/", sentence: "Good children obey their parents and teachers.", translation: "ভালো সন্তানরা পিতা-মাতা ও শিক্ষকদের আদেশ মান্য করে।" },
  { english: "observe", bangla: "পর্যবেক্ষণ করা / পালন করা", phonetic: "/əbˈzɜːrv/", sentence: "Scientists observe natural phenomena keenly.", translation: "বিজ্ঞানীরা গভীর মনোযোগের সাথে প্রাকৃতিক ঘটনা পর্যবেক্ষণ করেন।" },
  { english: "obtain", bangla: "অর্জন করা / লাভ করা", phonetic: "/əbˈteɪn/", sentence: "She obtained a scholarship for her brilliant result.", translation: "চমৎকার ফলাফলের জন্য সে একটি বৃত্তি লাভ করেছিল।" },
  { english: "occupy", bangla: "দখল করা / স্থান নেওয়া", phonetic: "/ˈɒkjupaɪ/", sentence: "Books occupy a major place in his study room.", translation: "তার পড়ার ঘরের একটি বড় স্থান বইগুলো দখল করে আছে।" },
  { english: "occur", bangla: "ঘটা", phonetic: "/əˈkɜːr/", sentence: "Solar eclipses occur at specific cosmic intervals.", translation: "সূর্যগ্রহণ নির্দিষ্ট মহাজাগতিক ব্যবধানে ঘটে।" },
  { english: "offer", bangla: "প্রস্তাব করা / দেওয়া", phonetic: "/ˈɒfər/", sentence: "He offered kind help to the stranger.", translation: "সে অপরিচিত ব্যক্তিকে সদয় সাহায্যের প্রস্তাব দিয়েছিল।" },
  { english: "open", bangla: "খোলা", phonetic: "/ˈoʊpən/", sentence: "Open the classroom door to let fresh air inside.", translation: "তাজা বাতাস ভেতরে আসার জন্য শ্রেণিকক্ষের দরজাটি খোলো।" },
  { english: "operate", bangla: "পরিচালনা করা / শল্যচিকিৎসা করা", phonetic: "/ˈɒpəreɪt/", sentence: "The surgeon operated on the patient skillfully.", translation: "শল্যচিকিৎসক দক্ষতার সাথে রোগীর অস্ত্রোপচার করেছিলেন।" },
  { english: "order", bangla: "আদেশ দেওয়া / ফরমাশ দেওয়া", phonetic: "/ˈɔːrdər/", sentence: "The officer ordered strict vigilance at the border.", translation: "কর্মকর্তা সীমান্তে কঠোর নজরদারির আদেশ দিয়েছিলেন।" },
  { english: "organize", bangla: "সংগঠিত করা / আয়োজন করা", phonetic: "/ˈɔːrɡənaɪz/", sentence: "Students organized an annual science exhibition.", translation: "শিক্ষার্থীরা একটি বার্ষিক বিজ্ঞান মেলার আয়োজন করেছিল।" },
  { english: "overcome", bangla: "জয় করা / পরাস্ত করা", phonetic: "/ˌoʊvərˈkʌm/", sentence: "We shall overcome all challenges with unity.", translation: "আমরা ঐক্যের মাধ্যমে সকল প্রতিকূলতা জয় করব।" },
  { english: "owe", bangla: "ঋণী থাকা", phonetic: "/oʊ/", sentence: "We owe deep gratitude to our noble teachers.", translation: "আমরা আমাদের মহান শিক্ষকদের প্রতি গভীর কৃতজ্ঞতায় ঋণী।" },
  { english: "paint", bangla: "রং করা / আঁকা", phonetic: "/peɪnt/", sentence: "She painted a picturesque Bangladeshi village.", translation: "সে ছবির মতো সুন্দর একটি বাংলাদেশি গ্রাম এঁকেছিল।" },
  { english: "participate", bangla: "অংশগ্রহণ করা", phonetic: "/pɑːrˈtɪsɪpeɪt/", sentence: "All students participated in the debate contest.", translation: "সকল শিক্ষার্থী বিতর্ক প্রতিযোগিতায় অংশগ্রহণ করেছিল।" },
  { english: "pass", bangla: "উত্তীর্ণ হওয়া / পার হওয়া", phonetic: "/pæs/", sentence: "He passed the board examination with flying colors.", translation: "সে চমৎকার ফলাফলের সাথে বোর্ড পরীক্ষায় উত্তীর্ণ হয়েছিল।" },
  { english: "pay", bangla: "পরিশোধ করা", phonetic: "/peɪ/", sentence: "Always pay your utility bills on time.", translation: "সর্বদা সময়মতো বিদ্যুৎ ও পানির বিল পরিশোধ করুন।" },
  { english: "perform", bangla: "সম্পাদন করা / অভিনয় করা", phonetic: "/pərˈfɔːrm/", sentence: "The school choir performed patriotic songs.", translation: "বিদ্যালয়ের গানের দল দেশাত্মবোধক গান পরিবেশন করেছিল।" },
  { english: "permit", bangla: "অনুমতি দেওয়া", phonetic: "/pərˈmɪt/", sentence: "Rules do not permit using cellphones during exams.", translation: "পরীক্ষার সময় মুঠোফোন ব্যবহার করা নিয়মে অনুমতি দেয় না।" },
  { english: "persuade", bangla: "প্ররোচিত করা / রাজি করানো", phonetic: "/pərˈsweɪd/", sentence: "She persuaded her brother to read more books.", translation: "সে তার ভাইকে আরও বেশি বই পড়তে রাজি করিয়েছিল।" },
  { english: "pick", bangla: "তোলা / নির্বাচন করা", phonetic: "/pɪk/", sentence: "Pick the sweetest mango from the fruit basket.", translation: "ফলের ঝুড়ি থেকে সবচেয়ে মিষ্টি আমটি বেছে নাও।" },
  { english: "plan", bangla: "পরিকল্পনা করা", phonetic: "/plæn/", sentence: "Plan your daily schedule for better productivity.", translation: "উন্নত উৎপাদনশীলতার জন্য তোমার দৈনন্দিন কাজের পরিকল্পনা করো।" },
  { english: "plant", bangla: "রোপণ করা", phonetic: "/plænt/", sentence: "Plant fruit-bearing trees to save the environment.", translation: "পরিবেশ রক্ষায় ফলদ বৃক্ষ রোপণ করুন।" },
  { english: "play", bangla: "খেলা করা", phonetic: "/pleɪ/", sentence: "Children play joyful games in the afternoon.", translation: "শিশুরা বিকেলে আনন্দের সাথে খেলাধুলা করে।" },
  { english: "point", bangla: "নির্দেশ করা", phonetic: "/pɔɪnt/", sentence: "The teacher pointed to the map on the wall.", translation: "শিক্ষক দেয়ালের মানচিত্রটির দিকে নির্দেশ করেছিলেন।" },
  { english: "pollute", bangla: "দূষিত করা", phonetic: "/pəˈluːt/", sentence: "Smoke and plastic pollute our environment.", translation: "ধোঁয়া ও প্লাস্টিক আমাদের পরিবেশ দূষিত করে।" },
  { english: "postpone", bangla: "স্থগিত রাখা", phonetic: "/poʊstˈpoʊn/", sentence: "The match was postponed due to heavy rain.", translation: "ভারী বৃষ্টির কারণে ম্যাচটি স্থগিত রাখা হয়েছিল।" },
  { english: "pour", bangla: "ঢালা", phonetic: "/pɔːr/", sentence: "Pour hot milk into the ceramic cup.", translation: "চিনামাটির কাপে গরম দুধ ঢালুন।" },
  { english: "practice", bangla: "অনুশীলন করা", phonetic: "/ˈpræktɪs/", sentence: "Practice English conversation with friends daily.", translation: "প্রতিদিন বন্ধুদের সাথে ইংরেজি কথোপকথন অনুশীলন করুন।" },
  { english: "praise", bangla: "প্রশংসা করা", phonetic: "/preɪz/", sentence: "The headmaster praised his outstanding honesty.", translation: "প্রধান শিক্ষক তার অসাধারণ সততার প্রশংসা করেছিলেন।" },
  { english: "pray", bangla: "প্রার্থনা করা", phonetic: "/preɪ/", sentence: "Devout people pray five times daily for peace.", translation: "ধর্মপ্রাণ মানুষ শান্তির জন্য দিনে পাঁচবার প্রার্থনা করেন।" },
  { english: "predict", bangla: "ভবিষ্যদ্বাণী করা", phonetic: "/prɪˈdɪkt/", sentence: "Meteorologists predict heavy rainfall tomorrow.", translation: "আবহাওয়াবিদরা আগামীকাল ভারী বর্ষণের ভবিষ্যদ্বাণী করেছেন।" },
  { english: "prefer", bangla: "অধিক পছন্দ করা", phonetic: "/prɪˈfɜːr/", sentence: "I prefer tea to coffee in the evening.", translation: "সন্ধ্যায় আমি কফির চেয়ে চা বেশি পছন্দ করি।" },
  { english: "prepare", bangla: "প্রস্তুত করা", phonetic: "/prɪˈpɛər/", sentence: "Prepare your lessons thoroughly every evening.", translation: "প্রতি সন্ধ্যায় তোমার পড়া ভালোভাবে প্রস্তুত করো।" },
  { english: "preserve", bangla: "সংরক্ষণ করা", phonetic: "/prɪˈzɜːrv/", sentence: "We must preserve our historical monuments.", translation: "আমাদের অবশ্যই আমাদের ঐতিহাসিক নিদর্শন সংরক্ষণ করতে হবে।" },
  { english: "pretend", bangla: "ভণিতা করা / ভান করা", phonetic: "/prɪˈtɛnd/", sentence: "Do not pretend to know what you do not know.", translation: "যা আপনি জানেন না তা জানার ভান করবেন না।" },
  { english: "prevent", bangla: "প্রতিরোধ করা", phonetic: "/prɪˈvɛnt/", sentence: "Vaccination helps prevent deadly viral diseases.", translation: "টিকাদান মারাত্মক ভাইরাসজনিত রোগ প্রতিরোধ করতে সাহায্য করে।" },
  { english: "produce", bangla: "উৎপাদন করা", phonetic: "/prəˈdjuːs/", sentence: "Fertile land produces bumper crops in Bangladesh.", translation: "বাংলাদেশে উর্বর জমি বাম্পার ফসল উৎপাদন করে।" },
  { english: "progress", bangla: "উন্নতি করা", phonetic: "/prəˈɡrɛs/", sentence: "The student progressed well in English proficiency.", translation: "শিক্ষার্থীটি ইংরেজি দক্ষতায় ভালো উন্নতি করেছে।" },
  { english: "promise", bangla: "প্রতিশ্রুতি দেওয়া", phonetic: "/ˈprɒmɪs/", sentence: "Always fulfill the promise you give to others.", translation: "অন্যদের যে প্রতিশ্রুতি দেন তা সর্বদা পূরণ করুন।" },
  { english: "pronounce", bangla: "উচ্চারণ করা", phonetic: "/prəˈnaʊns/", sentence: "Pronounce English words clearly and accurately.", translation: "ইংরেজি শব্দ স্পষ্টভাবে এবং নির্ভুলভাবে উচ্চারণ করুন।" },
  { english: "protect", bangla: "রক্ষা করা", phonetic: "/prəˈtɛkt/", sentence: "We must protect wildlife and natural forests.", translation: "আমাদের অবশ্যই বন্যপ্রাণী ও প্রাকৃতিক বন রক্ষা করতে হবে।" },
  { english: "prove", bangla: "প্রমাণ করা", phonetic: "/pruːv/", sentence: "Hard work proved his capability to everyone.", translation: "কঠোর পরিশ্রম সবার কাছে তার যোগ্যতা প্রমাণ করেছিল।" },
  { english: "provide", bangla: "সরবরাহ করা / দেওয়া", phonetic: "/prəˈvaɪd/", sentence: "Schools provide books and pencils to students.", translation: "বিদ্যালয় শিক্ষার্থীদের বই ও পেন্সিল সরবরাহ করে।" },
  { english: "publish", bangla: "প্রকাশ করা", phonetic: "/ˈpʌblɪʃ/", sentence: "The board published the SSC examination results.", translation: "বোর্ড এসএসসি পরীক্ষার ফলাফল প্রকাশ করেছে।" },
  { english: "pull", bangla: "টানা", phonetic: "/pʊl/", sentence: "Pull the lever down to start the machine.", translation: "যন্ত্রটি চালু করতে লিভারটি নিচের দিকে টানুন।" },
  { english: "punish", bangla: "শাস্তি দেওয়া", phonetic: "/ˈpʌnɪʃ/", sentence: "Courts punish criminals according to law.", translation: "আদালত আইন অনুযায়ী অপরাধীদের শাস্তি দেয়।" },
  { english: "purchase", bangla: "ক্রয় করা", phonetic: "/ˈpɜːrtʃəs/", sentence: "He purchased a new bicycle for going to school.", translation: "সে স্কুলে যাওয়ার জন্য একটি নতুন সাইকেল ক্রয় করেছিল।" },
  { english: "push", bangla: "ধাক্কা দেওয়া", phonetic: "/pʊʃ/", sentence: "Push the door gently to open it.", translation: "দরজাটি খুলতে আলতো করে ধাক্কা দিন।" },
  { english: "qualify", bangla: "যোগ্যতা অর্জন করা", phonetic: "/ˈkwɒlɪfaɪ/", sentence: "She qualified for the national championship.", translation: "সে জাতীয় চ্যাম্পিয়নশিপের জন্য যোগ্যতা অর্জন করেছিল।" },
  { english: "quarrel", bangla: "ঝগড়া করা", phonetic: "/ˈkwɒrəl/", sentence: "Good friends never quarrel over small matters.", translation: "ভালো বন্ধুরা ছোটখাটো বিষয় নিয়ে কখনো ঝগড়া করে না।" },
  { english: "question", bangla: "প্রশ্ন করা", phonetic: "/ˈkwɛstʃən/", sentence: "Students are encouraged to question curious topics.", translation: "শিক্ষার্থীদের কৌতূহলোদ্দীপক বিষয়ে প্রশ্ন করতে উৎসাহিত করা হয়।" },
  { english: "quit", bangla: "ত্যাগ করা / ছেড়ে দেওয়া", phonetic: "/kwɪt/", sentence: "Never quit trying when pursuing noble goals.", translation: "মহৎ লক্ষ্য অর্জনের প্রচেষ্টায় কখনো হাল ছেড়ে দেবেন না।" },
  { english: "rain", bangla: "বৃষ্টি হওয়া", phonetic: "/reɪn/", sentence: "It rained cats and dogs yesterday afternoon.", translation: "গতকাল বিকেলে মুষলধারে বৃষ্টি হয়েছিল।" },
  { english: "reach", bangla: "পৌঁছানো", phonetic: "/riːtʃ/", sentence: "We reached the hill summit before sunset.", translation: "আমরা সূর্যাস্তের আগেই পাহাড়ের চূড়ায় পৌঁছেছিলাম।" },
  { english: "read", bangla: "পড়া", phonetic: "/riːd/", sentence: "Read good English books to enrich your knowledge.", translation: "তোমার জ্ঞান সমৃদ্ধ করতে ভালো ইংরেজি বই পড়ো।" },
  { english: "realize", bangla: "উপলব্ধি করা", phonetic: "/ˈriːəlaɪz/", sentence: "He realized the importance of punctuality.", translation: "সে সময়নিষ্ঠতার গুরুত্ব উপলব্ধি করতে পেরেছিল।" },
  { english: "receive", bangla: "গ্রহণ করা / পাওয়া", phonetic: "/rɪˈsiːv/", sentence: "I received your cordial letter yesterday.", translation: "আমি গতকাল তোমার আন্তরিক চিঠিটি পেয়েছি।" },
  { english: "recognize", bangla: "চিনতে পারা / স্বীকৃতি দেওয়া", phonetic: "/ˈrɛkəɡnaɪz/", sentence: "The nation recognizes the contribution of teachers.", translation: "জাতি শিক্ষকদের অবদানকে স্বীকৃতি দেয়।" },
  { english: "recommend", bangla: "সুপারিশ করা", phonetic: "/ˌrɛkəˈmɛnd/", sentence: "The doctor recommended a balanced diet.", translation: "ডাক্তার একটি সুষম খাদ্যের সুপারিশ করেছিলেন।" },
  { english: "record", bangla: "নথিভুক্ত করা", phonetic: "/rɪˈkɔːrd/", sentence: "Record your daily quiz scores in a diary.", translation: "একটি ডায়েরিতে তোমার দৈনন্দিন কুইজের স্কোর নথিভুক্ত করো।" },
  { english: "recover", bangla: "সুস্থ হওয়া / উদ্ধার করা", phonetic: "/rɪˈkʌvər/", sentence: "He recovered quickly from the seasonal flu.", translation: "সে মৌসুমী ফ্লু থেকে দ্রুত সুস্থ হয়ে উঠেছিল।" },
  { english: "reduce", bangla: "কমানো / হ্রাস করা", phonetic: "/rɪˈdjuːs/", sentence: "Turn off lights to reduce electricity bills.", translation: "বিদ্যুৎ বিল কমাতে বাতিগুলো বন্ধ করুন।" },
  { english: "refuse", bangla: "প্রত্যাখ্যান করা", phonetic: "/rɪˈfjuːz/", sentence: "He refused to take an unjust bribe.", translation: "সে অন্যায় ঘুষ নিতে প্রত্যাখ্যান করেছিল।" },
  { english: "regret", bangla: "অনুশোচনা করা", phonetic: "/rɪˈɡrɛt/", sentence: "Never do things that you might regret later.", translation: "কখনো এমন কাজ করবেন না যা নিয়ে পরে অনুশোচনা করতে হয়।" },
  { english: "relax", bangla: "বিশ্রাম নেওয়া / স্বস্তি পাওয়া", phonetic: "/rɪˈlæks/", sentence: "Listen to soft music to relax your mind.", translation: "মনকে শিথিল করতে মৃদু সুরের গান শুনুন।" },
  { english: "remain", bangla: "অবশিষ্ট থাকা / থাকা", phonetic: "/rɪˈmeɪn/", sentence: "Remain calm and steadfast during difficult times.", translation: "কঠিন সময়ে শান্ত ও অবিচল থাকুন।" },
  { english: "remember", bangla: "মনে রাখা", phonetic: "/rɪˈmɛmbər/", sentence: "Always remember the advice of your beloved parents.", translation: "সর্বদা তোমার প্রিয় পিতা-মাতার উপদেশ মনে রাখবে।" },
  { english: "remind", bangla: "মনে করিয়ে দেওয়া", phonetic: "/rɪˈmaɪnd/", sentence: "Please remind me to call my grandfather tonight.", translation: "অনুগ্রহ করে আজ রাতে দাদুকে ফোন করার কথা আমাকে মনে করিয়ে দেবেন।" },
  { english: "repair", bangla: "মেরামত করা", phonetic: "/rɪˈpɛər/", sentence: "The mechanic repaired the car's engine.", translation: "মেকানিক গাড়ির ইঞ্জিনটি মেরামত করেছিল।" },
  { english: "repeat", bangla: "পুনরাবৃত্তি করা", phonetic: "/rɪˈpiːt/", sentence: "Repeat the words aloud for correct pronunciation.", translation: "সঠিক উচ্চারণের জন্য শব্দগুলো উচ্চস্বরে পুনরাবৃত্তি করো।" },
  { english: "replace", bangla: "প্রতিস্থাপন করা", phonetic: "/rɪˈpleɪs/", sentence: "Replace worn-out shoes with comfortable ones.", translation: "পুরোনো জুতো বদলে আরামদায়ক জুতো ব্যবহার করুন।" },
  { english: "reply", bangla: "উত্তর দেওয়া", phonetic: "/rɪˈplaɪ/", sentence: "He replied promptly to the urgent email.", translation: "সে জরুরি ইমেলের দ্রুত উত্তর দিয়েছিল।" },
  { english: "report", bangla: "প্রতিবেদন দেওয়া", phonetic: "/rɪˈpɔːrt/", sentence: "Report any suspicious activity to the authority.", translation: "কর্তৃপক্ষের কাছে যেকোনো সন্দেহজনক কার্যকলাপের প্রতিবেদন দিন।" },
  { english: "represent", bangla: "প্রতিনিধিত্ব করা", phonetic: "/ˌrɛprɪˈzɛnt/", sentence: "The diplomat represents his nation abroad.", translation: "কূটনীতিক বিদেশে তার জাতির প্রতিনিধিত্ব করেন।" },
  { english: "request", bangla: "অনুরোধ করা", phonetic: "/rɪˈkwɛst/", sentence: "She requested the teacher for extra guidance.", translation: "সে অতিরিক্ত নির্দেশনার জন্য শিক্ষকের কাছে অনুরোধ করেছিল।" },
  { english: "rescue", bangla: "উদ্ধার করা", phonetic: "/ˈrɛskjuː/", sentence: "Firefighters rescued the family from the blaze.", translation: "অগ্নিনির্বাপক কর্মীরা পরিবারটিকে আগুন থেকে উদ্ধার করেছিলেন।" },
  { english: "research", bangla: "গবেষণা করা", phonetic: "/rɪˈsɜːrtʃ/", sentence: "Scholars research to discover scientific breakthroughs.", translation: "বিজ্ঞানীরা বৈজ্ঞানিক আবিষ্কারের জন্য গবেষণা করেন।" },
  { english: "resist", bangla: "প্রতিরোধ করা", phonetic: "/rɪˈzɪst/", sentence: "The nation resisted foreign oppression courageously.", translation: "জাতি সাহসিকতার সাথে বিদেশি নিপীড়ন প্রতিরোধ করেছিল।" },
  { english: "resolve", bangla: "সমাধান করা / সংকল্প করা", phonetic: "/rɪˈzɒlv/", sentence: "They resolved the dispute amicably.", translation: "তারা শান্তিপূর্ণভাবে বিরোধটির সমাধান করেছিল।" },
  { english: "respect", bangla: "শ্রদ্ধা করা / সম্মান করা", phonetic: "/rɪˈspɛkt/", sentence: "Respect your elders and love the young.", translation: "তোমার বড়দের সম্মান করো এবং ছোটদের ভালোবাসো।" },
  { english: "respond", bangla: "সাড়া দেওয়া", phonetic: "/rɪˈspɒnd/", sentence: "He responded enthusiastically to the invitation.", translation: "সে আমন্ত্রণে উৎসাহের সাথে সাড়া দিয়েছিল।" },
  { english: "rest", bangla: "বিশ্রাম নেওয়া", phonetic: "/rɛst/", sentence: "Take adequate rest after hard physical exercise.", translation: "কঠোর শারীরিক ব্যায়ামের পর পর্যাপ্ত বিশ্রাম নিন।" },
  { english: "restore", bangla: "পুনরুদ্ধার করা", phonetic: "/rɪˈstɔːr/", sentence: "Efforts were made to restore peace in the region.", translation: "অঞ্চলে শান্তি পুনরুদ্ধারের প্রচেষ্টা চালানো হয়েছিল।" },
  { english: "retire", bangla: "অবসর নেওয়া", phonetic: "/rɪˈtaɪər/", sentence: "He will retire after thirty years of noble teaching.", translation: "ত্রিশ বছরের মহান শিক্ষকতার পর তিনি অবসর গ্রহণ করবেন।" },
  { english: "return", bangla: "ফিরে আসা / ফেরত দেওয়া", phonetic: "/rɪˈtɜːrn/", sentence: "Return borrowed books to the library in time.", translation: "ধার নেওয়া বই সময়মতো লাইব্রেরিতে ফেরত দিন।" },
  { english: "reveal", bangla: "প্রকাশ করা / উন্মোচন করা", phonetic: "/rɪˈviːl/", sentence: "Truth will reveal itself sooner or later.", translation: "সত্য আজ হোক বা কাল নিজে থেকেই প্রকাশ পাবে।" },
  { english: "review", bangla: "পর্যালোচনা করা", phonetic: "/rɪˈvjuː/", sentence: "Review your lessons every weekend.", translation: "প্রতি সপ্তাহান্তে তোমার পড়াগুলো পর্যালোচনা করো।" },
  { english: "reward", bangla: "পুরস্কৃত করা", phonetic: "/rɪˈwɔːrd/", sentence: "The school rewarded brilliant students with medals.", translation: "বিদ্যালয় মেধাবী শিক্ষার্থীদের পদক দিয়ে পুরস্কৃত করেছিল।" },
  { english: "ride", bangla: "চড়া / চালনা করা", phonetic: "/raɪd/", sentence: "He rides a bicycle to school every morning.", translation: "সে প্রতিদিন সকালে সাইকেলে চড়ে বিদ্যালয়ে যায়।" },
  { english: "ring", bangla: "ঘণ্টা বাজা / বাজানো", phonetic: "/rɪŋ/", sentence: "The school bell rings at nine sharp.", translation: "ঠিক নয়টায় স্কুলের ঘণ্টা বাজে।" },
  { english: "rise", bangla: "ওঠা / উদিত হওয়া", phonetic: "/raɪz/", sentence: "The golden sun rises in the eastern horizon.", translation: "পূর্ব দিগন্তে সোনালি সূর্য উদিত হয়।" },
  { english: "risk", bangla: "ঝুঁকি নেওয়া", phonetic: "/rɪsk/", sentence: "Brave sailors risk their lives on stormy seas.", translation: "সাহসী নাবিকরা উত্তাল সমুদ্রে নিজেদের জীবন ঝুঁকি নেন।" },
  { english: "run", bangla: "দৌড়ানো", phonetic: "/rʌn/", sentence: "The boy ran fast to win the race.", translation: "দৌড়ে জিততে ছেলেটি দ্রুত দৌড়েছিল।" },
  { english: "rush", bangla: "ছুটে চলা / তাড়াহুড়ো করা", phonetic: "/rʌʃ/", sentence: "Do not rush while crossing busy crossroads.", translation: "ব্যস্ত চৌরাস্তা পার হওয়ার সময় তাড়াহুড়ো করবেন না।" },
  { english: "sail", bangla: "পাল তোলা / নৌভ্রমণ করা", phonetic: "/seɪl/", sentence: "Boats sail gracefully on the river Meghna.", translation: "মেঘনা নদীতে নৌকাগুলো মনোরমভাবে পাল তুলে চলে।" },
  { english: "salute", bangla: "সালাম দেওয়া / সম্মান জানানো", phonetic: "/səˈluːt/", sentence: "Soldiers salute the national flag with dignity.", translation: "সৈন্যরা মর্যাদার সাথে জাতীয় পতাকাকে সালাম জানান।" },
  { english: "save", bangla: "সংরক্ষণ করা / বাঁচানো", phonetic: "/seɪv/", sentence: "Planting trees saves our planet from global warming.", translation: "গাছ লাগানো আমাদের গ্রহকে বৈশ্বিক উষ্ণতা থেকে বাঁচায়।" },
  { english: "say", bangla: "বলা", phonetic: "/seɪ/", sentence: "Always say the truth under all circumstances.", translation: "যেকোনো পরিস্থিতিতে সর্বদা সত্য বলুন।" },
  { english: "scan", bangla: "পুঙ্খানুপুঙ্খ পরীক্ষা করা", phonetic: "/skæn/", sentence: "Scan the text quickly to find key information.", translation: "মূল তথ্য খুঁজে পেতে পাঠ্যটি দ্রুত স্ক্যান করো।" },
  { english: "scare", bangla: "ভয় দেখানো", phonetic: "/skɛər/", sentence: "Loud thunder scared the little children.", translation: "বিকট বজ্রপাত ছোট শিশুদের ভয় দেখিয়েছিল।" },
  { english: "schedule", bangla: "সময়সূচি তৈরি করা", phonetic: "/ˈskɛdʒuːl/", sentence: "Schedule your revision time wisely before finals.", translation: "চূড়ান্ত পরীক্ষার আগে তোমার পুনরাবৃত্তির সময়সূচি বুদ্ধিমানের সাথে তৈরি করো।" },
  { english: "scold", bangla: "বকাঝকা করা", phonetic: "/skoʊld/", sentence: "Parents scold children only for their welfare.", translation: "পিতা-মাতা সন্তানদের কেবল তাদের মঙ্গলের জন্যই বকাঝকা করেন।" },
  { english: "search", bangla: "অনুসন্ধান করা / খোঁজা", phonetic: "/sɜːrtʃ/", sentence: "Search the dictionary for meanings of unfamiliar words.", translation: "অপরিচিত শব্দের অর্থের জন্য অভিধানে অনুসন্ধান করুন।" },
  { english: "secure", bangla: "নিরাপদ করা / সুরক্ষিত করা", phonetic: "/sɪˈkjʊər/", sentence: "Secure your belongings before traveling by train.", translation: "ট্রেনে ভ্রমণের আগে তোমার জিনিসপত্র সুরক্ষিত করো।" },
  { english: "see", bangla: "দেখা", phonetic: "/siː/", sentence: "We see with our eyes and understand with our mind.", translation: "আমরা চোখ দিয়ে দেখি এবং মন দিয়ে বুঝি।" },
  { english: "seek", bangla: "খোঁজা / অন্বেষণ করা", phonetic: "/siːk/", sentence: "Seek knowledge from the cradle to the grave.", translation: "দোলনা থেকে কবর পর্যন্ত জ্ঞান অন্বেষণ করুন।" },
  { english: "select", bangla: "নির্বাচন করা / বেছে নেওয়া", phonetic: "/sɪˈlɛkt/", sentence: "Select the most appropriate adjective for each sentence.", translation: "প্রতিটি বাক্যের জন্য সর্বাধিক উপযুক্ত বিশেষণটি নির্বাচন করুন।" },
  { english: "sell", bangla: "বিক্রি করা", phonetic: "/sɛl/", sentence: "Farmers sell fresh vegetables in the local bazaar.", translation: "কৃষকরা স্থানীয় বাজারে তাজা শাকসবজি বিক্রি করেন।" },
  { english: "send", bangla: "পাঠানো", phonetic: "/sɛnd/", sentence: "Send your application letter by registered post.", translation: "রেজিস্ট্রি ডাকে তোমার আবেদনপত্রটি পাঠাও।" },
  { english: "serve", bangla: "সেবা করা / পরিবেশন করা", phonetic: "/sɜːrv/", sentence: "Serve mankind with love, humility, and sincerity.", translation: "ভালোবাসা, বিনয় ও আন্তরিকতার সাথে মানবজাতির সেবা করুন।" },
  { english: "settle", bangla: "মীমাংসা করা / বসবাস শুরু করা", phonetic: "/ˈsɛtl/", sentence: "They settled the land dispute amicably.", translation: "তারা জমির বিরোধটি শান্তিপূর্ণভাবে মীমাংসা করেছিল।" },
  { english: "shake", bangla: "নাড়ানো / করমর্দন করা", phonetic: "/ʃeɪk/", sentence: "Shake hands warmly when you meet someone.", translation: "কারো সাথে দেখা হলে উষ্ণভাবে করমর্দন করুন।" },
  { english: "share", bangla: "ভাগাভাগি করা", phonetic: "/ʃɛər/", sentence: "Share your knowledge and happiness with others.", translation: "অন্যদের সাথে তোমার জ্ঞান ও সুখ ভাগাভাগি করো।" },
  { english: "shine", bangla: "উজ্জ্বল হওয়া / আলো ছড়ানো", phonetic: "/ʃaɪn/", sentence: "Stars shine brightly in the dark night sky.", translation: "অন্ধকার রাতের আকাশে তারারা উজ্জ্বল আলো ছড়ায়।" },
  { english: "shoot", bangla: "গুলি করা / নিক্ষেপ করা", phonetic: "/ʃuːt/", sentence: "The hunter shot an arrow at the target.", translation: "শিকারি লক্ষ্যের দিকে একটি তীর নিক্ষেপ করেছিল।" },
  { english: "shout", bangla: "চিৎকার করা", phonetic: "/ʃaʊt/", sentence: "Do not shout in the quiet library room.", translation: "শান্ত লাইব্রেরি কক্ষে চিৎকার করবেন না।" },
  { english: "show", bangla: "দেখানো", phonetic: "/ʃoʊ/", sentence: "Show respect to all people regardless of their status.", translation: "মর্যাদা নির্বিশেষে সকল মানুষকে সম্মান দেখান।" },
  { english: "shut", bangla: "বন্ধ করা", phonetic: "/ʃʌt/", sentence: "Shut the gate before leaving the premises.", translation: "প্রাঙ্গণ ত্যাগ করার আগে ফটকটি বন্ধ করো।" },
  { english: "sing", bangla: "গান গাওয়া", phonetic: "/sɪŋ/", sentence: "The cuckoo sings melodiously in springtime.", translation: "বসন্তকালে কোকিল সুরেলা কণ্ঠে গান গায়।" },
  { english: "sit", bangla: "বসা", phonetic: "/sɪt/", sentence: "Sit straight while reading to maintain good posture.", translation: "ভালো ভঙ্গিমা বজায় রাখতে পড়ার সময় সোজা হয়ে বসুন।" },
  { english: "sleep", bangla: "ঘুমানো", phonetic: "/sliːp/", sentence: "Get eight hours of sound sleep every night.", translation: "প্রতি রাতে আট ঘণ্টার গভীর ঘুম নিশ্চিত করুন।" },
  { english: "slide", bangla: "পিছলে যাওয়া", phonetic: "/slaɪd/", sentence: "Children slide joyfully down the playground slide.", translation: "শিশুরা খেলার মাঠের স্লাইডে আনন্দের সাথে পিছলে নামে।" },
  { english: "smell", bangla: "ঘ্রাণ নেওয়া / গন্ধ পাওয়া", phonetic: "/smɛl/", sentence: "Roses smell sweet and enchanting in the garden.", translation: "বাগানে গোলাপের ঘ্রাণ মিষ্টি ও মোহনীয় লাগে।" },
  { english: "smile", bangla: "হাসা / মৃদু হাসা", phonetic: "/smaɪl/", sentence: "A genuine smile wins everyone's heart.", translation: "একটি খাঁটি হাসি সবার মন জয় করে নেয়।" },
  { english: "smoke", bangla: "ধূমপান করা", phonetic: "/smoʊk/", sentence: "Smoking is extremely harmful to human health.", translation: "ধূমপান মানব স্বাস্থ্যের জন্য অত্যন্ত ক্ষতিকর।" },
  { english: "solve", bangla: "সমাধান করা", phonetic: "/sɒlv/", sentence: "Practice daily to solve difficult mathematical problems.", translation: "কঠিন গাণিতিক সমস্যা সমাধান করতে প্রতিদিন অনুশীলন করুন।" },
  { english: "speak", bangla: "কথা বলা", phonetic: "/spiːk/", sentence: "Speak the truth and shun falsehood forever.", translation: "সত্য কথা বলুন এবং মিথ্যাকে চিরতরে পরিহার করুন।" },
  { english: "spend", bangla: "ব্যয় করা / কাটানো", phonetic: "/spɛnd/", sentence: "Spend your free time reading informative books.", translation: "তথ্যপূর্ণ বই পড়ে তোমার অবসর সময় কাটাও।" },
  { english: "spread", bangla: "ছড়িয়ে দেওয়া", phonetic: "/sprɛd/", sentence: "Spread love, peace, and knowledge wherever you go.", translation: "যেখানেই যান ভালোবাসা, শান্তি ও জ্ঞান ছড়িয়ে দিন।" },
  { english: "stand", bangla: "দাঁড়ানো", phonetic: "/stænd/", sentence: "Always stand beside the oppressed and needy.", translation: "সর্বদা নিপীড়িত ও অসহায় মানুষের পাশে দাঁড়ান।" },
  { english: "start", bangla: "শুরু করা", phonetic: "/stɑːrt/", sentence: "Start your journey of English learning right now.", translation: "এখনই তোমার ইংরেজি শেখার যাত্রা শুরু করো।" },
  { english: "stay", bangla: "থাকা / অবস্থান করা", phonetic: "/steɪ/", sentence: "Stay focused on your educational goals.", translation: "তোমার শিক্ষাগত লক্ষ্যের প্রতি অবিচল থাকো।" },
  { english: "steal", bangla: "চুরি করা", phonetic: "/stiːl/", sentence: "Stealing is a punishable social crime.", translation: "চুরি করা একটি শাস্তিযোগ্য সামাজিক অপরাধ।" },
  { english: "stick", bangla: "আটকে থাকা / আঁকড়ে থাকা", phonetic: "/stɪk/", sentence: "Stick to your principles even in difficult moments.", translation: "কঠিন মুহূর্তেও নিজের নীতির প্রতি অবিচল থাকুন।" },
  { english: "stop", bangla: "থামানো / থামা", phonetic: "/stɒp/", sentence: "Vehicles must stop when the red traffic light shines.", translation: "লাল ট্রাফিক বাতি জ্বললে যানবাহন অবশ্যই থামবে।" },
  { english: "strengthen", bangla: "শক্তিশালী করা", phonetic: "/ˈstrɛŋθn/", sentence: "Nutritious food strengthens the immune system.", translation: "পুষ্টিকর খাবার রোগ প্রতিরোধ ক্ষমতাকে শক্তিশালী করে।" },
  { english: "strive", bangla: "কঠোর প্রচেষ্টা করা", phonetic: "/straɪv/", sentence: "Strive tirelessly for excellence in every field.", translation: "প্রতিটি ক্ষেত্রে শ্রেষ্ঠত্ব অর্জনের জন্য অক্লান্ত প্রচেষ্টা করুন।" },
  { english: "study", bangla: "অধ্যয়ন করা", phonetic: "/ˈstʌdi/", sentence: "Study attentively to build a prosperous career.", translation: "সমৃদ্ধ কর্মজীবন গড়তে মনোযোগ দিয়ে অধ্যয়ন করো।" },
  { english: "succeed", bangla: "সফল হওয়া", phonetic: "/səkˈsiːd/", sentence: "Those who persevere will surely succeed.", translation: "যারা অধ্যবসায়ী তারা অবশ্যই সফল হবে।" },
  { english: "suffer", bangla: "ভোগা / কষ্ট পাওয়া", phonetic: "/ˈsʌfər/", sentence: "Flood victims suffered immensely without shelter.", translation: "আশ্রয়হীন হয়ে বন্যার্তরা চরম কষ্ট ভোগ করেছিল।" },
  { english: "suggest", bangla: "পরামর্শ দেওয়া", phonetic: "/səˈdʒɛst/", sentence: "He suggested an innovative idea for the project.", translation: "সে প্রকল্পের জন্য একটি উদ্ভাবনী ধারণার পরামর্শ দিয়েছিল।" },
  { english: "supply", bangla: "সরবরাহ করা", phonetic: "/səˈplaɪ/", sentence: "The government supplies free textbooks every year.", translation: "সরকার প্রতি বছর বিনামূল্যে পাঠ্যবই সরবরাহ করে।" },
  { english: "support", bangla: "সমর্থন করা / সাহায্য করা", phonetic: "/səˈpɔːrt/", sentence: "Parents support their children in every step.", translation: "পিতা-মাতা প্রতিটি পদক্ষেপে তাদের সন্তানদের সমর্থন করেন।" },
  { english: "survive", bangla: "বেঁচে থাকা", phonetic: "/sərˈvaɪv/", sentence: "Many species adapt to survive in harsh weather.", translation: "অনেক প্রজাতি বৈরী আবহাওয়ায় টিকে থাকার জন্য মানিয়ে নেয়।" },
  { english: "swim", bangla: "সাঁতার কাটা", phonetic: "/swɪm/", sentence: "Village boys swim delightfully in the pond.", translation: "গ্রামের ছেলেরা পুকুরে আনন্দের সাথে সাঁতার কাটে।" },
  { english: "take", bangla: "নেওয়া", phonetic: "/teɪk/", sentence: "Take regular physical exercise to stay fit.", translation: "সুস্থ থাকতে নিয়মিত শারীরিক ব্যায়াম করুন।" },
  { english: "talk", bangla: "কথা বলা", phonetic: "/tɔːk/", sentence: "Talk softly and politely in formal places.", translation: "আনুষ্ঠানিক স্থানে মৃদু ও ভদ্রভাবে কথা বলুন।" },
  { english: "taste", bangla: "স্বাদ নেওয়া", phonetic: "/teɪst/", sentence: "Taste the freshly baked honey cookies.", translation: "সদ্য প্রস্তুত মধুর বিস্কুটের স্বাদ নিন।" },
  { english: "teach", bangla: "শেখানো / শিক্ষা দেওয়া", phonetic: "/tiːtʃ/", sentence: "Dedicated teachers teach students with great care.", translation: "নিবেদিতপ্রাণ শিক্ষকরা পরম যত্নে শিক্ষার্থীদের শিক্ষা দেন।" },
  { english: "tear", bangla: "ছেঁড়া / অশ্রুপাত করা", phonetic: "/tɛər/", sentence: "Do not tear pages from your school notebooks.", translation: "তোমার স্কুলের খাতা থেকে পাতা ছিঁড়বে না।" },
  { english: "tell", bangla: "বলা", phonetic: "/tɛl/", sentence: "Tell me an interesting moral story.", translation: "আমাকে একটি শিক্ষণীয় নীতিগল্প বলো।" },
  { english: "test", bangla: "পরীক্ষা করা", phonetic: "/tɛst/", sentence: "Examinations test students' comprehension skills.", translation: "পরীক্ষা শিক্ষার্থীদের বোধগম্যতার দক্ষতা পরীক্ষা করে।" },
  { english: "thank", bangla: "ধন্যবাদ জানানো", phonetic: "/θæŋk/", sentence: "Always thank those who assist you selflessly.", translation: "যারা আপনাকে নিঃস্বার্থভাবে সাহায্য করে সর্বদা তাদের ধন্যবাদ জানান।" },
  { english: "think", bangla: "চিন্তা করা / ভাবা", phonetic: "/θɪŋk/", sentence: "Think deeply before you take any critical step.", translation: "যেকোনো গুরুত্বপূর্ণ পদক্ষেপ নেওয়ার আগে গভীরভাবে চিন্তা করুন।" },
  { english: "threaten", bangla: "হুমকি দেওয়া", phonetic: "/ˈθrɛtn/", sentence: "Pollution threatens the marine biodiversity.", translation: "দূষণ সামুদ্রিক জীববৈচিত্র্যকে হুমকির মুখে ফেলে।" },
  { english: "throw", bangla: "নিক্ষেপ করা / ফেলা", phonetic: "/θroʊ/", sentence: "Throw household garbage into the dustbin.", translation: "গৃহস্থালির বর্জ্য ডাস্টবিনে ফেলুন।" },
  { english: "touch", bangla: "স্পর্শ করা", phonetic: "/tʌtʃ/", sentence: "Do not touch live electrical wires.", translation: "বৈদ্যুতিক খোলা তার স্পর্শ করবেন না।" },
  { english: "train", bangla: "প্রশিক্ষণ দেওয়া", phonetic: "/treɪn/", sentence: "Experts train primary teachers in modern pedagogy.", translation: "বিশেষজ্ঞরা প্রাথমিক শিক্ষকদের আধুনিক শিক্ষণপদ্ধতিতে প্রশিক্ষণ দেন।" },
  { english: "transform", bangla: "রূপান্তরিত করা", phonetic: "/trænsˈfɔːrm/", sentence: "Education transforms human mindset positively.", translation: "শিক্ষা মানুষের মানসিকতাকে ইতিবাচকভাবে রূপান্তরিত করে।" },
  { english: "translate", bangla: "অনুবাদ করা", phonetic: "/trænsˈleɪt/", sentence: "Translate each English sentence into correct Bengali.", translation: "প্রতিটি ইংরেজি বাক্য সঠিক বাংলায় অনুবাদ করুন।" },
  { english: "travel", bangla: "ভ্রমণ করা", phonetic: "/ˈtrævl/", sentence: "Traveling broadens our knowledge and worldview.", translation: "ভ্রমণ আমাদের জ্ঞান ও বিশ্বদৃষ্টিকে প্রসারিত করে।" },
  { english: "trust", bangla: "বিশ্বাস করা", phonetic: "/trʌst/", sentence: "Trust honest friends who stand by you.", translation: "যে সৎ বন্ধুরা পাশে থাকে তাদের বিশ্বাস করুন।" },
  { english: "try", bangla: "চেষ্টা করা", phonetic: "/traɪ/", sentence: "Try your utmost best to achieve your goals.", translation: "তোমার লক্ষ্য অর্জনে সর্বোচ্চ চেষ্টা করো।" },
  { english: "turn", bangla: "ঘোরা / ঘোরানো", phonetic: "/tɜːrn/", sentence: "Turn left at the next street intersection.", translation: "পরবর্তী রাস্তার মোড়ে বামে ঘুরুন।" },
  { english: "understand", bangla: "বোঝা / উপলব্ধি করা", phonetic: "/ˌʌndərˈstænd/", sentence: "Understand the true grammar concepts thoroughly.", translation: "ব্যাকরণের সঠিক ধারণাগুলো গভীরভাবে উপলব্ধি করুন।" },
  { english: "unite", bangla: "ঐক্যবদ্ধ হওয়া", phonetic: "/juˈnaɪt/", sentence: "People united to rebuild the damaged embankment.", translation: "ক্ষতিগ্রস্ত বাঁধ পুনর্নির্মাণে মানুষ ঐক্যবদ্ধ হয়েছিল।" },
  { english: "unlock", bangla: "তালা খোলা / উন্মুক্ত করা", phonetic: "/ʌnˈlɒk/", sentence: "Education unlocks doors to endless opportunities.", translation: "শিক্ষা অফুরন্ত সুযোগের দরজা উন্মুক্ত করে।" },
  { english: "update", bangla: "হালনাগাদ করা", phonetic: "/ʌpˈdeɪt/", sentence: "Update your general knowledge regularly.", translation: "তোমার সাধারণ জ্ঞান নিয়মিত হালনাগাদ রাখো।" },
  { english: "use", bangla: "ব্যবহার করা", phonetic: "/juːz/", sentence: "Use polite and gentle words when conversing.", translation: "কথা বলার সময় ভদ্র ও নম্র শব্দ ব্যবহার করুন।" },
  { english: "utilize", bangla: "কাজে লাগানো / সদ্ব্যবহার করা", phonetic: "/ˈjuːtəlaɪz/", sentence: "Utilize every minute of your precious time.", translation: "তোমার মূল্যবান সময়ের প্রতি মিনিটের সদ্ব্যবহার করো।" },
  { english: "vanish", bangla: "অদৃশ্য হওয়া", phonetic: "/ˈvænɪʃ/", sentence: "The magician made the pigeon vanish into thin air.", translation: "জাদুকর কবুতরটিকে শূন্যে অদৃশ্য করে দিয়েছিলেন।" },
  { english: "verify", bangla: "যাচাই করা", phonetic: "/ˈvɛrɪfaɪ/", sentence: "Verify information before believing online rumors.", translation: "অনলাইনের গুজবে বিশ্বাস করার আগে তথ্য যাচাই করুন।" },
  { english: "visit", bangla: "পরিদর্শন করা / দেখা করতে যাওয়া", phonetic: "/ˈvɪzɪt/", sentence: "We visited historical landmarks in Sonargaon.", translation: "আমরা সোনারগাঁয়ের ঐতিহাসিক নিদর্শন পরিদর্শন করেছিলাম।" },
  { english: "vote", bangla: "ভোট দেওয়া", phonetic: "/voʊt/", sentence: "Every eligible adult citizen has the right to vote.", translation: "প্রত্যেক যোগ্য প্রাপ্তবয়স্ক নাগরিকের ভোট দেওয়ার অধিকার রয়েছে।" },
  { english: "wait", bangla: "অপেক্ষা করা", phonetic: "/weɪt/", sentence: "Wait patiently until your turn arrives.", translation: "তোমার পালা আসা পর্যন্ত ধৈর্য ধরে অপেক্ষা করো।" },
  { english: "walk", bangla: "হাঁটা", phonetic: "/wɔːk/", sentence: "Walking in the morning is healthy and invigorating.", translation: "সকালে হাঁটা স্বাস্থ্যকর ও সতেজতাদায়ী।" },
  { english: "want", bangla: "চাওয়া", phonetic: "/wɒnt/", sentence: "I want to become an enlightened scholar.", translation: "আমি একজন আলোকিত পণ্ডিত হতে চাই।" },
  { english: "warn", bangla: "সতর্ক করা", phonetic: "/wɔːrn/", sentence: "The lighthouse warned ships of hidden rocky reefs.", translation: "বাতিঘর জাহাজগুলোকে লুকিয়ে থাকা পাথুরে শৈলশিরা সম্পর্কে সতর্ক করেছিল।" },
  { english: "wash", bangla: "ধোয়া / পরিষ্কার করা", phonetic: "/wɒʃ/", sentence: "Wash fruits thoroughly before eating.", translation: "খাওয়ার আগে ফল ভালোভাবে ধুয়ে নিন।" },
  { english: "waste", bangla: "অপচয় করা", phonetic: "/weɪst/", sentence: "Never waste precious water or electricity.", translation: "মূল্যবান পানি বা বিদ্যুৎ কখনো অপচয় করবেন না।" },
  { english: "watch", bangla: "দেখা / পাহারা দেওয়া", phonetic: "/wɒtʃ/", sentence: "Watch educational English shows to improve fluency.", translation: "কথ্য দক্ষতা বাড়াতে শিক্ষামূলক ইংরেজি অনুষ্ঠান দেখুন।" },
  { english: "wear", bangla: "পরিধান করা / পরা", phonetic: "/wɛər/", sentence: "Students wear neat school uniforms proudly.", translation: "শিক্ষার্থীরা গর্বের সাথে পরিচ্ছন্ন স্কুলের পোশাক পরে।" },
  { english: "weep", bangla: "অশ্রুপাত করা / কাঁদা", phonetic: "/wiːp/", sentence: "She wept joyful tears when her son passed.", translation: "ছেলে পাস করায় সে আনন্দের অশ্রু ফেলেছিল।" },
  { english: "weigh", bangla: "ওজন করা", phonetic: "/weɪ/", sentence: "The merchant weighed the grains on the balance.", translation: "বণিক দাঁড়িপাল্লায় শস্য ওজন করেছিলেন।" },
  { english: "welcome", bangla: "স্বাগত জানানো", phonetic: "/ˈwɛlkəm/", sentence: "We welcome all learners to our English learning app.", translation: "আমাদের ইংরেজি শিক্ষা অ্যাপে আমরা সকল শিক্ষার্থীকে স্বাগত জানাই।" },
  { english: "win", bangla: "জয়লাভ করা / জেতা", phonetic: "/wɪn/", sentence: "Diligence and honesty always win in the long run.", translation: "পরিশ্রম ও সততা অবশেষে সর্বদা জয়লাভ করে।" },
  { english: "wish", bangla: "শুভেচ্ছা জানানো / কামনা করা", phonetic: "/wɪʃ/", sentence: "We wish you peace, success, and prosperity.", translation: "আমরা আপনার শান্তি, সাফল্য ও সমৃদ্ধি কামনা করি।" },
  { english: "work", bangla: "কাজ করা / পরিশ্রম করা", phonetic: "/wɜːrk/", sentence: "Work hard with devotion to realize your dreams.", translation: "তোমার স্বপ্ন বাস্তবায়নে নিষ্ঠার সাথে কাজ করো।" },
  { english: "worry", bangla: "উদ্বিগ্ন হওয়া", phonetic: "/ˈwʌri/", sentence: "Do not worry about mistakes; learn from them.", translation: "ভুল নিয়ে চিন্তিত হবেন না; সেগুলো থেকে শিখুন।" },
  { english: "wrap", bangla: "মোড়ানো", phonetic: "/ræp/", sentence: "She wrapped the gift in glossy paper.", translation: "সে উজ্জ্বল কাগজ দিয়ে উপহারটি মুড়িয়েছিল।" },
  { english: "write", bangla: "লেখা", phonetic: "/raɪt/", sentence: "Write daily journals to enhance English expression.", translation: "ইংরেজি প্রকাশভঙ্গি বাড়াতে প্রতিদিন দিনলিপি লিখুন।" },
  { english: "yawn", bangla: "হাই তোলা", phonetic: "/jɔːn/", sentence: "The sleepy student yawned during late evening study.", translation: "ঘুমন্ত শিক্ষার্থী গভীর সন্ধ্যার পড়াশোনার সময় হাই তুলেছিল।" },
  { english: "yield", bangla: "উৎপাদন করা / নতি স্বীকার করা", phonetic: "/jiːld/", sentence: "Organic farming yields healthy and fresh crops.", translation: "জৈব চাষ স্বাস্থ্যকর ও তাজা ফসল উৎপাদন করে।" }
];

console.log('Base verbs added:', baseVocab.length);
